#!/usr/bin/env python3
"""
export_xfer.py - the transfer minigame's board, converted to BBC MODE 1.

Emits src/data/xferboard.asm.

WHAT THE BOARD IS
-----------------
SubGameSelectSide ($E016) writes three rows from SubGameTopLines_dat
($E613), then ONE row from SubGameLine_dat ($E68B) twelve times, then one
from SubGameBottomLine_dat ($E6B3). So the data is only 200 bytes and the
twelve middle rows are identical - each is a wire running from the
player's vertical bus at column 3, right along columns 4-17 into the
central result bar at 19-20, and the mirror of that from the CPU's bus at
column 36.

Fifteen distinct character codes are used (plus 0 for blank), all from the
$7800 charset the deck tiles come from. They are exported here as their
own small MODE 1 set rather than going through BuildCharset, because
unlike the tiles they are NOT deck-coloured - and because extending the
137-character remap pushes the charset at &0400 into the MOS's NMI area
at &0D00.

THE MULTICOLOUR PAIRS AND WHY 11 MATTERS
----------------------------------------
These are C64 MULTICOLOUR characters: a byte is four 2-bit pairs, each
drawn two pixels wide. The values map

    00 -> background        10 -> $D023
    01 -> $D022             11 -> COLOUR RAM, per character cell

and 11 is the one the transfer game uses to show ownership -
xfer_Colorize4 writes colour RAM and does nothing else. So the pixels a
per-owner variant would have to recolour are exactly the 11 pairs, which
is what makes "three copies of each character" cheap. This exporter emits
the NEUTRAL set, with 11 -> logical 3; the owned variants are the same
bytes with the 3s rewritten and are not emitted yet.

MODE 1 conversion is export_bbc.py's, unchanged: each C64 pixel becomes
two MODE 1 pixels, the left byte of a scanline carries C64 pixels 0,0,1,1
and the right byte 2,2,3,3, and a character is 16 bytes - the left half's
8 scanlines then the right half's.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'xferboard.asm'

CHARSET = 0x7800
TOP = 0xE613          # 3 rows of 40
MIDDLE = 0xE68B       # 1 row of 40, repeated
BOTTOM = 0xE6B3       # 1 row of 40
COLS = 40

# C64 multicolour pair -> BBC MODE 1 logical colour.
PAIR_TO_LOGICAL = {0: 0, 1: 1, 2: 2, 3: 3}


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def mode1_char(mem, code):
    """One C64 multicolour character -> 16 MODE 1 bytes, left half then right."""
    left, right = [], []
    for row in range(8):
        b = mem[CHARSET + code * 8 + row]
        pairs = [(b >> 6) & 3, (b >> 4) & 3, (b >> 2) & 3, b & 3]
        # each C64 pixel is two MODE 1 pixels: 0,0,1,1 then 2,2,3,3
        for half, src in ((left, pairs[0:2]), (right, pairs[2:4])):
            byte = 0
            for n, p in enumerate((src[0], src[0], src[1], src[1])):
                c = PAIR_TO_LOGICAL[p]
                if c & 2:
                    byte |= 0x80 >> n
                if c & 1:
                    byte |= 0x08 >> n
            half.append(byte)
    return left + right


def main():
    mem = load_memory()
    top = [mem[TOP + i] for i in range(3 * COLS)]
    mid = [mem[MIDDLE + i] for i in range(COLS)]
    bot = [mem[BOTTOM + i] for i in range(COLS)]

    codes = sorted(set(top + mid + bot))
    assert codes[0] == 0, 'expected blank to be code 0'
    index = {c: i for i, c in enumerate(codes)}

    out = []
    out.append('\\ ============================================================')
    out.append('\\ xferboard.asm - GENERATED by tools/export_xfer.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The transfer minigame board: SubGameTopLines_dat ($E613), three')
    out.append('\\ rows; SubGameLine_dat ($E68B), ONE row the original repeats twelve')
    out.append('\\ times; SubGameBottomLine_dat ($E6B3), one row. 200 bytes, and the')
    out.append('\\ repeat is why.')
    out.append('\\')
    out.append('\\ The %d distinct characters come from the $7800 charset the deck tiles' % len(codes))
    out.append('\\ use, but are exported HERE rather than through BuildCharset: unlike')
    out.append('\\ the tiles they are not deck-coloured, and extending that remap pushes')
    out.append('\\ the charset at &0400 into the MOS NMI area at &0D00.')
    out.append('\\')
    out.append('\\ NEUTRAL ONLY. The C64 shows ownership in colour RAM, per cell, which')
    out.append('\\ MODE 1 has none of - see docs/layer-10-transfer.md section 5. The')
    out.append('\\ pixels that would have to change are exactly the multicolour 11')
    out.append('\\ pairs, which come out as logical 3 here.')
    out.append('')
    out.append('XB_CHARS = %d' % len(codes))
    out.append('XB_COLS  = %d' % COLS)
    out.append('')

    out.append('\\ C64 character code -> index into xbChars. Only these %d occur.' % len(codes))
    out.append('.xbCode')
    out.append('  EQUB ' + ', '.join('&%02X' % c for c in codes))
    out.append('')

    out.append('\\ 16 bytes each: the left half\'s 8 scanlines then the right half\'s.')
    out.append('.xbChars')
    for c in codes:
        data = mode1_char(mem, c)
        out.append('  \\ code &%02X' % c)
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in data))
    out.append('.xbChars_end')
    out.append('ASSERT xbChars_end - xbChars == XB_CHARS * 16')
    out.append('')

    def rows(name, data, n):
        out.append('.%s' % name)
        for r in range(n):
            out.append('  EQUB ' + ', '.join('&%02X' % index[b] for b in data[r*COLS:(r+1)*COLS]))

    out.append('\\ Rows as GLYPH INDICES, not C64 codes, so the draw needs no lookup.')
    rows('xbTop', top, 3)
    out.append('')
    rows('xbMid', mid, 1)
    out.append('')
    rows('xbBottom', bot, 1)
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    total = len(codes) * 16 + 5 * COLS + len(codes)
    print(f'wrote {OUT}')
    print(f'  {len(codes)} characters, {len(codes)*16} B; board 5 rows, {5*COLS} B; total {total} B')
    print('  codes: ' + ' '.join('$%02X' % c for c in codes))


if __name__ == '__main__':
    main()
