#!/usr/bin/env python3
"""
export_player.py - Build the player droid sprite as BBC MODE 1 blitter data.

Emits src/data/player.asm.

Where the sprite comes from
---------------------------
There is no player sprite in the C64 data. Every droid's sprite is CONSTRUCTED
at runtime in the dynamic sprite area at $5200-$53FF, which ships zeroed:

  BuildDroidSprite ($3C77)  writes the three-digit droid number into sprite
                            rows 6-13, one 4-pixel-wide digit per byte column.
  AnimateDroids    ($3CFB)  writes the spinning ring into rows 0-4 and 15-19
                            from the RotAnim_* tables, indexed by a counter
                            kept in the sprite's own pad byte ($3F).

Rows 5, 14 and 20 are never written, so they stay transparent. That is the
whole sprite: a rotor above and below, the droid's number in the middle.

The ring has 8 phases, so there are 8 frames. The bottom half is the top half
in reverse ROW order (row 15 = row 4, 16 = 3, 17 = 2), not mirrored left to
right - AnimateDroids writes the same L/M/R bytes both times. Rows 0/1/18/19
carry only a middle byte, from a 2-entry table indexed by phase >> 2; the
bottom pair uses the other entry, so the two ends of the rotor alternate.

Droid 001 is the player: DCent_t[0] = 0 and DNum_t[0] = $01, giving digits
0, 0, 1.

Colour
------
A C64 multicolour sprite's bit pairs mean:

  00  transparent
  01  $D025 sprite multicolour 0  = $F0 -> black   (set at $10CE)
  10  the sprite's own colour     = $F1 -> white   (sprite 7, set by AnimateDroids)
  11  $D026 sprite multicolour 1  = $F8 -> orange  (set at $12D5)

MODE 1's four logical colours are the deck's, and they are not these - the
palette is rebuilt per deck by export_bbc.assign_palette. So the three sprite
colours are mapped onto logical 1-3 by role rather than by value, below. The
player consequently changes colour with the deck, exactly as the tiles do.

Output format
-------------
The blitter walks the sprite one scanline at a time, because a 21-row sprite
does not align to the 8-scanline groups BBC screen memory uses and the play
buffer is a circular strip anyway. One scanline is 24 px = 6 MODE 1 bytes, so
a row is stored as 6 data bytes followed by 6 mask bytes:

    result = (background AND mask) OR data

Only 13 distinct rows are stored, not 21: the 5 ring rows per frame, plus the
8 digit rows shared by every frame. 8*5*12 + 8*12 = 576 bytes.

Requires: Python 3. No third-party dependencies.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from rip_levels import parse_listing  # noqa: E402

PROJECT = Path(__file__).resolve().parent.parent
LST_FILE = PROJECT / 'paradroid_ce.lst'
OUT_DIR = PROJECT / 'src' / 'data'

# --- C64 addresses ---------------------------------------------------------
ROT_2_17L = 0x6B0E
ROT_2_17M = 0x6B16
ROT_3_16L = 0x6B1E
ROT_3_16M = 0x6B26
ROT_3_16R = 0x6B2E
ROT_4_15L = 0x6B36
ROT_4_15M = 0x6B3E
ROT_4_15R = 0x6B46
ROT_0_19M = 0x6B4E          # 2 entries
ROT_1_18M = 0x6B50          # 2 entries

NUM_DATA_OFFSET = 0x6AA4    # digit -> offset into NumData
NUM_DATA = 0x6AAE

DCENT_T = 0xEA00            # droid type -> hundreds digit
DNUM_T = 0xEA20             # droid type -> tens/units, packed BCD

PLAYER_TYPE = 0             # droid 001

# AnimateDroids writes $80 into the right-hand byte of rows 2 and 17. There is
# no RotAnim_2_17R table; the accumulator still holds $80 from the row above.
ROW_2_17_R = 0x80

SPRITE_ROWS = 21
FRAMES = 8

# C64 sprite bit pair -> BBC MODE 1 logical colour. 0 is the background and
# is never used, because 00 is transparent.
COLOUR = {
    0b00: None,             # transparent
    0b01: 2,                # black  -> logical 2, which assign_palette
                            #           prefers to put on physical black
    0b10: 1,                # white  -> logical 1, the highlight
    0b11: 3,                # orange -> logical 3, the grid/accent colour
}

BANNER = """\\ ============================================================
\\ {name}
\\ GENERATED by tools/export_player.py - do not edit by hand.
\\ Source: paradroid_ce.lst (Paradroid Redux, C64)
\\ {desc}
\\ ============================================================
"""


def emit_bytes(f, data, per_line=12):
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        f.write('  EQUB ' + ','.join('&%02X' % b for b in chunk) + '\n')


def build_c64_rows(mem):
    """The 8 ring frames and the shared digit block, as C64 sprite bytes.

    Returns (frames, digits) where frames[f] is 5 rows of 3 bytes (sprite rows
    0-4) and digits is 8 rows of 3 bytes (sprite rows 6-13).
    """
    frames = []
    for phase in range(FRAMES):
        top = mem[ROT_0_19M + (phase >> 2)]
        rows = [
            [0, top, 0],                                        # row 0
            [0, mem[ROT_1_18M + (phase >> 2)], 0],              # row 1
            [mem[ROT_2_17L + phase], mem[ROT_2_17M + phase], ROW_2_17_R],
            [mem[ROT_3_16L + phase], mem[ROT_3_16M + phase], mem[ROT_3_16R + phase]],
            [mem[ROT_4_15L + phase], mem[ROT_4_15M + phase], mem[ROT_4_15R + phase]],
        ]
        frames.append(rows)

    # The bottom pair of rows uses the OTHER entry of the 2-entry tables:
    # AnimateDroids does INX / AND #1 between writing the top and the bottom.
    # Rows 15-17 reuse rows 4-2 unchanged, so only 0/1 need the alternate.
    bottoms = []
    for phase in range(FRAMES):
        other = ((phase >> 2) + 1) & 1
        bottoms.append((mem[ROT_0_19M + other], mem[ROT_1_18M + other]))

    digits_of = [mem[DCENT_T + PLAYER_TYPE],
                 mem[DNUM_T + PLAYER_TYPE] >> 4,
                 mem[DNUM_T + PLAYER_TYPE] & 0x0F]
    digits = []
    for r in range(8):
        row = []
        for d in digits_of:
            row.append(mem[NUM_DATA + mem[NUM_DATA_OFFSET + d] + 3 * r])
        digits.append(row)

    return frames, bottoms, digits


def convert_row(c64_row):
    """3 C64 multicolour bytes -> (6 MODE 1 data bytes, 6 mask bytes).

    Each C64 byte is four 2-bit pixels; each becomes two MODE 1 pixels, so a
    C64 byte is two MODE 1 bytes. MODE 1 pixel n takes bit (7-n) as its high
    colour bit and bit (3-n) as its low bit; a transparent pixel sets both in
    the mask and neither in the data.
    """
    data, mask = [], []
    for byte in c64_row:
        pixels = [(byte >> 6) & 3, (byte >> 4) & 3, (byte >> 2) & 3, byte & 3]
        doubled = [p for p in pixels for _ in (0, 1)]        # 8 MODE 1 pixels
        for half in (doubled[:4], doubled[4:]):
            d = m = 0
            for n, pair in enumerate(half):
                logical = COLOUR[pair]
                if logical is None:
                    m |= (1 << (7 - n)) | (1 << (3 - n))
                else:
                    if logical & 2:
                        d |= 1 << (7 - n)
                    if logical & 1:
                        d |= 1 << (3 - n)
            data.append(d)
            mask.append(m)
    return data, mask


def main():
    mem, _ = parse_listing(LST_FILE)
    frames, bottoms, digits = build_c64_rows(mem)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / 'player.asm'
    with open(path, 'w') as f:
        f.write(BANNER.format(
            name='player.asm',
            desc='Droid 001, 8 ring phases + shared digit block, 24x21 MODE 1'))
        f.write('\n')
        f.write('PLY_W       = 6                 \\ 24 px = 6 MODE 1 bytes\n')
        f.write('PLY_H       = %d\n' % SPRITE_ROWS)
        f.write('PLY_ROWBYTES = 12               \\ 6 data then 6 mask\n')
        f.write('PLY_FRAMES  = %d\n' % FRAMES)
        f.write('PLY_RINGROWS = 5                \\ stored ring rows per frame\n')
        f.write('\n')

        f.write('\\ Ring rows 0-4 of each phase. Rows 15-19 reuse these in\n')
        f.write('\\ reverse: 15=4, 16=3, 17=2, 18=1b, 19=0b, where the b rows\n')
        f.write('\\ come from plyRingBot below.\n')
        f.write('.plyRing\n')
        for phase in range(FRAMES):
            f.write('  \\ phase %d\n' % phase)
            for row in frames[phase]:
                d, m = convert_row(row)
                emit_bytes(f, d + m)
        f.write('\n')

        f.write('\\ Rows 19 and 18: the same two tables as rows 0 and 1 but\n')
        f.write('\\ the other entry, so the two ends of the rotor alternate.\n')
        f.write('\\ Two rows per phase, row 19 first.\n')
        f.write('.plyRingBot\n')
        for phase in range(FRAMES):
            for mid in bottoms[phase]:
                d, m = convert_row([0, mid, 0])
                emit_bytes(f, d + m)
        f.write('\n')

        f.write('\\ Rows 6-13: the droid number, identical in every phase.\n')
        f.write('.plyDigits\n')
        for row in digits:
            d, m = convert_row(row)
            emit_bytes(f, d + m)
        f.write('\n')

        # --- lookup tables the blitter decodes ----------------------------
        f.write('\\ Rows 5, 14 and 20 are never written by the C64 either.\n')
        f.write('\\ Storing them as a real all-transparent row rather than a\n')
        f.write('\\ special case keeps the blit inner loop branchless.\n')
        f.write('.plyBlank\n')
        emit_bytes(f, [0] * 6 + [0xFF] * 6)
        f.write('\n')

        f.write('\\ Where each of the 21 sprite rows comes from:\n')
        f.write('\\   &00-&04  plyRing row n, of the current phase\n')
        f.write('\\   &20      plyBlank\n')
        f.write('\\   &40-&41  plyRingBot row n, of the current phase\n')
        f.write('\\   &80-&87  plyDigits row n\n')
        src = []
        for r in range(SPRITE_ROWS):
            if r < 5:
                src.append(r)
            elif r in (5, 14, 20):
                src.append(0x20)
            elif r < 14:
                src.append(0x80 | (r - 6))
            elif r < 18:
                src.append(19 - r)               # 15->4, 16->3, 17->2
            else:
                src.append(0x40 | (19 - r))      # 18->bot 1, 19->bot 0
        f.write('.plyRowSrc\n')
        emit_bytes(f, src, per_line=21)
        f.write('\n')

        f.write('\\ Per-phase base of each bank, so a row costs one add.\n')
        f.write('.plyRingLo\n')
        f.write('  ' + '\n  '.join(
            'EQUB LO(plyRing + %d)' % (p * 5 * 12) for p in range(FRAMES)) + '\n')
        f.write('.plyRingHi\n')
        f.write('  ' + '\n  '.join(
            'EQUB HI(plyRing + %d)' % (p * 5 * 12) for p in range(FRAMES)) + '\n')
        f.write('.plyBotLo\n')
        f.write('  ' + '\n  '.join(
            'EQUB LO(plyRingBot + %d)' % (p * 2 * 12) for p in range(FRAMES)) + '\n')
        f.write('.plyBotHi\n')
        f.write('  ' + '\n  '.join(
            'EQUB HI(plyRingBot + %d)' % (p * 2 * 12) for p in range(FRAMES)) + '\n')
        f.write('\n')
        f.write('\\ n * PLY_ROWBYTES, for n = 0-7.\n')
        f.write('.plyMulRow\n')
        emit_bytes(f, [12 * n for n in range(8)], per_line=8)
        f.write('\n')

    size = FRAMES * 5 * 12 + FRAMES * 2 * 12 + 8 * 12
    print('%s  (%d bytes of sprite data)' % (path, size))


if __name__ == '__main__':
    main()
