#!/usr/bin/env python3
"""
export_bbc.py - Convert Paradroid C64 data to BeebASM source for the BBC port.

Emits into src/data/:
  charset.asm   - the $7800 charset converted to BBC MODE 1 (256 chars, 16 bytes each)
  tiledefs.asm  - the 32 tile definitions from $E800 (4x4 char codes, byte-identical)
  levels.asm    - deck pointer table, per-deck metadata and RLE map data (byte-identical)

MODE 1 conversion
-----------------
C64 characters are 8x8, 1 bit per pixel, 8 bytes each.

BBC MODE 1 is 2 bits per pixel, 4 pixels per byte. Pixel n of a byte takes
bit (7-n) as its high colour bit and bit (3-n) as its low bit. Storing the
foreground as *logical colour 1* therefore sets only the low bit, and the
conversion collapses to a nibble split:

    left  4 pixels of scanline -> (b >> 4) & 0x0F
    right 4 pixels of scanline ->  b       & 0x0F

Using logical colour 1 (rather than baking in a colour) means each deck's
colour scheme is applied at runtime with VDU 19 / the palette registers,
exactly as the C64 recoloured via its CharColor table.

BBC screen memory groups 4 pixels x 8 scanlines into 8 consecutive bytes, so
a full 8x8 character occupies 16 contiguous bytes: the left half's 8 scanlines
followed by the right half's 8. Characters are stored here in that same order,
which makes plotting one a straight 16-byte copy to the screen.

Requires: Python 3. No third-party dependencies.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from rip_levels import parse_listing  # noqa: E402

PROJECT = Path(__file__).resolve().parent.parent
LST_FILE = PROJECT / 'paradroid_ce.lst'
OUT_DIR = PROJECT / 'src' / 'data'

CHARSET_ADDR = 0x7800
CHARSET_CHARS = 256

TILEDEF_ADDR = 0xE800
TILEDEF_COUNT = 32
TILEDEF_SIZE = 16

LVPTR_LO = 0xF100
LVPTR_HI = 0xF110
DECK_META = 0xF120          # 6 tables x 16 bytes: Y, X, height, width, colour, droids
DECK_META_LEN = 6 * 16
RLE_START = 0xF249
RLE_END = 0xFED0            # inclusive-exclusive; covers deck 15 plus terminator

BANNER = """\\ ============================================================
\\ {name}
\\ GENERATED by tools/export_bbc.py - do not edit by hand.
\\ Source: paradroid_ce.lst (Paradroid Redux, C64)
\\ {desc}
\\ ============================================================
"""


def emit_bytes(f, data, per_line=16):
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        f.write('  EQUB ' + ','.join('&%02X' % b for b in chunk) + '\n')


def convert_charset(mem):
    """C64 1bpp charset -> MODE 1, logical colour 1, 16 bytes per char."""
    out = bytearray()
    for c in range(CHARSET_CHARS):
        src = CHARSET_ADDR + c * 8
        rows = mem[src:src + 8]
        # left half: 8 scanlines, then right half: 8 scanlines
        out.extend(((b >> 4) & 0x0F) for b in rows)
        out.extend((b & 0x0F) for b in rows)
    return out


def main():
    if not LST_FILE.exists():
        sys.exit('ERROR: %s not found. See README.' % LST_FILE)

    print('Parsing %s ...' % LST_FILE.name)
    mem, filled = parse_listing(LST_FILE)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # ---- charset -------------------------------------------------------
    chars = convert_charset(mem)
    path = OUT_DIR / 'charset.asm'
    with open(path, 'w') as f:
        f.write(BANNER.format(
            name='charset.asm',
            desc='%d chars x 16 bytes, MODE 1, foreground = logical colour 1'
                 % CHARSET_CHARS))
        f.write('\nALIGN &100\n.charset\n')
        emit_bytes(f, chars)
        f.write('.charset_end\n')
    print('  charset.asm   %5d bytes (%d chars)' % (len(chars), CHARSET_CHARS))

    # ---- tile definitions ----------------------------------------------
    tiles = mem[TILEDEF_ADDR:TILEDEF_ADDR + TILEDEF_COUNT * TILEDEF_SIZE]
    path = OUT_DIR / 'tiledefs.asm'
    with open(path, 'w') as f:
        f.write(BANNER.format(
            name='tiledefs.asm',
            desc='%d tiles x 4x4 character codes - byte-identical to the C64'
                 % TILEDEF_COUNT))
        f.write('\nALIGN &100\n.tiledefs\n')
        emit_bytes(f, tiles)
        f.write('.tiledefs_end\n')
    print('  tiledefs.asm  %5d bytes (%d tiles)' % (len(tiles), TILEDEF_COUNT))

    # ---- levels ---------------------------------------------------------
    ptr_lo = mem[LVPTR_LO:LVPTR_LO + 16]
    ptr_hi = mem[LVPTR_HI:LVPTR_HI + 16]
    meta = mem[DECK_META:DECK_META + DECK_META_LEN]
    rle = mem[RLE_START:RLE_END]

    # C64 pointers are absolute into $F249+. Re-base them to an offset from
    # the start of the RLE block so the BBC build can place it anywhere.
    offs = [(((ptr_hi[i] << 8) | ptr_lo[i]) - RLE_START) for i in range(16)]
    if any(o < 0 or o >= len(rle) for o in offs):
        sys.exit('ERROR: deck pointer outside the RLE block: %r' % offs)

    path = OUT_DIR / 'levels.asm'
    with open(path, 'w') as f:
        f.write(BANNER.format(
            name='levels.asm',
            desc='16 deck maps, RLE encoded - byte-identical to the C64'))
        f.write('\n\\ Per-deck offsets into leveldata (re-based from C64 $F249)\n')
        f.write('.deckOffsetLo\n')
        emit_bytes(f, [o & 0xFF for o in offs])
        f.write('.deckOffsetHi\n')
        emit_bytes(f, [(o >> 8) & 0xFF for o in offs])
        for n, label in enumerate(['deckY', 'deckX', 'deckHeight',
                                   'deckWidth', 'deckColour', 'deckDroids']):
            f.write('.%s\n' % label)
            emit_bytes(f, meta[n * 16:(n + 1) * 16])
        f.write('\n.leveldata\n')
        emit_bytes(f, rle)
        f.write('.leveldata_end\n')
    print('  levels.asm    %5d bytes RLE + %d bytes metadata'
          % (len(rle), len(meta) + 32))

    print('\nWrote to %s' % OUT_DIR)


if __name__ == '__main__':
    main()
