#!/usr/bin/env python3
"""
export_strings.py - Convert the C64 string table at $C000 to glyph indices.

Emits src/data/strings.asm.

WHAT THE TABLE IS
-----------------
$C000 holds a count (249) and $C001 upward holds 1,541 bytes of text in
which THE FIRST CHARACTER OF EACH STRING HAS BIT 7 SET. That is the whole
format -- there is no length byte and no terminator. FindStrings ($2BCA)
walks it once at startup building Strings_lo/hi:

    LDX #1 : LDY #$C0 : STX src : STY src+1     ; src = $C001
    LDX #0
    _1: LDA (src),Y : BMI _3                    ; found a bit-7 byte
        src += 1 : JMP _1
    _3: STA Strings_lo,X ... src += 1 : INX
        CPX String_dat : BCC _1                 ; 249 of them

so string N starts at the Nth bit-7 byte, counting from zero, and runs to
just before the next one.

WHAT IS IN IT
-------------
Everything the console and the transfer game name:

    token 50        the dash and a space, the "Unit type 001 - ..." separator
    tokens 10-16    robot, droid, cyborg, ... the droid class words
    token 55        device
    tokens 105+     the eight ship names, indexed by (shipLevel-1) AND 7
    tokens 122+     the sixteen deck names, indexed by deckNum
    tokens 208+     green, yellow, amber, red -- the four alert levels

ShowRobotType ($3149) builds a droid name from three of them: token 50,
then the droid's hundreds digit as a token, then ((cent-1) >> 2) + 10.
That gives 001 Influence device, 123 Disposal robot, 999 Command cyborg
and the rest.

WHY IT IS TRANSLATED HERE AND NOT AT RUN TIME
---------------------------------------------
The C64 codes are the $7000 charset's, and the port indexes its font
contiguously instead -- see export_font.py. Mapping at export time makes
the 6502 printer a straight glyph-index copy with no code arithmetic, and
costs nothing: the table is the same size either way. BIT 7 IS PRESERVED,
so the "first character of a string" marker survives the translation.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'strings.asm'

# THE SAME BYTES AGAIN, FOR BANK 7. The droid database reads the table
# too, and it is in bank 7 while the console that owns this copy is in
# bank 6 -- only one bank is visible at a time, so the table has to exist
# twice. Emitting both from here is what stops the two drifting apart:
# they are the same list, written out under two labels.
OUT7 = PROJECT / 'src' / 'data' / 'strings7.asm'

TABLE = 0xC000

# C64 code -> port glyph index. The alphabet is arithmetic; everything
# else is here because the C64 put it out of line. See export_font.py.
PN_SPACE, PN_DIGIT0, PN_UPPER_A, PN_LOWER_A = 0, 1, 11, 63
PN_DOT, PN_DASH, PN_COLON, PN_BANG = 89, 98, 99, 102
PN_UPPER_I = PN_UPPER_A + 8
PN_LOWER_M = PN_LOWER_A + 12
PN_LOWER_W = PN_LOWER_A + 22

SPECIAL = {
    0x16: PN_UPPER_I,       # capital I, in lowercase m's alphabet slot
    0x42: PN_LOWER_M,       # lowercase m, in capital I's alphabet slot
    0x54: PN_LOWER_W,       # lowercase w, just past Z
    0x25: PN_BANG,
    0x28: PN_DOT,
    0x2A: PN_COLON,
    0x2E: PN_DASH,
    0x30: PN_SPACE,
}


def to_glyph(code):
    if code in SPECIAL:
        return SPECIAL[code]
    if code <= 0x09:
        return PN_DIGIT0 + code
    if 0x0A <= code <= 0x23:
        return PN_LOWER_A + (code - 0x0A)
    if 0x3A <= code <= 0x53:
        return PN_UPPER_A + (code - 0x3A)
    raise KeyError('no glyph for C64 code $%02X' % code)


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def main():
    mem = load_memory()
    count = mem[TABLE]

    # Walk to the end of the last string, so the blob is exactly the table.
    addr, found = TABLE + 1, 0
    while found < count - 1:
        if mem[addr] & 0x80:
            found += 1
        addr += 1
    while not (mem[addr] & 0x80):
        addr += 1
    end = addr

    raw = [mem[a] for a in range(TABLE + 1, end)]
    data = [(b & 0x80) | to_glyph(b & 0x7F) for b in raw]
    nstrings = sum(1 for b in raw if b & 0x80)
    # A SENTINEL, which the C64 does not have and does not need: its own
    # printer stops on the next string's bit-7 byte, and the last string
    # in the table is one it never prints. Ours would run off the end, so
    # one more bit-7 byte terminates it for free and the reader needs no
    # bounds check at all.
    data.append(0x80 | PN_SPACE)

    out = []
    out.append('\\ ============================================================')
    out.append('\\ strings.asm - GENERATED by tools/export_strings.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The C64 string table at $C000, translated to port glyph indices.')
    out.append('\\')
    out.append('\\ THE FIRST CHARACTER OF EACH STRING HAS BIT 7 SET. There is no')
    out.append('\\ length byte and no terminator: string N starts at the Nth bit-7')
    out.append('\\ byte counting from zero and runs to just before the next. That is')
    out.append('\\ FindStrings\' own format ($2BCA), kept because it costs nothing and')
    out.append('\\ the index it builds -- 249 pointers, 498 bytes -- does not.')
    out.append('\\')
    out.append('\\ Codes are OUR glyph indices, not the C64\'s charset codes, so the')
    out.append('\\ 6502 printer is a straight copy with no code arithmetic. Bit 7')
    out.append('\\ survives the translation.')
    out.append('')
    out.append('\ GEN_STR_BYTES includes the trailing sentinel; GEN_STR_COUNT does not.')
    out.append('GEN_STR_COUNT = %d' % nstrings)
    out.append('GEN_STR_BYTES = %d' % len(data))
    out.append('')
    out.append('.constrings')
    for i in range(0, len(data), 16):
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in data[i:i + 16]))
    out.append('.constrings_end')
    out.append('ASSERT constrings_end - constrings == GEN_STR_BYTES')
    out.append('ASSERT GEN_STR_COUNT == CON_STR_COUNT')
    out.append('ASSERT GEN_STR_BYTES == CON_STR_BYTES')
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote %s  (%d strings, %d bytes)' % (OUT, nstrings, len(data)))

    out7 = []
    out7.append('\\ ============================================================')
    out7.append('\\ strings7.asm - GENERATED by tools/export_strings.py, do not edit')
    out7.append('\\ ============================================================')
    out7.append('\\ THE SAME TABLE AS strings.asm, under a second label, for BANK 7.')
    out7.append('\\ The droid database prints from it and lives in bank 7; the')
    out7.append('\\ console main screen prints from it and lives in bank 6. Only one')
    out7.append('\\ bank is visible at a time, so the 1,542 bytes exist twice. Both')
    out7.append('\\ copies come out of this one tool, so they cannot drift.')
    out7.append('')
    out7.append('.constrings7')
    for i in range(0, len(data), 16):
        out7.append('  EQUB ' + ', '.join('&%02X' % b for b in data[i:i + 16]))
    out7.append('.constrings7_end')
    out7.append('ASSERT constrings7_end - constrings7 == GEN_STR_BYTES')
    out7.append('')
    OUT7.write_text('\n'.join(out7) + '\n')
    print('wrote %s  (the bank 7 copy)' % OUT7)

    # Report what the console will actually print, as a check on the indices.
    starts = [i for i, b in enumerate(raw) if b & 0x80]

    def text(n):
        s = starts[n]
        e = starts[n + 1] if n + 1 < len(starts) else len(raw)
        return ''.join(chr(97 + (c & 0x7F) - 0x0A) if 0x0A <= (c & 0x7F) <= 0x23
                       else {0x30: ' ', 0x28: '.', 0x2A: ':', 0x2E: '-', 0x25: '!',
                             0x16: 'I', 0x42: 'm', 0x54: 'w'}.get(c & 0x7F,
                             chr(65 + (c & 0x7F) - 0x3A) if 0x3A <= (c & 0x7F) <= 0x53
                             else str(c & 0x7F))
                       for c in raw[s:e])

    print('\n  token 50 (separator) = %r' % text(50))
    print('  ship names 105+ :', [text(105 + i) for i in range(8)])
    print('  alert names 208+:', [text(208 + i) for i in range(4)])
    print('  deck names 122+ :', [text(122 + i) for i in range(16)])


if __name__ == '__main__':
    main()
