#!/usr/bin/env python3
"""
export_portraits.py - the droid portrait pool, from the C64 sprite images
BuildIntroSprites ($3629) composes.

Emits src/data/portraits.asm, for SWRAM bank 7.

WHAT THE PORTRAIT IS
--------------------
A 48 x 84 picture per droid type, composed from EIGHT 24 x 21 hardware
sprites in a 2 x 4 grid. Only the LEFT column is stored: record bytes
0/2/4/6 of DroidInfo_dat ($EB00) name the left image of each row-pair,
and bytes 1/3/5/7 name an explicit right image or, when zero, tell
MirrorSprite ($3AE8) to build the mirror of the left at runtime. Image
N means $4000 + N*64.

Byte 63 of every image carries its metadata, exactly as the C64 reads
it at $3670: bit 7 set = multicolour (2bpp pairs, drawn double-wide),
clear = hires (1bpp); bits 0-4 = rptLen, the number of scanlines the
NEXT row-pair starts below this one (pairs overlap when it is < 21,
and the upper pair wins - VIC sprite priority - so a renderer drawing
opaquely must compose bottom-up).

WHAT IS EMITTED
---------------
  poIdx   24 x 8 bytes - the records' bytes 0-7 translated to pool
          slots: even positions the left image's slot, odd positions
          $FF for "mirror the left" (the C64's zero) or the explicit
          right image's slot.
  poPool  the unique images, 64 bytes each, verbatim C64 data, sorted
          by C64 image number. Slot order is the sort order.
  poLutL/poLutR
          multicolour byte -> left/right MODE 1 byte. One mc byte is
          four 2-bit pixels drawn double-wide: the left MODE 1 byte
          shows pixels 0,0,1,1 and the right 2,2,3,3, each 2-bit value
          v landing as logical colour v (MODE 1 pixel n takes bit 7-n
          high and 3-n low). Hires bytes need no table: logical 2 is
          high-bit-only, so left = b AND $F0 and right = b << 4.

Colour fidelity (SpriteColor_t/SpriteMc_t via DColorTheme_t) is NOT
exported: the console page has one 4-colour palette and the mapping
v -> logical v is the whole scheme. Per-type palettes are Layer 14's.
"""

import importlib.util
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'portraits.asm'

TABLE = 0xEB00
TYPES = 24
STRIDE = 64
IMG_BASE = 0x4000
IMG_SIZE = 64


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def mc_expand(b):
    """One multicolour byte -> (left, right) MODE 1 bytes, pixels doubled."""
    v = [(b >> s) & 3 for s in (6, 4, 2, 0)]

    def pack(a, c):
        hi = ((a >> 1) * 0b1100) | ((c >> 1) * 0b0011)
        lo = ((a & 1) * 0b1100) | ((c & 1) * 0b0011)
        return (hi << 4) | lo
    return pack(v[0], v[1]), pack(v[2], v[3])


def rows_of(vals, per=16):
    for i in range(0, len(vals), per):
        yield ', '.join('&%02X' % v for v in vals[i:i + per])


def main():
    mem = load_memory()

    recs = []
    for t in range(TYPES):
        base = TABLE + t * STRIDE
        recs.append([mem[base + i] for i in range(8)])

    imgs = sorted({b for r in recs for b in r if b})
    slot = {n: i for i, n in enumerate(imgs)}

    out = []
    out.append('\\ ============================================================')
    out.append('\\ portraits.asm - GENERATED by tools/export_portraits.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The droid portrait pool: %d unique C64 sprite images, verbatim,' % len(imgs))
    out.append('\\ and the per-type composition index. Read the tool header.')
    out.append('')
    out.append('PO_IMAGES = %d' % len(imgs))
    out.append('PO_MIRROR = &FF')
    out.append('')
    out.append('\\ 24 types x 8: even bytes the left image slot, odd bytes the right')
    out.append('\\ (PO_MIRROR = mirror the left, the C64\'s record byte 0).')
    out.append('.poIdx')
    for t, r in enumerate(recs):
        row = []
        for i in range(8):
            if i % 2 == 0:
                row.append(slot[r[i]])
            else:
                row.append(slot[r[i]] if r[i] else 0xFF)
        out.append('  EQUB ' + ', '.join('&%02X' % v for v in row) +
                   '   \\ type %d' % t)
    out.append('')
    out.append('\\ The images, 64 bytes each: 21 rows x 3 bytes, then byte 63 =')
    out.append('\\ MC flag (bit 7) OR rptLen (bits 0-4).')
    out.append('.poPool')
    for n in imgs:
        d = [mem[IMG_BASE + n * IMG_SIZE + i] for i in range(IMG_SIZE)]
        meta = d[63]
        out.append('\\ slot %d = C64 image &%02X - %s, rptLen %d' %
                   (slot[n], n, 'MC' if meta & 0x80 else 'hires', meta & 0x1F))
        for row in rows_of(d):
            out.append('  EQUB ' + row)
    out.append('')
    out.append('\\ Multicolour byte -> MODE 1, left half (pixels 0,0,1,1).')
    out.append('.poLutL')
    for row in rows_of([mc_expand(b)[0] for b in range(256)]):
        out.append('  EQUB ' + row)
    out.append('\\ ... and the right half (pixels 2,2,3,3).')
    out.append('.poLutR')
    for row in rows_of([mc_expand(b)[1] for b in range(256)]):
        out.append('  EQUB ' + row)
    out.append('')

    OUT.write_text('\n'.join(out) + '\n')
    total = len(imgs) * IMG_SIZE + TYPES * 8 + 512
    print('wrote %s: %d images, %d bytes of data' % (OUT, len(imgs), total))
    hires = [n for n in imgs if not (mem[IMG_BASE + n * IMG_SIZE + 63] & 0x80)]
    print('hires images: %s' % (', '.join('&%02X' % n for n in hires) or 'none'))


if __name__ == '__main__':
    main()
