#!/usr/bin/env python3
"""
export_icons.py - The console's menu icons, C64 sprites to MODE 1.

Emits src/data/conicons.asm.

WHERE THEY COME FROM
--------------------
conRedraw ($2C25) draws the menu by walking a table of 11-byte sprite
records at $6B89 until it has written the one for sprite 7:

    6B94: 01 34 00 90 FF 00 00 00 00 FF 4F
    6B9F: 02 34 00 AC FF 00 00 00 00 FF 50
    6BAA: 03 28 00 C8 FF 00 00 00 FF FF A1
    6BB5: 04 28 00 E0 FF 00 00 00 FF FF A2

so FOUR visible icons -- sprites 1 to 4, sprites 0 and 5 to 7 being all
zero. Byte 1 is the sprite X, byte 3 the Y and byte 10 the VIC image
pointer; the sprite data is at $4000 + ptr * 64, 24 x 21 pixels in 63
bytes, three bytes a row.

    ptr $4F -> $53C0   BLANK IN ROM. This is where BuildDroidSprite
                       composes the player's own droid at run time, which
                       is why conRedraw sets dType from droidType first.
                       Not exported -- see conicons.asm's header.
    ptr $50 -> $5400   the droid-number emblem
    ptr $A1 -> $6840   a circular ship-plan badge
    ptr $A2 -> $6880   a ship side view

ALL FOUR ARE HIRES -- SpriteMC is 0 in every record -- BUT SPRITES 3 AND
4 ARE X-EXPANDED. The 11 bytes map onto SpriteNum ($04) through
SpriteImage ($0E), so byte 8 is SpriteXExp, and it is $FF for the ship
plan and the side view and 0 for the other two. They are 48 pixels wide
on screen, not 24. SpriteYExp is 0 throughout, so all four stay 21
scanlines. The widening is baked into the data here: the BBC has no
equivalent register.

THE MODE 1 LAYOUT, AND WHY EACH ICON IS THREE FLAT COPIES
---------------------------------------------------------
Consecutive 4-pixel columns in the play buffer are EIGHT bytes apart, and
a column's eight bytes are eight consecutive scanlines -- so the six
columns of a 24 px sprite occupy 48 CONSECUTIVE bytes within one
character row. 21 scanlines is three character rows (the last three
scanlines blank), so an icon is three 48-byte copies at base, base + 640
and base + 1280. No shifting, no masking, no per-row arithmetic.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'conicons.asm'

VIC_BANK = 0x4000
# name, image pointer, X-expanded
ICONS = [
    ('droid ? emblem', 0x50, False),
    ('ship plan badge', 0xA1, True),
    ('ship side view', 0xA2, True),
]
SPR_W, SPR_H = 24, 21
ROWS = 3                        # character rows an icon spans
UNITS = SPR_W // 4              # 4-pixel columns, unexpanded


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def pixels(mem, ptr):
    """24 x 21 booleans from a hires C64 sprite."""
    base = VIC_BANK + ptr * 64
    out = []
    for y in range(SPR_H):
        row = []
        for i in range(3):
            b = mem[base + y * 3 + i]
            for bit in range(8):
                row.append(bool(b & (0x80 >> bit)))
        out.append(row)
    return out


def to_mode1(px, expand):
    """Character row major, then 4-pixel column, then scanline: the order
    the buffer itself is in, so drawing is a straight copy.

    THE X-EXPANDED ONES ARE STORED NARROW and doubled by ConIcons as it
    draws, from a 16-entry nibble table. Baking the widening in costs 288
    bytes and bank 6 does not have them; doubling four pixels to eight is
    two table lookups, and the icons are drawn once."""
    data = []
    for crow in range(ROWS):
        for unit in range(UNITS):
            for sl in range(8):
                y = crow * 8 + sl
                b = 0
                for n in range(4):
                    x = unit * 4 + n
                    if y < SPR_H and px[y][x]:
                        b |= (0x80 >> n) | (0x08 >> n)   # logical colour 3
                data.append(b)
    return data


def main():
    mem = load_memory()
    out = []
    out.append('\\ ============================================================')
    out.append('\\ conicons.asm - GENERATED by tools/export_icons.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The console menu icons, C64 sprites 2, 3 and 4 of conRedraw\'s')
    out.append('\\ table at $6B94, converted to MODE 1.')
    out.append('\\')
    out.append('\\ SPRITE 1 IS NOT HERE. Its image pointer is $4F, and $53C0 is blank')
    out.append('\\ in ROM: that is where BuildDroidSprite composes the PLAYER\'S OWN')
    out.append('\\ droid at run time, which is why conRedraw sets dType from droidType')
    out.append('\\ before it draws. Ours is drawn from the sprite bank instead.')
    out.append('\\')
    out.append('\\ Each icon is 24 x 21 px = THREE character rows of six 4-pixel')
    out.append('\\ columns. Consecutive columns are eight bytes apart and a column is')
    out.append('\\ eight consecutive scanlines, so the six columns of one row are 48')
    out.append('\\ CONSECUTIVE bytes in the buffer -- an icon is three flat 48-byte')
    out.append('\\ copies at base, base + 640 and base + 1280.')
    out.append('')
    out.append('GEN_ICON_COUNT = %d' % len(ICONS))
    out.append('GEN_ICON_ROWS  = %d' % ROWS)
    out.append('')

    body, labels, total = [], [], 0
    for name, ptr, expand in ICONS:
        data = to_mode1(pixels(mem, ptr), expand)
        assert len(data) == ROWS * UNITS * 8
        body.append('  \\ %s  (pointer $%02X at $%04X%s)'
                    % (name, ptr, VIC_BANK + ptr * 64,
                       ', X-EXPANDED at draw time' if expand else ''))
        for i in range(0, len(data), 16):
            body.append('  EQUB ' + ', '.join('&%02X' % b for b in data[i:i + 16]))
        labels.append((name, total, len(data), expand))
        total += len(data)

    out.append('.conicons')
    out.extend(body)
    out.append('.conicons_end')
    out.append('ASSERT conicons_end - conicons == %d' % total)
    out.append('ASSERT GEN_ICON_COUNT == CON_ICON_COUNT')
    out.append('')
    out.append('\\ All three are stored 24 px wide. CON_ICON_EXP is a bit per icon')
    out.append('\\ saying which the VIC draws X-expanded; ConIcons doubles those as')
    out.append('\\ it copies, from a 16-entry nibble table.')
    for i, (name, off, size, expand) in enumerate(labels):
        out.append('CON_ICON%d_OFS = %-5d \\ %-18s%s'
                   % (i, off, name, '  X-EXPANDED' if expand else ''))
    out.append('CON_ICON_EXP  = %%%s' % ''.join(
        '1' if l[3] else '0' for l in reversed(labels)))
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote %s  (%d icons, %d bytes)' % (OUT, len(ICONS), total))
    for name, off, size, expand in labels:
        print('   %-18s offset %4d, %3d bytes%s'
              % (name, off, size, '  (doubled at draw time)' if expand else ''))


if __name__ == '__main__':
    main()
