#!/usr/bin/env python3
"""
export_droidinfo.py - the droid database's per-type records, from $EB00.

Emits src/data/droidinfo.asm, for SWRAM bank 7.

WHAT THE TABLE IS
-----------------
DroidInfo_dat lives at $EB00 and is 24 records of 64 bytes, one per droid
type, $EB00-$F0FF. BuildIntroSprites ($3629) computes its address as
dType * 64 + $EB00 and leaves it in droidInfoData, which is then the base
for everything con_DroidInfo prints.

    bytes 0-7    the four intro sprite images and their mirror flags
    byte 8       height, as two BCD nibbles: Height_txt draws "1.HL m"
    byte 9       weight, a plain byte: Weight_txt draws it as three digits
    bytes 10-15  drive, brain, armament, sensor 1, sensor 2, sensor 3 --
                 each a token index into the $C000 string table
    $10 onwards  the description, a list of token indices ending $FF, with
                 $FE marking a sentence break

PrintDroidInfo ($2F57) reads bytes 8-15 through a counter that runs 13-22,
subtracting 7 to index the record; sub_0_2DCD ($2DCD) walks the
description from $10 to at most $37.

BYTES 0-7 ARE NOT EXPORTED. They are C64 sprite image numbers for the
48x84 multicolour portrait the browser page draws, and the port has no
portrait: its droid artwork is compiled into the sprite banks and the
console draws the same runtime-composed rotor-and-digits image the C64
builds at $53C0 (docs/layer-9-hud.md, decision 16). Dropping them takes
the record from 64 bytes to 8 plus a variable-length description, which
is 1,536 bytes down to about 700 -- and bank 7 pays for all of it.

THE DESCRIPTIONS ARE PACKED AND POINTED AT rather than kept on the
original's 64-byte stride: they run from 8 to 35 bytes, so the stride
would waste a third of the space to save a table lookup that happens once
per page.

NOTHING IS TRANSLATED. Every byte here is either a number or an index
into the string table, and export_strings.py has already translated that
table's text to port glyph indices.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'droidinfo.asm'

TABLE = 0xEB00
TYPES = 24
STRIDE = 64
STATS = 8                       # record bytes 8-15
DESC_START = 0x10
DESC_END = 0x38                 # sub_0_2DCD's own bound: index < $38
DESC_BREAK = 0xFE
DESC_TERM = 0xFF


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def main():
    mem = load_memory()

    stats, descs = [], []
    for t in range(TYPES):
        base = TABLE + t * STRIDE
        stats.append([mem[base + 8 + i] for i in range(STATS)])

        d = []
        for i in range(DESC_START, DESC_END):
            b = mem[base + i]
            d.append(b)
            if b == DESC_TERM:
                break
        else:
            # The C64 stops at $38 whether or not it has seen $FF, and
            # prints the closing full stop either way; give the reader the
            # terminator explicitly so it needs no bounds check.
            d.append(DESC_TERM)
        descs.append(d)

    total = sum(len(d) for d in descs)

    out = []
    out.append('\\ ============================================================')
    out.append('\\ droidinfo.asm - GENERATED by tools/export_droidinfo.py')
    out.append('\\ ============================================================')
    out.append('\\ DroidInfo_dat ($EB00), 24 records of 64 bytes, one per droid')
    out.append('\\ type. See the tool for the layout; in short:')
    out.append('\\')
    out.append('\\   dbiStats   8 bytes a type - the original\'s record bytes 8-15:')
    out.append('\\              height (two BCD nibbles), weight, then the token')
    out.append('\\              indices for drive, brain, armament and three sensors')
    out.append('\\   dbiDesc    the description, a token list ending $FF, with $FE')
    out.append('\\              a sentence break. Packed and pointed at, because the')
    out.append('\\              lengths run 8 to 35 against a 40-byte stride')
    out.append('\\')
    out.append('\\ THE INTRO SPRITE IMAGES (record bytes 0-7) ARE NOT HERE. They')
    out.append('\\ are the C64\'s 48x84 portrait, which the port does not have and')
    out.append('\\ cannot build - see docs/layer-9-hud.md.')
    out.append('')
    out.append('GEN_DBI_TYPES = %d' % TYPES)
    out.append('GEN_DBI_STATS = %d' % STATS)
    out.append('')
    out.append('\\ height, weight, drive, brain, armament, sensor 1, 2, 3')
    out.append('.dbiStats')
    for t, s in enumerate(stats):
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in s) + '  \\ %d' % t)
    out.append('')
    out.append('.dbiDescLo')
    for i in range(0, TYPES, 8):
        out.append('  EQUB ' + ', '.join('LO(dbiDesc%d)' % t for t in range(i, i + 8)))
    out.append('.dbiDescHi')
    for i in range(0, TYPES, 8):
        out.append('  EQUB ' + ', '.join('HI(dbiDesc%d)' % t for t in range(i, i + 8)))
    out.append('')
    out.append('.dbiDesc')
    for t, d in enumerate(descs):
        out.append('.dbiDesc%d' % t)
        for i in range(0, len(d), 12):
            out.append('  EQUB ' + ', '.join('&%02X' % b for b in d[i:i + 12]))
    out.append('.dbiDesc_end')
    out.append('')
    out.append('ASSERT dbiDescLo - dbiStats == GEN_DBI_TYPES * GEN_DBI_STATS')
    out.append('ASSERT dbiDesc_end - dbiDesc == %d' % total)
    out.append('ASSERT GEN_DBI_TYPES == DB_TYPES')
    out.append('ASSERT GEN_DBI_STATS == DB_STATS')
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote %s  (%d stat bytes, %d description bytes, %d total)'
          % (OUT, TYPES * STATS, total, TYPES * STATS + total + 2 * TYPES))

    # A readable dump, as a check on the indices.
    lens = [len(d) for d in descs]
    print('  descriptions: shortest %d, longest %d' % (min(lens), max(lens)))
    for t in range(TYPES):
        h, w = stats[t][0], stats[t][1]
        print('  %2d  1.%02X m  %3d  tokens %s  desc %d' %
              (t, h, w, ' '.join('%3d' % b for b in stats[t][2:]), len(descs[t])))


if __name__ == '__main__':
    main()
