#!/usr/bin/env python3
"""
export_xfer.py - the transfer minigame's board, converted to BBC MODE 1.

Emits src/data/xferboard.asm.

WHAT THE BOARD IS
-----------------
SubGameSelectSide ($E016) writes three rows from SubGameTopLines_dat
($E613), then ONE row from SubGameLine_dat ($E68B) twelve times, then one
from SubGameBottomLine_dat ($E6B3). So the data is only 200 bytes and the
twelve middle rows are identical - each is a wire running from the
player's vertical bus at column 3, right along columns 4-17 into the
central result bar at 19-20, and the mirror of that from the CPU's bus at
column 36.

Fifteen distinct character codes are used (plus 0 for blank), all from the
$7800 charset the deck tiles come from. They are exported here as their
own small MODE 1 set rather than going through BuildCharset, because
unlike the tiles they are NOT deck-coloured - and because extending the
137-character remap pushes the charset at &0400 into the MOS's NMI area
at &0D00.

THE ROWS ARE RAW C64 CODES, NOT GLYPH INDICES
---------------------------------------------
The game logic is a transliteration of xfer_DoColumn and friends, which
dispatch on the character IN the cell - CMP #$F5, CMP #$F6, CMP #$F7,
CMP xfer_CpuPulserChar. Keeping the shadow screen in the original's own
codes keeps every one of those comparisons verbatim, so the rows here are
the C64 bytes and xbCode is the 16-entry code list the renderer expands
into a 256-byte code->glyph table at init.

THREE VARIANTS PER CHARACTER - route A of layer-10-transfer.md section 5
------------------------------------------------------------------------
The C64 shows ownership in colour RAM, per cell, which MODE 1 has none
of. Every pixel the game recolours is a multicolour 11 pair - logical 3
here - so ownership becomes a character-set choice: the NEUTRAL set keeps
logical 3, the PLAYER set rewrites every 3 to 1, the CPU set to 2.
Pixels that are not 3 (the counter frame's 01/10 pairs) are untouched, so
the three sets differ only where ownership shows.

MODE 1 conversion is export_bbc.py's, unchanged: each C64 pixel becomes
two MODE 1 pixels, the left byte of a scanline carries C64 pixels 0,0,1,1
and the right byte 2,2,3,3, and a character is 16 bytes - the left half's
8 scanlines then the right half's.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'xferboard.asm'

CHARSET = 0x7800
TOP = 0xE613          # 3 rows of 40
MIDDLE = 0xE68B       # 1 row of 40, repeated
BOTTOM = 0xE6B3       # 1 row of 40
COLS = 40


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def mode1_char(mem, code, remap3):
    """One C64 multicolour character -> 16 MODE 1 bytes, left then right.

    Pair 11 is the OWNERSHIP plane (C64 colour RAM) and becomes remap3.
    Pairs 01 and 10 are STRUCTURE - the C64 draws them in the fixed
    $D022/$D023 registers, the same whoever owns the cell - so they
    render neutral (logical 3) in every set. Mapping them onto logical
    1/2 was tried first and made the buses read as owned."""
    left, right = [], []
    for row in range(8):
        b = mem[CHARSET + code * 8 + row]
        pairs = [(b >> 6) & 3, (b >> 4) & 3, (b >> 2) & 3, b & 3]
        for half, src in ((left, pairs[0:2]), (right, pairs[2:4])):
            byte = 0
            for n, p in enumerate((src[0], src[0], src[1], src[1])):
                if p == 0:
                    c = 0
                elif p == 3:
                    c = remap3
                else:
                    c = 3
                if c & 2:
                    byte |= 0x80 >> n
                if c & 1:
                    byte |= 0x08 >> n
            half.append(byte)
    return left + right


def main():
    mem = load_memory()
    top = [mem[TOP + i] for i in range(3 * COLS)]
    mid = [mem[MIDDLE + i] for i in range(COLS)]
    bot = [mem[BOTTOM + i] for i in range(COLS)]

    # $F4 never appears in the board data - xfer_PutSwitcher ($E276) writes
    # it at runtime - so it is added by hand or the renderer would have no
    # glyph for it.
    codes = sorted(set(top + mid + bot) | {0xF4})
    assert codes[0] == 0, 'expected blank to be code 0'

    out = []
    out.append('\\ ============================================================')
    out.append('\\ xferboard.asm - GENERATED by tools/export_xfer.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The transfer minigame board: SubGameTopLines_dat ($E613), three')
    out.append('\\ rows; SubGameLine_dat ($E68B), ONE row the original repeats twelve')
    out.append('\\ times; SubGameBottomLine_dat ($E6B3), one row. 200 bytes, and the')
    out.append('\\ repeat is why.')
    out.append('\\')
    out.append('\\ Rows are RAW C64 CODES - the game logic dispatches on the byte in')
    out.append('\\ the cell, so the shadow screen keeps the original\'s values and the')
    out.append('\\ renderer owns the code->glyph mapping. Three glyph sets: neutral')
    out.append('\\ (logical 3), player (3 rewritten to 1), CPU (3 rewritten to 2) -')
    out.append('\\ ownership as a character-set choice, route A of')
    out.append('\\ docs/layer-10-transfer.md section 5.')
    out.append('')
    out.append('XB_CHARS = %d' % len(codes))
    out.append('XB_COLS  = %d' % COLS)
    out.append('')

    out.append('\\ The %d C64 codes that occur, in xbChars order. XfInit expands' % len(codes))
    out.append('\\ this into the 256-byte code->glyph-index table at xsGlyphOf.')
    out.append('.xbCode')
    out.append('  EQUB ' + ', '.join('&%02X' % c for c in codes))
    out.append('')

    for name, remap3, label in (('xbChars', 3, 'NEUTRAL: multicolour 11 stays logical 3'),
                                ('xbCharsPly', 1, 'PLAYER: 11 pairs become logical 1'),
                                ('xbCharsCpu', 2, 'CPU: 11 pairs become logical 2')):
        out.append('\\ %s. 16 bytes each: left half\'s 8 scanlines then right\'s.' % label)
        out.append('.%s' % name)
        for c in codes:
            data = mode1_char(mem, c, remap3)
            out.append('  \\ code &%02X' % c)
            out.append('  EQUB ' + ', '.join('&%02X' % b for b in data))
        out.append('.%s_end' % name)
        out.append('ASSERT %s_end - %s == XB_CHARS * 16' % (name, name))
        out.append('')

    def rows(name, data, n):
        out.append('.%s' % name)
        for r in range(n):
            out.append('  EQUB ' + ', '.join('&%02X' % b for b in data[r*COLS:(r+1)*COLS]))

    out.append('\\ Rows as RAW C64 CODES - see the header.')
    rows('xbTop', top, 3)
    out.append('')
    rows('xbMid', mid, 1)
    out.append('')
    rows('xbBottom', bot, 1)
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    total = len(codes) * 16 * 3 + 5 * COLS + len(codes)
    print(f'wrote {OUT}')
    print(f'  {len(codes)} characters x 3 sets, {len(codes)*48} B; board 5 rows, {5*COLS} B; total {total} B')
    print('  codes: ' + ' '.join('$%02X' % c for c in codes))


if __name__ == '__main__':
    main()
