#!/usr/bin/env python3
"""
export_droidicon.py - the console's droid icon, as data rather than code.

Emits src/data/droidicon.asm.

WHY THIS EXISTS AT ALL
----------------------
conRedraw ($2C25) draws four menu sprites, and the first one's image
pointer is $4F -> $53C0, which is BLANK in ROM. $5200-$53FF is the C64's
dynamic sprite area: BuildDroidSprite ($3C77) writes the three-digit
number into rows 6-13 and AnimateDroids ($3CFB) the spinning rotor into
rows 0-4 and 15-19, so the icon is the PLAYER'S OWN DROID, built at run
time. That is why conRedraw sets dType from droidType before it draws.

The port cannot copy it the way it copies the other three, because the
port's droid artwork is not data: export_droids.py compiles it into 6502
per row and per digit glyph, baked in as immediates, and the compiled
form cannot be read back. It is also in the SPRITE banks, which the
console in bank 6 cannot see.

So the icon gets its own small copy of the two pieces the C64 composes:

    the rotor    ONE phase, 10 rows x 3 bytes            30 bytes
    the digits   ten glyphs, 8 rows x 1 byte each        80 bytes

110 bytes of the C64's OWN sprite bytes, against 1,743 for the full animated set at one shift. ConDroid
composes a row at a time from droid type, exactly as BuildDroidSprite and
AnimateDroids do between them.

ONE PHASE, NOT EIGHT. The console is a still screen; the C64's rotor keeps
spinning there because its sprite is the same one the game animates, not
because the console animates it.

THE LAYOUT, WHICH IS AnimateDroids' AND BuildDroidSprite'S
----------------------------------------------------------
    rows 0-4     rotor, top
    row  5       never written, so transparent
    rows 6-13    the three digits, one 4-pixel column each
    row  14      transparent
    rows 15-19   rotor, bottom -- the top five in reverse ROW order, with
                 rows 18/19 taking the OTHER entry of the 2-entry tables,
                 which is what makes the two ends alternate
    row  20      transparent

SHIFT 0, because an icon does not move. The seventh byte convert_row
emits is the spill a shifted copy would need and is dropped here.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'droidicon.asm'

PHASE = 0                       # the still the icon shows
DIGITS = 10
DIGIT_ROWS = 8
ROTOR_ROWS = 10                 # five top, five bottom
WIDTH = 6                       # 24 px at 4 pixels a byte


def load(name):
    spec = importlib.util.spec_from_file_location(name, PROJECT / 'tools' / (name + '.py'))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    return mod


def main():
    ed = load('export_droids')
    rg = load('rip_graphics')
    mem, _ = rg.parse_listing(rg.LST_FILE)

    frames, bottoms = ed.build_rotor(mem)
    top = frames[PHASE]                       # five rows of 3 C64 bytes
    other0, other1 = bottoms[PHASE]

    # The bottom five are the top five in reverse row order, with the two
    # end rows taking the other entry -- build_rotor's own note.
    bottom = [list(top[4]), list(top[3]), list(top[2]),
              [0, other1, 0], [0, other0, 0]]

    rotor = [list(r) for r in top + bottom]        # 3 C64 bytes a row

    # Each digit is ONE C64 sprite byte per row, so it converts to two
    # MODE 1 bytes -- eight pixels. Converting it alone rather than as
    # part of a three-byte row is what lets the three be recombined at
    # run time from the droid's own number.
    digits = []
    for d in range(DIGITS):
        digits.append([mem[ed.NUM_DATA + mem[ed.NUM_DATA_OFFSET + d] + 3 * r]
                       for r in range(DIGIT_ROWS)])

    out = []
    out.append('\\ ============================================================')
    out.append('\\ droidicon.asm - GENERATED by tools/export_droidicon.py')
    out.append('\\ ============================================================')
    out.append("\\ The console's first menu icon: the PLAYER'S OWN DROID, which the")
    out.append('\\ C64 builds at run time into $53C0 and cannot be copied as artwork.')
    out.append('\\ BuildDroidSprite ($3C77) writes the number, AnimateDroids ($3CFB)')
    out.append('\\ the rotor; ConDroid composes the two the same way.')
    out.append('\\')
    out.append('\\ The port\'s own droid artwork is COMPILED - 6502 with the pixels')
    out.append('\\ baked in as immediates - and lives in the sprite banks, which the')
    out.append('\\ console in bank 6 cannot see. Hence this separate 220 bytes.')
    out.append('\\')
    out.append('\\ ONE ROTOR PHASE, because the console is a still screen.')
    out.append('')
    out.append('GEN_DRICON_W      = 3        \ C64 sprite bytes a row')
    out.append('GEN_DRICON_DIGITS = %d' % DIGITS)
    out.append('')
    out.append('\\ Rows 0-4 then 15-19, three C64 sprite bytes each.')
    out.append('.conDrRotor')
    for i, r in enumerate(rotor):
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in r)
                   + '                          \\ row %d' % (i if i < 5 else i + 10))
    out.append('')
    out.append('\\ Digit 0-9, eight rows of ONE byte. BuildDroidSprite writes each')
    out.append('\\ digit into a byte column of its own, so a glyph is eight bytes and')
    out.append('\\ the three sit side by side without touching.')
    out.append('.conDrDigits')
    for d, rows in enumerate(digits):
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in rows) + '  \\ %d' % d)
    out.append('')
    out.append('ASSERT conDrDigits - conDrRotor == %d' % (ROTOR_ROWS * 3))
    out.append('ASSERT GEN_DRICON_W == CON_DRICON_W')
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote %s  (%d bytes)' % (OUT, ROTOR_ROWS * 3 + DIGITS * DIGIT_ROWS))

    # The icon as it will appear, for droid 001 -- rotor, gap, digits, gap.
    def px(row):
        return ''.join('#' if b & (0x80 >> n) else '.' for b in row for n in range(8))
    blank = [0, 0, 0]
    cent, num = mem[ed.DCENT_T + 0], mem[ed.DNUM_T + 0]
    dig = [cent, num >> 4, num & 0x0F]
    print('\n  droid %d%02X:' % (cent, num))
    for r in range(21):
        if r < 5:
            row = rotor[r]
        elif r in (5, 14, 20):
            row = blank
        elif r < 14:
            row = [digits[d][r - 6] for d in dig]
        else:
            row = rotor[r - 15 + 5]
        print('    ' + px(row))


if __name__ == '__main__':
    main()
