#!/usr/bin/env python3
"""
export_font.py - Convert the C64 Paradroid text font at $7000 to BBC MODE 1.

Emits src/data/textfont.asm.

THE FONT IS 8 x 16, NOT 8 x 8
-----------------------------
The $7000 charset stores a glyph's top half at code c and its bottom half
at code c + $80. Rendered, the map is:

    $00-$09   digits 0-9
    $0A-$23   lowercase a-z
    $2E       full stop
    $30       space
    $31-$37   frame pieces (not exported)
    $3A-$53   capitals A-Z

confirmed against Mobile_txt at $698A, which reads $46 $18 $0B $12 $15 $0E
= M o b i l e.

MODE 1 CONVERSION
-----------------
A MODE 1 character cell is 8 pixels wide by 8 scanlines and occupies 16
bytes: the left half's 8 scanlines then the right half's. An 8 x 16 glyph
is therefore TWO stacked cells, 32 bytes, and that is how each glyph is
emitted -- top cell first, then bottom.

MODE 1 packs 4 pixels per byte; pixel n takes bit (7-n) as its high colour
bit and bit (3-n) as its low bit. The source is 1bpp, so a set pixel gets
both bits and comes out as logical colour 3.

GLYPH INDEX
-----------
The port indexes glyphs 0-65 rather than by C64 code, so the table is
contiguous and PnAscii can map ASCII onto it with four compares:

    0        space
    1-10     digits 0-9
    11-36    capitals A-Z
    37-62    lowercase a-z
    63       full stop
    64       bar cell, full     synthesised -- the C64 has no energy bar
    65       bar cell, empty    and so nothing to be faithful to
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'textfont.asm'

FONT_BASE = 0x7000

# CAPITALS ARE 16 PIXELS WIDE, and DrawChar ($0C5F) is where that is
# stated: having written the code and code|$80 for the two rows, it does
#
#     AND #$7F : CMP #$3A : BCC _1 : CMP #$5A : BCS _1   ; see if it was wide
#     LDY #1 : ADC #$20 : STA (cpyDest),Y ...            ; ...and if so
#     INC prntX                                          ; two columns
#
# so a capital at code c has its RIGHT half at c + $20 and occupies two
# character cells. Lowercase and digits are 8 px and occupy one. The port
# keeps that: a capital is exported as two glyphs, left and right, and
# PnStr draws the second whenever the first is in the capital range —
# exactly DrawChar's own test.
#
# glyph index -> C64 code of the TOP-LEFT cell, or None if synthesised
GLYPHS = []
GLYPHS.append(('space', 0x30))
for d in range(10):
    GLYPHS.append((f"'{d}'", 0x00 + d))
for i in range(26):
    GLYPHS.append((f"'{chr(65+i)}' left", 0x3A + i))
for i in range(26):
    GLYPHS.append((f"'{chr(65+i)}' right", 0x3A + 0x20 + i))
for i in range(26):
    GLYPHS.append((f"'{chr(97+i)}'", 0x0A + i))
GLYPHS.append(("'.'", 0x2E))
GLYPHS.append(('bar full', None))
GLYPHS.append(('bar empty', None))

# The two synthesised bar cells, as 8x16 1bpp rows. A solid 6x12 block and
# an outline of the same, both sitting on the letters' baseline: the C64
# glyphs occupy source rows 2-13 of the 16, so these do too.
BAR_FULL = [0x00, 0x00] + [0x7E] * 12 + [0x00, 0x00]
BAR_EMPTY = [0x00, 0x00, 0x7E] + [0x42] * 10 + [0x7E, 0x00, 0x00]


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def glyph_rows(mem, code):
    """16 rows of 1bpp, top half then bottom half."""
    if code is None:
        return None
    top = [mem[FONT_BASE + code * 8 + r] for r in range(8)]
    bot = [mem[FONT_BASE + (code + 0x80) * 8 + r] for r in range(8)]
    return top + bot


def cell_bytes(rows8):
    """One MODE 1 cell: 8 scanlines of 8 pixels -> 16 bytes, left half then right."""
    left, right = [], []
    for row in rows8:
        lo = hi = 0
        for n in range(4):
            if row & (0x80 >> n):
                lo |= (0x80 >> n) | (0x08 >> n)
            if row & (0x08 >> n):
                hi |= (0x80 >> n) | (0x08 >> n)
        left.append(lo)
        right.append(hi)
    return left + right


def main():
    mem = load_memory()
    out = []
    out.append('\\ ============================================================')
    out.append('\\ textfont.asm - GENERATED by tools/export_font.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The C64 text font at $7000, converted to MODE 1.')
    out.append('\\')
    out.append('\\ IT IS 8 x 16, NOT 8 x 8: the glyph top half is at C64 code c and')
    out.append('\\ its bottom half at c + $80. A MODE 1 cell is 8 x 8 in 16 bytes, so')
    out.append('\\ a glyph is TWO STACKED CELLS, 32 bytes - top cell then bottom. That')
    out.append('\\ is why the panel holds two lines of text in five character rows.')
    out.append('\\')
    out.append('\\ CAPITALS ARE 16 PX WIDE, right half at C64 code + $20, which is')
    out.append('\\ DrawChar\'s own arrangement at $0C82 — "see if it was wide". Each is')
    out.append('\\ exported as two glyphs and PnStr draws the second when the first')
    out.append('\\ falls in the capital range. Lowercase and digits are 8 px, one cell.')
    out.append('\\')
    out.append('\\ Glyph index, contiguous so PnAscii can map ASCII with four compares:')
    out.append('\\   0 space, 1-10 digits, 11-36 capitals LEFT, 37-62 capitals RIGHT,')
    out.append('\\   63-88 lowercase, 89 full stop, 90 bar full, 91 bar empty.')
    out.append('\\ The two bar cells are SYNTHESISED - the C64 has no energy bar and so')
    out.append('\\ nothing to be faithful to. See docs/layer-9-hud.md, decision 3.')
    out.append('')
    out.append("\ Declared here and checked against main.asm's FONT_GLYPHS and")
    out.append('\ FONT_BYTES, which have to come first: beebasm resolves constants in')
    out.append('\ file order and droid.asm asserts on the font size before this file.')
    out.append('GEN_FONT_GLYPHS = %d' % len(GLYPHS))
    out.append('GEN_FONT_BYTES  = %d' % (len(GLYPHS) * 32))
    out.append('')
    out.append('.textfont')

    for idx, (name, code) in enumerate(GLYPHS):
        if code is None:
            rows = BAR_FULL if name == 'bar full' else BAR_EMPTY
        else:
            rows = glyph_rows(mem, code)
        data = cell_bytes(rows[:8]) + cell_bytes(rows[8:])
        assert len(data) == 32
        out.append('  \\ %2d  %s' % (idx, name))
        for half in (0, 16):
            out.append('  EQUB ' + ', '.join('&%02X' % b for b in data[half:half + 16]))

    out.append('.textfont_end')
    out.append('ASSERT textfont_end - textfont == GEN_FONT_BYTES')
    out.append('ASSERT GEN_FONT_GLYPHS == FONT_GLYPHS')
    out.append('ASSERT GEN_FONT_BYTES  == FONT_BYTES')
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print(f'wrote {OUT}  ({len(GLYPHS)} glyphs, {len(GLYPHS)*32} bytes)')

    # sanity: report which glyphs came out blank, which would mean a bad map
    blank = []
    for idx, (name, code) in enumerate(GLYPHS):
        if code is None:
            continue
        rows = glyph_rows(mem, code)
        if not any(rows):
            blank.append((idx, name, code))
    if blank:
        print('WARNING blank glyphs:', blank)
    else:
        print('no blank glyphs except space')


if __name__ == '__main__':
    main()
