#!/usr/bin/env python3
"""
export_icons.py - The console's menu icons, C64 sprites to MODE 1.

Emits src/data/conicons.asm.

WHERE THEY COME FROM
--------------------
conRedraw ($2C25) draws the menu by walking a table of 11-byte sprite
records at $6B89 until it has written the one for sprite 7:

    6B94: 01 34 00 90 FF 00 00 00 00 FF 4F
    6B9F: 02 34 00 AC FF 00 00 00 00 FF 50
    6BAA: 03 28 00 C8 FF 00 00 00 FF FF A1
    6BB5: 04 28 00 E0 FF 00 00 00 FF FF A2

so FOUR visible icons -- sprites 1 to 4, sprites 0 and 5 to 7 being all
zero. Byte 1 is the sprite X, byte 3 the Y and byte 10 the VIC image
pointer; the sprite data is at $4000 + ptr * 64, 24 x 21 pixels in 63
bytes, three bytes a row.

    ptr $4F -> $53C0   BLANK IN ROM. This is where BuildDroidSprite
                       composes the player's own droid at run time, which
                       is why conRedraw sets dType from droidType first.
                       Not exported -- see conicons.asm's header.
    ptr $50 -> $5400   the droid-number emblem
    ptr $A1 -> $6840   a circular ship-plan badge
    ptr $A2 -> $6880   a ship side view

They are HIRES, not multicolour: read as multicolour the shapes come out
as doubled-width mush, and as hires they are clean line art.

THE MODE 1 LAYOUT, AND WHY EACH ICON IS THREE FLAT COPIES
---------------------------------------------------------
Consecutive 4-pixel columns in the play buffer are EIGHT bytes apart, and
a column's eight bytes are eight consecutive scanlines -- so the six
columns of a 24 px sprite occupy 48 CONSECUTIVE bytes within one
character row. 21 scanlines is three character rows (the last three
scanlines blank), so an icon is three 48-byte copies at base, base + 640
and base + 1280. No shifting, no masking, no per-row arithmetic.
"""

import sys
import importlib.util
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OUT = PROJECT / 'src' / 'data' / 'conicons.asm'

VIC_BANK = 0x4000
ICONS = [
    ('droid number emblem', 0x50),
    ('ship plan badge', 0xA1),
    ('ship side view', 0xA2),
]
SPR_W, SPR_H = 24, 21
ROWS = 3                        # character rows an icon spans
UNITS = SPR_W // 4              # 4-pixel columns


def load_memory():
    spec = importlib.util.spec_from_file_location('rg', PROJECT / 'tools' / 'rip_graphics.py')
    rg = importlib.util.module_from_spec(spec)
    sys.modules['rg'] = rg
    try:
        spec.loader.exec_module(rg)
    except SystemExit:
        pass
    mem, _ = rg.parse_listing(rg.LST_FILE)
    return mem


def pixels(mem, ptr):
    """24 x 21 booleans from a hires C64 sprite."""
    base = VIC_BANK + ptr * 64
    out = []
    for y in range(SPR_H):
        row = []
        for i in range(3):
            b = mem[base + y * 3 + i]
            for bit in range(8):
                row.append(bool(b & (0x80 >> bit)))
        out.append(row)
    return out


def to_mode1(px):
    """Character row major, then 4-pixel column, then scanline: the order
    the buffer itself is in, so drawing is a straight copy."""
    data = []
    for crow in range(ROWS):
        for unit in range(UNITS):
            for sl in range(8):
                y = crow * 8 + sl
                b = 0
                for n in range(4):
                    x = unit * 4 + n
                    if y < SPR_H and px[y][x]:
                        b |= (0x80 >> n) | (0x08 >> n)   # logical colour 3
                data.append(b)
    return data


def main():
    mem = load_memory()
    out = []
    out.append('\\ ============================================================')
    out.append('\\ conicons.asm - GENERATED by tools/export_icons.py, do not edit')
    out.append('\\ ============================================================')
    out.append('\\ The console menu icons, C64 sprites 2, 3 and 4 of conRedraw\'s')
    out.append('\\ table at $6B94, converted to MODE 1.')
    out.append('\\')
    out.append('\\ SPRITE 1 IS NOT HERE. Its image pointer is $4F, and $53C0 is blank')
    out.append('\\ in ROM: that is where BuildDroidSprite composes the PLAYER\'S OWN')
    out.append('\\ droid at run time, which is why conRedraw sets dType from droidType')
    out.append('\\ before it draws. Ours is drawn from the sprite bank instead.')
    out.append('\\')
    out.append('\\ Each icon is 24 x 21 px = THREE character rows of six 4-pixel')
    out.append('\\ columns. Consecutive columns are eight bytes apart and a column is')
    out.append('\\ eight consecutive scanlines, so the six columns of one row are 48')
    out.append('\\ CONSECUTIVE bytes in the buffer -- an icon is three flat 48-byte')
    out.append('\\ copies at base, base + 640 and base + 1280.')
    out.append('')
    out.append('GEN_ICON_COUNT = %d' % len(ICONS))
    out.append('GEN_ICON_ROWS  = %d' % ROWS)
    out.append('GEN_ICON_BYTES = %d' % (ROWS * UNITS * 8))
    out.append('')
    out.append('.conicons')
    for name, ptr in ICONS:
        data = to_mode1(pixels(mem, ptr))
        assert len(data) == ROWS * UNITS * 8
        out.append('  \\ %s  (sprite pointer $%02X, $%04X)' % (name, ptr, VIC_BANK + ptr * 64))
        for i in range(0, len(data), 16):
            out.append('  EQUB ' + ', '.join('&%02X' % b for b in data[i:i + 16]))
    out.append('.conicons_end')
    out.append('ASSERT conicons_end - conicons == GEN_ICON_COUNT * GEN_ICON_BYTES')
    out.append('ASSERT GEN_ICON_COUNT == CON_ICON_COUNT')
    out.append('ASSERT GEN_ICON_BYTES == CON_ICON_BYTES')
    out.append('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote %s  (%d icons, %d bytes each, %d total)'
          % (OUT, len(ICONS), ROWS * UNITS * 8, len(ICONS) * ROWS * UNITS * 8))

    for name, ptr in ICONS:
        px = pixels(mem, ptr)
        print('\n  %s:' % name)
        for y in range(SPR_H):
            print('    ' + ''.join('#' if p else '.' for p in px[y]))


if __name__ == '__main__':
    main()
