#!/usr/bin/env python3
"""
export_player.py - Build the player droid sprite as BBC MODE 1 blitter data.

Emits src/data/player.asm.

Where the sprite comes from
---------------------------
There is no player sprite in the C64 data. Every droid's sprite is CONSTRUCTED
at runtime in the dynamic sprite area at $5200-$53FF, which ships zeroed:

  BuildDroidSprite ($3C77)  writes the three-digit droid number into sprite
                            rows 6-13, one 4-pixel-wide digit per byte column.
  AnimateDroids    ($3CFB)  writes the spinning ring into rows 0-4 and 15-19
                            from the RotAnim_* tables, indexed by a counter
                            kept in the sprite's own pad byte ($3F).

Rows 5, 14 and 20 are never written, so they stay transparent. That is the
whole sprite: a rotor above and below, the droid's number in the middle.

The ring has 8 phases, so there are 8 frames. The bottom half is the top half
in reverse ROW order (row 15 = row 4, 16 = 3, 17 = 2), not mirrored left to
right - AnimateDroids writes the same L/M/R bytes both times. Rows 0/1/18/19
carry only a middle byte, from a 2-entry table indexed by phase >> 2; the
bottom pair uses the other entry, so the two ends of the rotor alternate.

Droid 001 is the player: DCent_t[0] = 0 and DNum_t[0] = $01, giving digits
0, 0, 1.

Colour
------
A C64 multicolour sprite's bit pairs mean:

  00  transparent
  01  $D025 sprite multicolour 0  = $F0 -> black   (set at $10CE)
  10  the sprite's own colour     = $F1 -> white   (sprite 7, set by AnimateDroids)
  11  $D026 sprite multicolour 1  = $F8 -> orange  (set at $12D5)

MODE 1's four logical colours are the deck's, and they are not these - the
palette is rebuilt per deck by export_bbc.assign_palette. So the three sprite
colours are mapped onto logical 1-3 by role rather than by value, below. The
player consequently changes colour with the deck, exactly as the tiles do.

Output format
-------------
The blitter walks the sprite one scanline at a time, because a 21-row sprite
does not align to the 8-scanline groups BBC screen memory uses and the play
buffer is a circular strip anyway.

Rows are stored SEVEN bytes wide, not six. 24 px is 6 MODE 1 bytes when the
sprite sits on a 4-pixel boundary, but the dead-zone camera positions it every
2 pixels, and a 2-pixel shift spills into a seventh byte. The shifted copy is
generated at startup rather than stored, so only the unshifted set is here.

NO MASKS ARE STORED. The mask is derivable: every opaque pixel maps to logical
colour 1, 2 or 3 (see COLOUR), never 0, so a pixel is transparent exactly when
both of its bits are clear. The blitter recovers it with one lookup through a
256-byte table built at startup. That halves the data and, because the copy
into the row buffer was going to happen anyway, costs nothing at blit time.

Only 65 distinct rows exist: 5 ring rows x 8 phases, 2 alternate end rows x 8
phases, 8 digit rows shared by every phase, and one blank. 65 x 7 = 455 bytes,
plus 8 x 21 sixteen-bit row offsets so the blitter can find them.

Requires: Python 3. No third-party dependencies.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from rip_levels import parse_listing  # noqa: E402

PROJECT = Path(__file__).resolve().parent.parent
LST_FILE = PROJECT / 'paradroid_ce.lst'
OUT_DIR = PROJECT / 'src' / 'data'

# --- C64 addresses ---------------------------------------------------------
ROT_2_17L = 0x6B0E
ROT_2_17M = 0x6B16
ROT_3_16L = 0x6B1E
ROT_3_16M = 0x6B26
ROT_3_16R = 0x6B2E
ROT_4_15L = 0x6B36
ROT_4_15M = 0x6B3E
ROT_4_15R = 0x6B46
ROT_0_19M = 0x6B4E          # 2 entries
ROT_1_18M = 0x6B50          # 2 entries

NUM_DATA_OFFSET = 0x6AA4    # digit -> offset into NumData
NUM_DATA = 0x6AAE

DCENT_T = 0xEA00            # droid type -> hundreds digit
DNUM_T = 0xEA20             # droid type -> tens/units, packed BCD

PLAYER_TYPE = 0             # droid 001

# AnimateDroids writes $80 into the right-hand byte of rows 2 and 17. There is
# no RotAnim_2_17R table; the accumulator still holds $80 from the row above.
ROW_2_17_R = 0x80

SPRITE_ROWS = 21
FRAMES = 8

# C64 sprite bit pair -> BBC MODE 1 logical colour. 0 is the background and
# is never used, because 00 is transparent.
COLOUR = {
    0b00: None,             # transparent
    0b01: 2,                # black  -> logical 2, which assign_palette
                            #           prefers to put on physical black
    0b10: 1,                # white  -> logical 1, the highlight
    0b11: 3,                # orange -> logical 3, the grid/accent colour
}

BANNER = """\\ ============================================================
\\ {name}
\\ GENERATED by tools/export_player.py - do not edit by hand.
\\ Source: paradroid_ce.lst (Paradroid Redux, C64)
\\ {desc}
\\ ============================================================
"""


def emit_bytes(f, data, per_line=12):
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        f.write('  EQUB ' + ','.join('&%02X' % b for b in chunk) + '\n')


def build_c64_rows(mem):
    """The 8 ring frames and the shared digit block, as C64 sprite bytes.

    Returns (frames, digits) where frames[f] is 5 rows of 3 bytes (sprite rows
    0-4) and digits is 8 rows of 3 bytes (sprite rows 6-13).
    """
    frames = []
    for phase in range(FRAMES):
        top = mem[ROT_0_19M + (phase >> 2)]
        rows = [
            [0, top, 0],                                        # row 0
            [0, mem[ROT_1_18M + (phase >> 2)], 0],              # row 1
            [mem[ROT_2_17L + phase], mem[ROT_2_17M + phase], ROW_2_17_R],
            [mem[ROT_3_16L + phase], mem[ROT_3_16M + phase], mem[ROT_3_16R + phase]],
            [mem[ROT_4_15L + phase], mem[ROT_4_15M + phase], mem[ROT_4_15R + phase]],
        ]
        frames.append(rows)

    # The bottom pair of rows uses the OTHER entry of the 2-entry tables:
    # AnimateDroids does INX / AND #1 between writing the top and the bottom.
    # Rows 15-17 reuse rows 4-2 unchanged, so only 0/1 need the alternate.
    bottoms = []
    for phase in range(FRAMES):
        other = ((phase >> 2) + 1) & 1
        bottoms.append((mem[ROT_0_19M + other], mem[ROT_1_18M + other]))

    digits_of = [mem[DCENT_T + PLAYER_TYPE],
                 mem[DNUM_T + PLAYER_TYPE] >> 4,
                 mem[DNUM_T + PLAYER_TYPE] & 0x0F]
    digits = []
    for r in range(8):
        row = []
        for d in digits_of:
            row.append(mem[NUM_DATA + mem[NUM_DATA_OFFSET + d] + 3 * r])
        digits.append(row)

    return frames, bottoms, digits


def convert_row(c64_row):
    """3 C64 multicolour bytes -> 7 MODE 1 data bytes.

    Each C64 byte is four 2-bit pixels; each becomes two MODE 1 pixels, so a
    C64 byte is two MODE 1 bytes. MODE 1 pixel n takes bit (7-n) as its high
    colour bit and bit (3-n) as its low bit; a transparent pixel gets neither.

    The seventh byte is always empty. It exists so that the 2-pixel-shifted
    copy generated at startup has somewhere to put the pixels that spill out
    of byte 6, and so every row is the same width whichever shift is in use.
    """
    data = []
    for byte in c64_row:
        pixels = [(byte >> 6) & 3, (byte >> 4) & 3, (byte >> 2) & 3, byte & 3]
        doubled = [p for p in pixels for _ in (0, 1)]        # 8 MODE 1 pixels
        for half in (doubled[:4], doubled[4:]):
            d = 0
            for n, pair in enumerate(half):
                logical = COLOUR[pair]
                if logical is None:
                    continue                    # transparent: both bits clear
                assert logical != 0, (
                    'an opaque sprite pixel mapped to logical 0; the mask can '
                    'no longer be derived from the data')
                if logical & 2:
                    d |= 1 << (7 - n)
                if logical & 1:
                    d |= 1 << (3 - n)
            data.append(d)
    data.append(0)
    return data


def main():
    mem, _ = parse_listing(LST_FILE)
    frames, bottoms, digits = build_c64_rows(mem)

    # --- flatten every distinct row into one table -------------------------
    # order: ring[phase][0..4], ringbot[phase][0..1], digits[0..7], blank
    rows = []
    ring_at, bot_at, dig_at = {}, {}, {}
    for phase in range(FRAMES):
        for r in range(5):
            ring_at[(phase, r)] = len(rows)
            rows.append(convert_row(frames[phase][r]))
    for phase in range(FRAMES):
        for r in range(2):               # 0 = sprite row 19, 1 = sprite row 18
            bot_at[(phase, r)] = len(rows)
            rows.append(convert_row([0, bottoms[phase][r], 0]))
    for r in range(8):
        dig_at[r] = len(rows)
        rows.append(convert_row(digits[r]))
    blank_at = len(rows)
    rows.append([0] * 7)

    # --- which stored row each of the 21 sprite rows uses, per phase -------
    def row_index(phase, r):
        if r < 5:
            return ring_at[(phase, r)]
        if r in (5, 14, 20):
            return blank_at
        if r < 14:
            return dig_at[r - 6]
        if r < 18:
            return ring_at[(phase, 19 - r)]      # 15->4, 16->3, 17->2
        return bot_at[(phase, 19 - r)]           # 18->bot 1, 19->bot 0

    offsets = []
    for phase in range(FRAMES):
        for r in range(SPRITE_ROWS):
            offsets.append(row_index(phase, r) * 7)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / 'player.asm'
    with open(path, 'w') as f:
        f.write(BANNER.format(
            name='player.asm',
            desc='Droid 001, 8 ring phases + shared digit block, 24x21 MODE 1'))
        f.write('\n')
        f.write('PLY_W        = 7                \ 24 px, plus one for a 2 px shift\n')
        f.write('PLY_H        = %d\n' % SPRITE_ROWS)
        f.write('PLY_FRAMES   = %d\n' % FRAMES)
        f.write('PLY_ROWS     = %d               \ distinct stored rows\n' % len(rows))
        f.write('PLY_DATASIZE = PLY_ROWS * PLY_W\n')
        f.write('\n')

        f.write('\ Every distinct row, seven bytes each, unshifted. The 2 px\n')
        f.write('\ shifted copy is built from this at startup, and masks are\n')
        f.write('\ derived rather than stored - see the header comment.\n')
        f.write('.plySprData\n')
        for row in rows:
            emit_bytes(f, row, per_line=7)
        f.write('\n')

        f.write('\ Byte offset into plySprData for sprite row r of phase p, at\n')
        f.write('\ index p*%d + r. Blank rows point at a real all-transparent\n'
                % SPRITE_ROWS)
        f.write('\ row, so the blit needs no special case for them.\n')
        f.write('.plyOfsLo\n')
        emit_bytes(f, [o & 0xFF for o in offsets], per_line=SPRITE_ROWS)
        f.write('.plyOfsHi\n')
        emit_bytes(f, [o >> 8 for o in offsets], per_line=SPRITE_ROWS)
        f.write('\n')
        f.write('\\ p * %d, to index the tables above.\n' % SPRITE_ROWS)
        f.write('.plyMulRows\n')
        emit_bytes(f, [SPRITE_ROWS * p for p in range(FRAMES)], per_line=FRAMES)
        f.write('\n')

    print('%s  (%d rows, %d bytes of data + %d of tables)'
          % (path, len(rows), len(rows) * 7, len(offsets) * 2 + FRAMES))


if __name__ == '__main__':
    main()
