#!/usr/bin/env python3
"""
pack_overlays.py - ZX0 the overlays that are ASSEMBLED CODE.

no-load step 5. Some of what the game keeps in a bank is not data but
code assembled at a fixed address and copied down to run there: the
PARBRF briefing driver at &0400, the low overlay at &0E00 and the
keyredef screen, which depacks over the briefing's page. beebasm
cannot compress its own output, so they shipped raw and cost their
full size in a bank.

THIS IS THE EXTRA BUILD PASS THAT LETS THEM SHIP PACKED. main.asm
SAVEs each block to the disc image under an X-name; this reads those
back out, ZX0s them with the compressor tools/zx0tool.py finds (round-
tripped through
tools/zx0.py, as make_disc.py does), and writes one generated file per
overlay for the NEXT assembly to INCLUDE.

    XBRF -> src/data/brfimg.asm   .brfImg   BRF_IMG_UNPACKED
    XLOW -> src/data/lowimg.asm   .lowImg   LOW_IMG_UNPACKED
    XKR  -> src/data/krimg.asm    .krImg    KR_IMG_UNPACKED

CONVERGENCE, and why the build loop is shaped as it is: a pass whose
generated streams are a different SIZE from the ones it produces has
laid the banks out differently, and an overlay that references a bank
label would then have been extracted from the wrong layout. So the
exit code says whether anything changed -

    0   nothing changed: the image just built IS the converged one
    10  a stream was rewritten: assemble again

- and build.ps1 loops on it. In the steady state that is ONE assembly:
the first pass extracts what is already there and exits 0.

The X-files are dropped from the shipping image by make_disc.py's
BUILD_ONLY set. That has to be explicit: build_image appends any file it
does not recognise, which is how an --intro build carries PINTRO's data,
so relying on LAYOUT alone shipped all four.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import zx0                       # noqa: E402
import zx0tool                   # noqa: E402

PROJECT = Path(__file__).resolve().parent.parent
SECTOR = 256

# disc name -> (generated file, label, size constant, what it is).
#
# THERE IS NO SIZE ASSERT, and that was tried: an
# `ASSERT BRF_IMG_UNPACKED == brf_end - brf_start` in the generated file
# makes a CHANGED overlay unbuildable, because the assembly that would
# produce the new bytes is the one the stale assert stops. The loop's
# byte-for-byte comparison is the guard, and it is the stronger one - it
# checks the content, not just the length, on every build.
OVERLAYS = {
    'XBRF': ('brfimg.asm', 'brfImg', 'BRF_IMG_UNPACKED',
             'the PARBRF briefing driver, copied down to &0400'),
    'XLOW': ('lowimg.asm', 'lowImg', 'LOW_IMG_UNPACKED',
             'the low overlay, staged at LOW_STAGE and copied to &0E00'),
    'XKR':  ('krimg.asm', 'krImg', 'KR_IMG_UNPACKED',
             "the keyredef screen, depacked over the briefing's page"),
}


def catalogue(img):
    files = {}
    for i in range(img[0x105] // 8):
        n = 8 + i * 8
        name = img[n:n + 7].decode('latin-1').strip()
        a = img[0x100 + n:0x100 + n + 8]
        length = a[4] | (a[5] << 8) | (((a[6] >> 4) & 3) << 16)
        start = a[7] | ((a[6] & 3) << 8)
        files[name] = img[start * SECTOR:start * SECTOR + length]
    return files


def pack(raw, name, zx0_exe):
    packed = zx0tool.run_zx0(zx0_exe, raw)
    if zx0.decompress(packed) != raw:
        raise SystemExit('%s: stream fails the zx0.py round-trip' % name)
    return packed


def emit(path, label, const, what, raw, packed):
    bs = chr(92)
    out = [
        bs + ' ============================================================',
        bs + ' %s - GENERATED by tools/pack_overlays.py' % path.name,
        bs + ' ============================================================',
        bs + ' %s.' % what[0].upper() + what[1:],
        bs + ' ZX0 of the block main.asm assembles at its run address and',
        bs + " SAVEs under an X-name: %d bytes -> %d." % (len(raw), len(packed)),
        bs + ' Do not edit; it is rewritten by the build whenever the code',
        bs + ' it holds changes, and the build assembles again when it is.',
        '',
        '%-16s = %d' % (const, len(raw)),
        '.%s' % label,
    ]
    for j in range(0, len(packed), 16):
        out.append('  EQUB ' + ', '.join('&%02X' % b for b in packed[j:j + 16]))
    out.append('.%s_end' % label)
    out.append('')
    text = chr(10).join(out) + chr(10)
    old = path.read_text() if path.exists() else None
    if old == text:
        return False
    path.write_text(text)
    return True


def main():
    args = sys.argv[1:]
    zx0_arg = zx0tool.take_zx0_arg(args)
    # --ensure: write a stub for any generated file that does not exist yet
    # and stop. beebasm cannot INCLUDE a missing file, so a fresh clone has
    # to get past the first assembly somehow; the loop fills them in.
    ensure = '--ensure' in args
    if ensure:
        args.remove('--ensure')
    if not args:
        raise SystemExit(__doc__)
    img_path = Path(args[0])
    zx0_exe = zx0tool.find_zx0(zx0_arg)

    if ensure:
        for fname, label, const, what in OVERLAYS.values():
            path = PROJECT / 'src' / 'data' / fname
            if not path.exists():
                stub = bytes(1)
                emit(path, label, const, what, stub,
                     pack(stub, fname, zx0_exe))
                print('pack_overlays: stubbed %s' % fname)
        return

    files = catalogue(img_path.read_bytes()) if img_path.exists() else {}
    changed, report = [], []
    for disc, (fname, label, const, what) in OVERLAYS.items():
        path = PROJECT / 'src' / 'data' / fname
        raw = files.get(disc)
        if raw is None:
            # bootstrap: no image to read yet, so emit a one-byte stub. It
            # only has to ASSEMBLE - the pass that reads it is the one that
            # produces the real bytes, and the loop then runs again.
            if not path.exists():
                stub = bytes(1)
                emit(path, label, const, what, stub, pack(stub, disc, zx0_exe))
                changed.append(disc)
            continue
        packed = pack(raw, disc, zx0_exe)
        report.append('%s %d->%d' % (disc, len(raw), len(packed)))
        if emit(path, label, const, what, raw, packed):
            changed.append(disc)

    print('pack_overlays: ' + ', '.join(report)
          + ('; rewrote ' + ', '.join(changed) + ' - assembling again'
             if changed else '; unchanged'))
    sys.exit(10 if changed else 0)


if __name__ == '__main__':
    main()
