\ ============================================================
\ consolesel.asm - the console menu's selection, in bank 4
\ ============================================================
\ The C64 marks the chosen menu entry by RECOLOURING ITS ICON and nothing
\ else. conWaitInput ($2C63) writes SpriteColor $F1 - VIC colour 1, white -
\ to the newly selected sprite and puts $FF back on the one it left, taking
\ that value from the sprite table's own field at $6B94+9 (colour 15, light
\ grey); WrSpriteState ($09B7) STAs the byte into $D027,Y. A white marker
\ bar stood here until 2026-08-24 and it was OURS, not the original's.
\
\ BLACK AND WHITE, because MODE 1 has no grey. KC took the brightness step
\ to its ends rather than swapping in a hue. Layer-9 DECISION 18.
\
\ IT IS A TRANSFORM, NOT A REDRAW. ConIcons (bank 6) plots every icon in
\ logical 3, and an icon is two-colour - ink or nothing - so its SHAPE
\ lives entirely in the LOW nibble of every byte. Rebuilding the high
\ nibble from the low is therefore lossless in both directions:
\
\     high nibble 0     -> logical 1, black
\     high nibble = low -> logical 3, white
\
\ one patched AND chooses between them, and no second copy of the artwork
\ is needed. Neither bank 6 nor main RAM had room for one.
\
\ WHY THIS FILE EXISTS, AND WHY IT IS INCLUDED WHERE IT IS.
\ Bank 4 had TWO bytes free and this needs about eighty. The room is
\ colourMap's alignment padding: colours.asm ends with ALIGN &100, which
\ left 162 unused bytes in front of it. **Deleting that ALIGN recovers
\ nothing** - tiledefs.asm aligns next and simply pads by the same amount,
\ and the bank still ended at &BFFE when it was tried. The padding is only
\ recoverable by putting something INSIDE it, and anything assembled
\ ANYWHERE before that ALIGN lands there: the pad shrinks by what you add,
\ and the page boundary - and so the end of the bank - does not move.
\
\ So this is INCLUDEd between chardata.asm and colours.asm, and its cost is
\ zero until it exceeds 162 bytes. Past that the ALIGN rounds to the next
\ page and it costs 256 at a stroke, so watch the fuel gauge if it grows.
\ src/data/ is generated by export_bbc.py, which is why this cannot simply
\ live in colours.asm.
\
\ IT CANNOT SEE console.asm's CONSTANTS. That file is bank 6 and beebasm
\ resolves constants in file order, so CON_ICON_ROWS and the icon
\ destinations do not exist yet. The literals below are console.asm's job
\ to ASSERT, and it does.

CON_SEL_ROWS  = 3               \ an icon is 21 scanlines, so three rows
CON_SEL_UNITS = 12              \ and the widest is 48 px - see below
CON_SEL_BYTES = CON_SEL_UNITS * UNIT_BYTES

\ TWELVE UNITS FOR ALL FOUR, though only the lower two are that wide
\ (SpriteXExp $FF; the upper two are six). The six units past a narrow
\ icon are blank buffer - ConClear cleared them and the text starts at
\ CON_COL_TEXT, unit 24 - and the transform leaves a zero byte zero. A
\ width table would have cost more than the wasted loop.

\ The four icons in conSel order: the player's own 001, then ship, deck
\ and alert. console.asm ASSERTs these against CON_DROID_D/CON_ICON_D*.
\ The rows moved when Redux's droid counts went in -- layer-12
\ [DECISION 5], console.asm's CON_ROW_* block. The ASSERTs there are
\ what caught these literals, which is what they are for.
CON_SEL0 = BUF_BASE +  3 * ROW_BYTES + 7 * UNIT_BYTES
CON_SEL1 = BUF_BASE +  6 * ROW_BYTES + 7 * UNIT_BYTES
CON_SEL2 = BUF_BASE +  9 * ROW_BYTES + 4 * UNIT_BYTES
CON_SEL3 = BUF_BASE + 12 * ROW_BYTES + 4 * UNIT_BYTES

\ ONE ENTRY, repainting all four, rather than the original's dim-the-old
\ and light-the-new. That form needs two entry points and two calls per
\ step; this needs one, and every caller - a menu step, and both paths
\ that arrive after a full redraw - wants exactly the same thing.
\ ---- the ink table: the colour BEFORE anything is drawn -----
\ KC, 2026-08-24: "the icon should be drawn in the correct colour once."
\ It was not - ConIcons plotted all four white and the transform below
\ then blackened three, and because the icons go down SECOND in ConDraw
\ and the recolour ran after every line of text, they sat white for the
\ whole of the text draw. Visibly.
\ So the colour is chosen HERE, before the draw, into a main-RAM table
\ that bank 6's ConIcons and ConDroid read: conSel is this bank's and
\ bank 6 cannot see it. csn_put (console.asm) is the one place the ink
\ is applied, and it uses the SAME transform as ConIconSel4 below - the
\ two agree by construction rather than by being kept in step.
\ THE TRANSFORM IS STILL NEEDED. A menu step does not redraw anything,
\ so it recolours the icons where they lie; only the two paths that
\ arrive after a full redraw are served by the table alone.
.ConIconInk4
  LDX #3
.cii_each
  LDA #&00                      \ black
  CPX conSel
  BNE cii_put
  LDA #&F0                      \ white: the one that is chosen
.cii_put
  STA conInkT,X
  DEX
  BPL cii_each
  RTS

\ ---- and the same four, recoloured where they already lie ---
.ConIconSel4
  JSR ConIconInk4               \ so a later redraw agrees with this
  LDX #3
.cis_each
  STX conSelIx
  LDA #&00                      \ black: the high plane goes to zero
  CPX conSel
  BNE cis_ink
  LDA #&F0                      \ white: it takes a copy of the low one
.cis_ink
  STA cis_mask+1
  LDA conSelLo,X : STA swDst
  LDA conSelHi,X : STA swDst+1
  LDX #CON_SEL_ROWS
.cis_row
  LDY #CON_SEL_BYTES-1
.cis_byte
  LDA (swDst),Y
  AND #&0F                      \ the shape, in the low colour plane
  STA (swDst),Y                 \ stored now, so the ORA below can read
  ASL A : ASL A : ASL A : ASL A \ it back and no scratch byte is needed
.cis_mask
  AND #&00                      \ operand patched above
  ORA (swDst),Y
  STA (swDst),Y
  DEY
  BPL cis_byte
  CLC
  LDA swDst   : ADC #LO(ROW_BYTES) : STA swDst
  LDA swDst+1 : ADC #HI(ROW_BYTES) : STA swDst+1
  DEX
  BNE cis_row
  LDX conSelIx
  DEX
  BPL cis_each
  RTS

.conSelLo
  EQUB LO(CON_SEL0), LO(CON_SEL1), LO(CON_SEL2), LO(CON_SEL3)
.conSelHi
  EQUB HI(CON_SEL0), HI(CON_SEL1), HI(CON_SEL2), HI(CON_SEL3)
.conSelIx EQUB 0

