\ ============================================================
\ brextra.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ The characters the shared font has not got. The renderer
\ plots a glyph index of BR_XTRA0 or above from here rather
\ than from textfont, with this bank paged - so unlike the
\ page streams these bytes are read on the HOT path and must
\ be in the briefing's own resting bank.

.brExtra
  \ ',' = index 104
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  \ "'" = index 105
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  \ ';' = index 106
  EQUB &00, &00, &00, &00, &70, &70, &00, &00
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  \ '@' = index 107
  EQUB &00, &00, &00, &3C, &42, &9D, &A1, &A1
  EQUB &9D, &42, &3C, &00, &00, &00, &00, &00

