\ ============================================================
\ briefconst.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ The briefing text's shape, and nothing else. Separate from
\ briefing.asm because main.asm includes THIS from its header,
\ ahead of the PARBRF overlay that reads it, while the data
\ itself stays in the bank. Edit src/data/briefing.txt.

BR_PAGES     = 5
BR_ROW_LO    = 1
BR_ROW_HI    = 57
BR_ROWS      = BR_ROW_HI - BR_ROW_LO + 1

\ Characters the shared font has not got; the renderer plots an
\ index of BR_XTRA0 or above from brExtra, not from the font.
BR_XTRA0     = 104
