\ ============================================================
\ briefing.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ From src/data/briefing.txt, the hand-editable text. Edit THAT
\ and rebuild; do not edit this. Format and rules: the tool.

BR_PAGES     = 5
BR_ROW_LO    = 1
BR_ROW_HI    = 57
BR_ROWS      = BR_ROW_HI - BR_ROW_LO + 1

\ Characters the shared font has not got; the renderer plots an
\ index of BR_XTRA0 or above from brExtra, not from the font.
BR_XTRA0     = 104

\ A row list is (col, glyphs..., $FE) per record, then $FF.
\ Rows with nothing on them are one byte: $FF.

.brRowLo_0
  EQUB LO(brRow_0_1)
  EQUB LO(brRow_0_2)
  EQUB LO(brRow_0_3)
  EQUB LO(brRow_0_4)
  EQUB LO(brRow_0_5)
  EQUB LO(brRow_0_6)
  EQUB LO(brRow_0_7)
  EQUB LO(brRow_0_8)
  EQUB LO(brRow_0_9)
  EQUB LO(brRow_0_10)
  EQUB LO(brRow_0_11)
  EQUB LO(brRow_0_12)
  EQUB LO(brRow_0_13)
  EQUB LO(brRow_0_14)
  EQUB LO(brRow_0_15)
  EQUB LO(brRow_0_16)
  EQUB LO(brRow_0_17)
  EQUB LO(brRow_0_18)
  EQUB LO(brRow_0_19)
  EQUB LO(brRow_0_20)
  EQUB LO(brRow_0_21)
  EQUB LO(brRow_0_22)
  EQUB LO(brRow_0_23)
  EQUB LO(brRow_0_24)
  EQUB LO(brRow_0_25)
  EQUB LO(brRow_0_26)
  EQUB LO(brRow_0_27)
  EQUB LO(brRow_0_28)
  EQUB LO(brRow_0_29)
  EQUB LO(brRow_0_30)
  EQUB LO(brRow_0_31)
  EQUB LO(brRow_0_32)
  EQUB LO(brRow_0_33)
  EQUB LO(brRow_0_34)
  EQUB LO(brRow_0_35)
  EQUB LO(brRow_0_36)
  EQUB LO(brRow_0_37)
  EQUB LO(brRow_0_38)
  EQUB LO(brRow_0_39)
  EQUB LO(brRow_0_40)
  EQUB LO(brRow_0_41)
  EQUB LO(brRow_0_42)
  EQUB LO(brRow_0_43)
  EQUB LO(brRow_0_44)
  EQUB LO(brRow_0_45)
  EQUB LO(brRow_0_46)
  EQUB LO(brRow_0_47)
  EQUB LO(brRow_0_48)
  EQUB LO(brRow_0_49)
  EQUB LO(brRow_0_50)
  EQUB LO(brRow_0_51)
  EQUB LO(brRow_0_52)
  EQUB LO(brRow_0_53)
  EQUB LO(brRow_0_54)
  EQUB LO(brRow_0_55)
  EQUB LO(brRow_0_56)
  EQUB LO(brRow_0_57)
.brRowHi_0
  EQUB HI(brRow_0_1)
  EQUB HI(brRow_0_2)
  EQUB HI(brRow_0_3)
  EQUB HI(brRow_0_4)
  EQUB HI(brRow_0_5)
  EQUB HI(brRow_0_6)
  EQUB HI(brRow_0_7)
  EQUB HI(brRow_0_8)
  EQUB HI(brRow_0_9)
  EQUB HI(brRow_0_10)
  EQUB HI(brRow_0_11)
  EQUB HI(brRow_0_12)
  EQUB HI(brRow_0_13)
  EQUB HI(brRow_0_14)
  EQUB HI(brRow_0_15)
  EQUB HI(brRow_0_16)
  EQUB HI(brRow_0_17)
  EQUB HI(brRow_0_18)
  EQUB HI(brRow_0_19)
  EQUB HI(brRow_0_20)
  EQUB HI(brRow_0_21)
  EQUB HI(brRow_0_22)
  EQUB HI(brRow_0_23)
  EQUB HI(brRow_0_24)
  EQUB HI(brRow_0_25)
  EQUB HI(brRow_0_26)
  EQUB HI(brRow_0_27)
  EQUB HI(brRow_0_28)
  EQUB HI(brRow_0_29)
  EQUB HI(brRow_0_30)
  EQUB HI(brRow_0_31)
  EQUB HI(brRow_0_32)
  EQUB HI(brRow_0_33)
  EQUB HI(brRow_0_34)
  EQUB HI(brRow_0_35)
  EQUB HI(brRow_0_36)
  EQUB HI(brRow_0_37)
  EQUB HI(brRow_0_38)
  EQUB HI(brRow_0_39)
  EQUB HI(brRow_0_40)
  EQUB HI(brRow_0_41)
  EQUB HI(brRow_0_42)
  EQUB HI(brRow_0_43)
  EQUB HI(brRow_0_44)
  EQUB HI(brRow_0_45)
  EQUB HI(brRow_0_46)
  EQUB HI(brRow_0_47)
  EQUB HI(brRow_0_48)
  EQUB HI(brRow_0_49)
  EQUB HI(brRow_0_50)
  EQUB HI(brRow_0_51)
  EQUB HI(brRow_0_52)
  EQUB HI(brRow_0_53)
  EQUB HI(brRow_0_54)
  EQUB HI(brRow_0_55)
  EQUB HI(brRow_0_56)
  EQUB HI(brRow_0_57)
.brRowLo_1
  EQUB LO(brRow_1_1)
  EQUB LO(brRow_1_2)
  EQUB LO(brRow_1_3)
  EQUB LO(brRow_1_4)
  EQUB LO(brRow_1_5)
  EQUB LO(brRow_1_6)
  EQUB LO(brRow_1_7)
  EQUB LO(brRow_1_8)
  EQUB LO(brRow_1_9)
  EQUB LO(brRow_1_10)
  EQUB LO(brRow_1_11)
  EQUB LO(brRow_1_12)
  EQUB LO(brRow_1_13)
  EQUB LO(brRow_1_14)
  EQUB LO(brRow_1_15)
  EQUB LO(brRow_1_16)
  EQUB LO(brRow_1_17)
  EQUB LO(brRow_1_18)
  EQUB LO(brRow_1_19)
  EQUB LO(brRow_1_20)
  EQUB LO(brRow_1_21)
  EQUB LO(brRow_1_22)
  EQUB LO(brRow_1_23)
  EQUB LO(brRow_1_24)
  EQUB LO(brRow_1_25)
  EQUB LO(brRow_1_26)
  EQUB LO(brRow_1_27)
  EQUB LO(brRow_1_28)
  EQUB LO(brRow_1_29)
  EQUB LO(brRow_1_30)
  EQUB LO(brRow_1_31)
  EQUB LO(brRow_1_32)
  EQUB LO(brRow_1_33)
  EQUB LO(brRow_1_34)
  EQUB LO(brRow_1_35)
  EQUB LO(brRow_1_36)
  EQUB LO(brRow_1_37)
  EQUB LO(brRow_1_38)
  EQUB LO(brRow_1_39)
  EQUB LO(brRow_1_40)
  EQUB LO(brRow_1_41)
  EQUB LO(brRow_1_42)
  EQUB LO(brRow_1_43)
  EQUB LO(brRow_1_44)
  EQUB LO(brRow_1_45)
  EQUB LO(brRow_1_46)
  EQUB LO(brRow_1_47)
  EQUB LO(brRow_1_48)
  EQUB LO(brRow_1_49)
  EQUB LO(brRow_1_50)
  EQUB LO(brRow_1_51)
  EQUB LO(brRow_1_52)
  EQUB LO(brRow_1_53)
  EQUB LO(brRow_1_54)
  EQUB LO(brRow_1_55)
  EQUB LO(brRow_1_56)
  EQUB LO(brRow_1_57)
.brRowHi_1
  EQUB HI(brRow_1_1)
  EQUB HI(brRow_1_2)
  EQUB HI(brRow_1_3)
  EQUB HI(brRow_1_4)
  EQUB HI(brRow_1_5)
  EQUB HI(brRow_1_6)
  EQUB HI(brRow_1_7)
  EQUB HI(brRow_1_8)
  EQUB HI(brRow_1_9)
  EQUB HI(brRow_1_10)
  EQUB HI(brRow_1_11)
  EQUB HI(brRow_1_12)
  EQUB HI(brRow_1_13)
  EQUB HI(brRow_1_14)
  EQUB HI(brRow_1_15)
  EQUB HI(brRow_1_16)
  EQUB HI(brRow_1_17)
  EQUB HI(brRow_1_18)
  EQUB HI(brRow_1_19)
  EQUB HI(brRow_1_20)
  EQUB HI(brRow_1_21)
  EQUB HI(brRow_1_22)
  EQUB HI(brRow_1_23)
  EQUB HI(brRow_1_24)
  EQUB HI(brRow_1_25)
  EQUB HI(brRow_1_26)
  EQUB HI(brRow_1_27)
  EQUB HI(brRow_1_28)
  EQUB HI(brRow_1_29)
  EQUB HI(brRow_1_30)
  EQUB HI(brRow_1_31)
  EQUB HI(brRow_1_32)
  EQUB HI(brRow_1_33)
  EQUB HI(brRow_1_34)
  EQUB HI(brRow_1_35)
  EQUB HI(brRow_1_36)
  EQUB HI(brRow_1_37)
  EQUB HI(brRow_1_38)
  EQUB HI(brRow_1_39)
  EQUB HI(brRow_1_40)
  EQUB HI(brRow_1_41)
  EQUB HI(brRow_1_42)
  EQUB HI(brRow_1_43)
  EQUB HI(brRow_1_44)
  EQUB HI(brRow_1_45)
  EQUB HI(brRow_1_46)
  EQUB HI(brRow_1_47)
  EQUB HI(brRow_1_48)
  EQUB HI(brRow_1_49)
  EQUB HI(brRow_1_50)
  EQUB HI(brRow_1_51)
  EQUB HI(brRow_1_52)
  EQUB HI(brRow_1_53)
  EQUB HI(brRow_1_54)
  EQUB HI(brRow_1_55)
  EQUB HI(brRow_1_56)
  EQUB HI(brRow_1_57)
.brRowLo_2
  EQUB LO(brRow_2_1)
  EQUB LO(brRow_2_2)
  EQUB LO(brRow_2_3)
  EQUB LO(brRow_2_4)
  EQUB LO(brRow_2_5)
  EQUB LO(brRow_2_6)
  EQUB LO(brRow_2_7)
  EQUB LO(brRow_2_8)
  EQUB LO(brRow_2_9)
  EQUB LO(brRow_2_10)
  EQUB LO(brRow_2_11)
  EQUB LO(brRow_2_12)
  EQUB LO(brRow_2_13)
  EQUB LO(brRow_2_14)
  EQUB LO(brRow_2_15)
  EQUB LO(brRow_2_16)
  EQUB LO(brRow_2_17)
  EQUB LO(brRow_2_18)
  EQUB LO(brRow_2_19)
  EQUB LO(brRow_2_20)
  EQUB LO(brRow_2_21)
  EQUB LO(brRow_2_22)
  EQUB LO(brRow_2_23)
  EQUB LO(brRow_2_24)
  EQUB LO(brRow_2_25)
  EQUB LO(brRow_2_26)
  EQUB LO(brRow_2_27)
  EQUB LO(brRow_2_28)
  EQUB LO(brRow_2_29)
  EQUB LO(brRow_2_30)
  EQUB LO(brRow_2_31)
  EQUB LO(brRow_2_32)
  EQUB LO(brRow_2_33)
  EQUB LO(brRow_2_34)
  EQUB LO(brRow_2_35)
  EQUB LO(brRow_2_36)
  EQUB LO(brRow_2_37)
  EQUB LO(brRow_2_38)
  EQUB LO(brRow_2_39)
  EQUB LO(brRow_2_40)
  EQUB LO(brRow_2_41)
  EQUB LO(brRow_2_42)
  EQUB LO(brRow_2_43)
  EQUB LO(brRow_2_44)
  EQUB LO(brRow_2_45)
  EQUB LO(brRow_2_46)
  EQUB LO(brRow_2_47)
  EQUB LO(brRow_2_48)
  EQUB LO(brRow_2_49)
  EQUB LO(brRow_2_50)
  EQUB LO(brRow_2_51)
  EQUB LO(brRow_2_52)
  EQUB LO(brRow_2_53)
  EQUB LO(brRow_2_54)
  EQUB LO(brRow_2_55)
  EQUB LO(brRow_2_56)
  EQUB LO(brRow_2_57)
.brRowHi_2
  EQUB HI(brRow_2_1)
  EQUB HI(brRow_2_2)
  EQUB HI(brRow_2_3)
  EQUB HI(brRow_2_4)
  EQUB HI(brRow_2_5)
  EQUB HI(brRow_2_6)
  EQUB HI(brRow_2_7)
  EQUB HI(brRow_2_8)
  EQUB HI(brRow_2_9)
  EQUB HI(brRow_2_10)
  EQUB HI(brRow_2_11)
  EQUB HI(brRow_2_12)
  EQUB HI(brRow_2_13)
  EQUB HI(brRow_2_14)
  EQUB HI(brRow_2_15)
  EQUB HI(brRow_2_16)
  EQUB HI(brRow_2_17)
  EQUB HI(brRow_2_18)
  EQUB HI(brRow_2_19)
  EQUB HI(brRow_2_20)
  EQUB HI(brRow_2_21)
  EQUB HI(brRow_2_22)
  EQUB HI(brRow_2_23)
  EQUB HI(brRow_2_24)
  EQUB HI(brRow_2_25)
  EQUB HI(brRow_2_26)
  EQUB HI(brRow_2_27)
  EQUB HI(brRow_2_28)
  EQUB HI(brRow_2_29)
  EQUB HI(brRow_2_30)
  EQUB HI(brRow_2_31)
  EQUB HI(brRow_2_32)
  EQUB HI(brRow_2_33)
  EQUB HI(brRow_2_34)
  EQUB HI(brRow_2_35)
  EQUB HI(brRow_2_36)
  EQUB HI(brRow_2_37)
  EQUB HI(brRow_2_38)
  EQUB HI(brRow_2_39)
  EQUB HI(brRow_2_40)
  EQUB HI(brRow_2_41)
  EQUB HI(brRow_2_42)
  EQUB HI(brRow_2_43)
  EQUB HI(brRow_2_44)
  EQUB HI(brRow_2_45)
  EQUB HI(brRow_2_46)
  EQUB HI(brRow_2_47)
  EQUB HI(brRow_2_48)
  EQUB HI(brRow_2_49)
  EQUB HI(brRow_2_50)
  EQUB HI(brRow_2_51)
  EQUB HI(brRow_2_52)
  EQUB HI(brRow_2_53)
  EQUB HI(brRow_2_54)
  EQUB HI(brRow_2_55)
  EQUB HI(brRow_2_56)
  EQUB HI(brRow_2_57)
.brRowLo_3
  EQUB LO(brRow_3_1)
  EQUB LO(brRow_3_2)
  EQUB LO(brRow_3_3)
  EQUB LO(brRow_3_4)
  EQUB LO(brRow_3_5)
  EQUB LO(brRow_3_6)
  EQUB LO(brRow_3_7)
  EQUB LO(brRow_3_8)
  EQUB LO(brRow_3_9)
  EQUB LO(brRow_3_10)
  EQUB LO(brRow_3_11)
  EQUB LO(brRow_3_12)
  EQUB LO(brRow_3_13)
  EQUB LO(brRow_3_14)
  EQUB LO(brRow_3_15)
  EQUB LO(brRow_3_16)
  EQUB LO(brRow_3_17)
  EQUB LO(brRow_3_18)
  EQUB LO(brRow_3_19)
  EQUB LO(brRow_3_20)
  EQUB LO(brRow_3_21)
  EQUB LO(brRow_3_22)
  EQUB LO(brRow_3_23)
  EQUB LO(brRow_3_24)
  EQUB LO(brRow_3_25)
  EQUB LO(brRow_3_26)
  EQUB LO(brRow_3_27)
  EQUB LO(brRow_3_28)
  EQUB LO(brRow_3_29)
  EQUB LO(brRow_3_30)
  EQUB LO(brRow_3_31)
  EQUB LO(brRow_3_32)
  EQUB LO(brRow_3_33)
  EQUB LO(brRow_3_34)
  EQUB LO(brRow_3_35)
  EQUB LO(brRow_3_36)
  EQUB LO(brRow_3_37)
  EQUB LO(brRow_3_38)
  EQUB LO(brRow_3_39)
  EQUB LO(brRow_3_40)
  EQUB LO(brRow_3_41)
  EQUB LO(brRow_3_42)
  EQUB LO(brRow_3_43)
  EQUB LO(brRow_3_44)
  EQUB LO(brRow_3_45)
  EQUB LO(brRow_3_46)
  EQUB LO(brRow_3_47)
  EQUB LO(brRow_3_48)
  EQUB LO(brRow_3_49)
  EQUB LO(brRow_3_50)
  EQUB LO(brRow_3_51)
  EQUB LO(brRow_3_52)
  EQUB LO(brRow_3_53)
  EQUB LO(brRow_3_54)
  EQUB LO(brRow_3_55)
  EQUB LO(brRow_3_56)
  EQUB LO(brRow_3_57)
.brRowHi_3
  EQUB HI(brRow_3_1)
  EQUB HI(brRow_3_2)
  EQUB HI(brRow_3_3)
  EQUB HI(brRow_3_4)
  EQUB HI(brRow_3_5)
  EQUB HI(brRow_3_6)
  EQUB HI(brRow_3_7)
  EQUB HI(brRow_3_8)
  EQUB HI(brRow_3_9)
  EQUB HI(brRow_3_10)
  EQUB HI(brRow_3_11)
  EQUB HI(brRow_3_12)
  EQUB HI(brRow_3_13)
  EQUB HI(brRow_3_14)
  EQUB HI(brRow_3_15)
  EQUB HI(brRow_3_16)
  EQUB HI(brRow_3_17)
  EQUB HI(brRow_3_18)
  EQUB HI(brRow_3_19)
  EQUB HI(brRow_3_20)
  EQUB HI(brRow_3_21)
  EQUB HI(brRow_3_22)
  EQUB HI(brRow_3_23)
  EQUB HI(brRow_3_24)
  EQUB HI(brRow_3_25)
  EQUB HI(brRow_3_26)
  EQUB HI(brRow_3_27)
  EQUB HI(brRow_3_28)
  EQUB HI(brRow_3_29)
  EQUB HI(brRow_3_30)
  EQUB HI(brRow_3_31)
  EQUB HI(brRow_3_32)
  EQUB HI(brRow_3_33)
  EQUB HI(brRow_3_34)
  EQUB HI(brRow_3_35)
  EQUB HI(brRow_3_36)
  EQUB HI(brRow_3_37)
  EQUB HI(brRow_3_38)
  EQUB HI(brRow_3_39)
  EQUB HI(brRow_3_40)
  EQUB HI(brRow_3_41)
  EQUB HI(brRow_3_42)
  EQUB HI(brRow_3_43)
  EQUB HI(brRow_3_44)
  EQUB HI(brRow_3_45)
  EQUB HI(brRow_3_46)
  EQUB HI(brRow_3_47)
  EQUB HI(brRow_3_48)
  EQUB HI(brRow_3_49)
  EQUB HI(brRow_3_50)
  EQUB HI(brRow_3_51)
  EQUB HI(brRow_3_52)
  EQUB HI(brRow_3_53)
  EQUB HI(brRow_3_54)
  EQUB HI(brRow_3_55)
  EQUB HI(brRow_3_56)
  EQUB HI(brRow_3_57)
.brRowLo_4
  EQUB LO(brRow_4_1)
  EQUB LO(brRow_4_2)
  EQUB LO(brRow_4_3)
  EQUB LO(brRow_4_4)
  EQUB LO(brRow_4_5)
  EQUB LO(brRow_4_6)
  EQUB LO(brRow_4_7)
  EQUB LO(brRow_4_8)
  EQUB LO(brRow_4_9)
  EQUB LO(brRow_4_10)
  EQUB LO(brRow_4_11)
  EQUB LO(brRow_4_12)
  EQUB LO(brRow_4_13)
  EQUB LO(brRow_4_14)
  EQUB LO(brRow_4_15)
  EQUB LO(brRow_4_16)
  EQUB LO(brRow_4_17)
  EQUB LO(brRow_4_18)
  EQUB LO(brRow_4_19)
  EQUB LO(brRow_4_20)
  EQUB LO(brRow_4_21)
  EQUB LO(brRow_4_22)
  EQUB LO(brRow_4_23)
  EQUB LO(brRow_4_24)
  EQUB LO(brRow_4_25)
  EQUB LO(brRow_4_26)
  EQUB LO(brRow_4_27)
  EQUB LO(brRow_4_28)
  EQUB LO(brRow_4_29)
  EQUB LO(brRow_4_30)
  EQUB LO(brRow_4_31)
  EQUB LO(brRow_4_32)
  EQUB LO(brRow_4_33)
  EQUB LO(brRow_4_34)
  EQUB LO(brRow_4_35)
  EQUB LO(brRow_4_36)
  EQUB LO(brRow_4_37)
  EQUB LO(brRow_4_38)
  EQUB LO(brRow_4_39)
  EQUB LO(brRow_4_40)
  EQUB LO(brRow_4_41)
  EQUB LO(brRow_4_42)
  EQUB LO(brRow_4_43)
  EQUB LO(brRow_4_44)
  EQUB LO(brRow_4_45)
  EQUB LO(brRow_4_46)
  EQUB LO(brRow_4_47)
  EQUB LO(brRow_4_48)
  EQUB LO(brRow_4_49)
  EQUB LO(brRow_4_50)
  EQUB LO(brRow_4_51)
  EQUB LO(brRow_4_52)
  EQUB LO(brRow_4_53)
  EQUB LO(brRow_4_54)
  EQUB LO(brRow_4_55)
  EQUB LO(brRow_4_56)
  EQUB LO(brRow_4_57)
.brRowHi_4
  EQUB HI(brRow_4_1)
  EQUB HI(brRow_4_2)
  EQUB HI(brRow_4_3)
  EQUB HI(brRow_4_4)
  EQUB HI(brRow_4_5)
  EQUB HI(brRow_4_6)
  EQUB HI(brRow_4_7)
  EQUB HI(brRow_4_8)
  EQUB HI(brRow_4_9)
  EQUB HI(brRow_4_10)
  EQUB HI(brRow_4_11)
  EQUB HI(brRow_4_12)
  EQUB HI(brRow_4_13)
  EQUB HI(brRow_4_14)
  EQUB HI(brRow_4_15)
  EQUB HI(brRow_4_16)
  EQUB HI(brRow_4_17)
  EQUB HI(brRow_4_18)
  EQUB HI(brRow_4_19)
  EQUB HI(brRow_4_20)
  EQUB HI(brRow_4_21)
  EQUB HI(brRow_4_22)
  EQUB HI(brRow_4_23)
  EQUB HI(brRow_4_24)
  EQUB HI(brRow_4_25)
  EQUB HI(brRow_4_26)
  EQUB HI(brRow_4_27)
  EQUB HI(brRow_4_28)
  EQUB HI(brRow_4_29)
  EQUB HI(brRow_4_30)
  EQUB HI(brRow_4_31)
  EQUB HI(brRow_4_32)
  EQUB HI(brRow_4_33)
  EQUB HI(brRow_4_34)
  EQUB HI(brRow_4_35)
  EQUB HI(brRow_4_36)
  EQUB HI(brRow_4_37)
  EQUB HI(brRow_4_38)
  EQUB HI(brRow_4_39)
  EQUB HI(brRow_4_40)
  EQUB HI(brRow_4_41)
  EQUB HI(brRow_4_42)
  EQUB HI(brRow_4_43)
  EQUB HI(brRow_4_44)
  EQUB HI(brRow_4_45)
  EQUB HI(brRow_4_46)
  EQUB HI(brRow_4_47)
  EQUB HI(brRow_4_48)
  EQUB HI(brRow_4_49)
  EQUB HI(brRow_4_50)
  EQUB HI(brRow_4_51)
  EQUB HI(brRow_4_52)
  EQUB HI(brRow_4_53)
  EQUB HI(brRow_4_54)
  EQUB HI(brRow_4_55)
  EQUB HI(brRow_4_56)
  EQUB HI(brRow_4_57)
.brPageLLo
  EQUB LO(brRowLo_0)
  EQUB LO(brRowLo_1)
  EQUB LO(brRowLo_2)
  EQUB LO(brRowLo_3)
  EQUB LO(brRowLo_4)
.brPageLHi
  EQUB HI(brRowLo_0)
  EQUB HI(brRowLo_1)
  EQUB HI(brRowLo_2)
  EQUB HI(brRowLo_3)
  EQUB HI(brRowLo_4)
.brPageHLo
  EQUB LO(brRowHi_0)
  EQUB LO(brRowHi_1)
  EQUB LO(brRowHi_2)
  EQUB LO(brRowHi_3)
  EQUB LO(brRowHi_4)
.brPageHHi
  EQUB HI(brRowHi_0)
  EQUB HI(brRowHi_1)
  EQUB HI(brRowHi_2)
  EQUB HI(brRowHi_3)
  EQUB HI(brRowHi_4)

.brRow_0_1
  \ "HEWSON"
  EQUB 14
  EQUB 18, 15, 33, 29, 25, 24
  EQUB &FE
  EQUB &FF
.brRow_0_2
  EQUB &FF
.brRow_0_3
  EQUB &FF
.brRow_0_4
  \ "presents"
  EQUB 16
  EQUB 78, 80, 67, 81, 67, 76, 82, 81
  EQUB &FE
  EQUB &FF
.brRow_0_5
  EQUB &FF
.brRow_0_6
  EQUB &FF
.brRow_0_7
  \ "Paradroid"
  EQUB 15
  EQUB 26, 63, 80, 63, 66, 80, 77, 71, 66
  EQUB &FE
  EQUB &FF
.brRow_0_8
  EQUB &FF
.brRow_0_9
  EQUB &FF
.brRow_0_10
  \ "Competition Edition"
  EQUB 9
  EQUB 13, 77, 75, 78, 67, 82, 71, 82, 71, 77, 76, 0
  EQUB 15, 66, 71, 82, 71, 77, 76
  EQUB &FE
  EQUB &FF
.brRow_0_11
  EQUB &FF
.brRow_0_12
  EQUB &FF
.brRow_0_13
  \ "@ Graftgold Ltd. 1986."
  EQUB 9
  EQUB 107, 0, 17, 80, 63, 68, 82, 69, 77, 74, 66, 0
  EQUB 22, 82, 66, 89, 0, 2, 10, 9, 7, 89
  EQUB &FE
  EQUB &FF
.brRow_0_14
  EQUB &FF
.brRow_0_15
  EQUB &FF
.brRow_0_16
  EQUB &FF
.brRow_0_17
  \ "BBC port by Bitshifters"
  EQUB 7
  EQUB 12, 12, 13, 0, 78, 77, 80, 82, 0, 64, 87, 0
  EQUB 12, 71, 82, 81, 70, 71, 68, 82, 67, 80, 81
  EQUB &FE
  EQUB &FF
.brRow_0_18
  EQUB &FF
.brRow_0_19
  EQUB &FF
.brRow_0_20
  EQUB &FF
.brRow_0_21
  \ "Clear  the freighter  of robots by"
  EQUB 3
  EQUB 13, 74, 67, 63, 80, 0, 0, 82, 70, 67, 0, 68
  EQUB 80, 67, 71, 69, 70, 82, 67, 80, 0, 0, 77, 68
  EQUB 0, 80, 77, 64, 77, 82, 81, 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_0_22
  EQUB &FF
.brRow_0_23
  \ "destroying them with twin  lasers"
  EQUB 2
  EQUB 66, 67, 81, 82, 80, 77, 87, 71, 76, 69, 0, 82
  EQUB 70, 67, 75, 0, 85, 71, 82, 70, 0, 82, 85, 71
  EQUB 76, 0, 0, 74, 63, 81, 67, 80, 81
  EQUB &FE
  EQUB &FF
.brRow_0_24
  EQUB &FF
.brRow_0_25
  \ "or by transferring control to them."
  EQUB 2
  EQUB 77, 80, 0, 64, 87, 0, 82, 80, 63, 76, 81, 68
  EQUB 67, 80, 80, 71, 76, 69, 0, 65, 77, 76, 82, 80
  EQUB 77, 74, 0, 82, 77, 0, 82, 70, 67, 75, 89
  EQUB &FE
  EQUB &FF
.brRow_0_26
  EQUB &FF
.brRow_0_27
  EQUB &FF
.brRow_0_28
  \ "Control is as follows:"
  EQUB 3
  EQUB 13, 77, 76, 82, 80, 77, 74, 0, 71, 81, 0, 63
  EQUB 81, 0, 68, 77, 74, 74, 77, 85, 81, 99
  EQUB &FE
  EQUB &FF
.brRow_0_29
  EQUB &FF
.brRow_0_30
  EQUB &FF
.brRow_0_31
  \ "Use keyboard to move your robot."
  EQUB 2
  EQUB 31, 81, 67, 0, 73, 67, 87, 64, 77, 63, 80, 66
  EQUB 0, 82, 77, 0, 75, 77, 84, 67, 0, 87, 77, 83
  EQUB 80, 0, 80, 77, 64, 77, 82, 89
  EQUB &FE
  EQUB &FF
.brRow_0_32
  EQUB &FF
.brRow_0_33
  \ "Press fire to shoot your laser and "
  EQUB 2
  EQUB 26, 80, 67, 81, 81, 0, 68, 71, 80, 67, 0, 82
  EQUB 77, 0, 81, 70, 77, 77, 82, 0, 87, 77, 83, 80
  EQUB 0, 74, 63, 81, 67, 80, 0, 63, 76, 66, 0
  EQUB &FE
  EQUB &FF
.brRow_0_34
  EQUB &FF
.brRow_0_35
  \ "use lifts or consoles. Hold fire "
  EQUB 2
  EQUB 83, 81, 67, 0, 74, 71, 68, 82, 81, 0, 77, 80
  EQUB 0, 65, 77, 76, 81, 77, 74, 67, 81, 89, 0, 18
  EQUB 77, 74, 66, 0, 68, 71, 80, 67, 0
  EQUB &FE
  EQUB &FF
.brRow_0_36
  EQUB &FF
.brRow_0_37
  \ "whilst stationary to prepare for "
  EQUB 2
  EQUB 85, 70, 71, 74, 81, 82, 0, 81, 82, 63, 82, 71
  EQUB 77, 76, 63, 80, 87, 0, 82, 77, 0, 78, 80, 67
  EQUB 78, 63, 80, 67, 0, 68, 77, 80, 0
  EQUB &FE
  EQUB &FF
.brRow_0_38
  EQUB &FF
.brRow_0_39
  \ "transfer mode or press transfer"
  EQUB 2
  EQUB 82, 80, 63, 76, 81, 68, 67, 80, 0, 75, 77, 66
  EQUB 67, 0, 77, 80, 0, 78, 80, 67, 81, 81, 0, 82
  EQUB 80, 63, 76, 81, 68, 67, 80
  EQUB &FE
  EQUB &FF
.brRow_0_40
  EQUB &FF
.brRow_0_41
  \ "button. Make contact with another"
  EQUB 2
  EQUB 64, 83, 82, 82, 77, 76, 89, 0, 23, 63, 73, 67
  EQUB 0, 65, 77, 76, 82, 63, 65, 82, 0, 85, 71, 82
  EQUB 70, 0, 63, 76, 77, 82, 70, 67, 80
  EQUB &FE
  EQUB &FF
.brRow_0_42
  EQUB &FF
.brRow_0_43
  \ "robot to initiate the transfer."
  EQUB 2
  EQUB 80, 77, 64, 77, 82, 0, 82, 77, 0, 71, 76, 71
  EQUB 82, 71, 63, 82, 67, 0, 82, 70, 67, 0, 82, 80
  EQUB 63, 76, 81, 68, 67, 80, 89
  EQUB &FE
  EQUB &FF
.brRow_0_44
  EQUB &FF
.brRow_0_45
  EQUB &FF
.brRow_0_46
  \ "Default keys:"
  EQUB 4
  EQUB 14, 67, 68, 63, 83, 74, 82, 0, 73, 67, 87, 81
  EQUB 99
  EQUB &FE
  EQUB &FF
.brRow_0_47
  EQUB &FF
.brRow_0_48
  EQUB &FF
.brRow_0_49
  \ "Left:        Z"
  EQUB 10
  EQUB 22, 67, 68, 82, 99, 0, 0, 0, 0, 0, 0, 0
  EQUB 0, 36
  EQUB &FE
  EQUB &FF
.brRow_0_50
  EQUB &FF
.brRow_0_51
  \ "Right:       X"
  EQUB 10
  EQUB 28, 71, 69, 70, 82, 99, 0, 0, 0, 0, 0, 0
  EQUB 0, 34
  EQUB &FE
  EQUB &FF
.brRow_0_52
  EQUB &FF
.brRow_0_53
  \ "Up:          K"
  EQUB 10
  EQUB 31, 78, 99, 0, 0, 0, 0, 0, 0, 0, 0, 0
  EQUB 0, 21
  EQUB &FE
  EQUB &FF
.brRow_0_54
  EQUB &FF
.brRow_0_55
  \ "Down:       M"
  EQUB 10
  EQUB 14, 77, 85, 76, 99, 0, 0, 0, 0, 0, 0, 0
  EQUB 23
  EQUB &FE
  EQUB &FF
.brRow_0_56
  EQUB &FF
.brRow_0_57
  \ "Fire:        L"
  EQUB 10
  EQUB 16, 71, 80, 67, 99, 0, 0, 0, 0, 0, 0, 0
  EQUB 0, 22
  EQUB &FE
  EQUB &FF
.brRow_1_1
  \ "A fleet  of  Robo-Freighters  on"
  EQUB 3
  EQUB 11, 0, 68, 74, 67, 67, 82, 0, 0, 77, 68, 0
  EQUB 0, 28, 77, 64, 77, 98, 16, 80, 67, 71, 69, 70
  EQUB 82, 67, 80, 81, 0, 0, 77, 76
  EQUB &FE
  EQUB &FF
.brRow_1_2
  EQUB &FF
.brRow_1_3
  \ "its way to the Beta Ceti  system"
  EQUB 2
  EQUB 71, 82, 81, 0, 85, 63, 87, 0, 82, 77, 0, 82
  EQUB 70, 67, 0, 12, 67, 82, 63, 0, 13, 67, 82, 71
  EQUB 0, 0, 81, 87, 81, 82, 67, 75
  EQUB &FE
  EQUB &FF
.brRow_1_4
  EQUB &FF
.brRow_1_5
  \ "reported entering an uncharted field"
  EQUB 2
  EQUB 80, 67, 78, 77, 80, 82, 67, 66, 0, 67, 76, 82
  EQUB 67, 80, 71, 76, 69, 0, 63, 76, 0, 83, 76, 65
  EQUB 70, 63, 80, 82, 67, 66, 0, 68, 71, 67, 74, 66
  EQUB &FE
  EQUB &FF
.brRow_1_6
  EQUB &FF
.brRow_1_7
  \ "of  asteroids. Each  ship carries a"
  EQUB 2
  EQUB 77, 68, 0, 0, 63, 81, 82, 67, 80, 77, 71, 66
  EQUB 81, 89, 0, 15, 63, 65, 70, 0, 0, 81, 70, 71
  EQUB 78, 0, 65, 63, 80, 80, 71, 67, 81, 0, 63
  EQUB &FE
  EQUB &FF
.brRow_1_8
  EQUB &FF
.brRow_1_9
  \ "cargo of battle droids to  reinforce"
  EQUB 2
  EQUB 65, 63, 80, 69, 77, 0, 77, 68, 0, 64, 63, 82
  EQUB 82, 74, 67, 0, 66, 80, 77, 71, 66, 81, 0, 82
  EQUB 77, 0, 0, 80, 67, 71, 76, 68, 77, 80, 65, 67
  EQUB &FE
  EQUB &FF
.brRow_1_10
  EQUB &FF
.brRow_1_11
  \ "the outworld defences."
  EQUB 2
  EQUB 82, 70, 67, 0, 77, 83, 82, 85, 77, 80, 74, 66
  EQUB 0, 66, 67, 68, 67, 76, 65, 67, 81, 89
  EQUB &FE
  EQUB &FF
.brRow_1_12
  EQUB &FF
.brRow_1_13
  \ "Two  distress beacons  have  been"
  EQUB 3
  EQUB 30, 85, 77, 0, 0, 66, 71, 81, 82, 80, 67, 81
  EQUB 81, 0, 64, 67, 63, 65, 77, 76, 81, 0, 0, 70
  EQUB 63, 84, 67, 0, 0, 64, 67, 67, 76
  EQUB &FE
  EQUB &FF
.brRow_1_14
  EQUB &FF
.brRow_1_15
  \ "recovered. Similar messages were"
  EQUB 2
  EQUB 80, 67, 65, 77, 84, 67, 80, 67, 66, 89, 0, 29
  EQUB 71, 75, 71, 74, 63, 80, 0, 75, 67, 81, 81, 63
  EQUB 69, 67, 81, 0, 85, 67, 80, 67
  EQUB &FE
  EQUB &FF
.brRow_1_16
  EQUB &FF
.brRow_1_17
  \ "stored on each. The ships had  been"
  EQUB 2
  EQUB 81, 82, 77, 80, 67, 66, 0, 77, 76, 0, 67, 63
  EQUB 65, 70, 89, 0, 30, 70, 67, 0, 81, 70, 71, 78
  EQUB 81, 0, 70, 63, 66, 0, 0, 64, 67, 67, 76
  EQUB &FE
  EQUB &FF
.brRow_1_18
  EQUB &FF
.brRow_1_19
  \ "bombarded by  a powerful  radionic"
  EQUB 2
  EQUB 64, 77, 75, 64, 63, 80, 66, 67, 66, 0, 64, 87
  EQUB 0, 0, 63, 0, 78, 77, 85, 67, 80, 68, 83, 74
  EQUB 0, 0, 80, 63, 66, 71, 77, 76, 71, 65
  EQUB &FE
  EQUB &FF
.brRow_1_20
  EQUB &FF
.brRow_1_21
  \ "beam from one of the asteroids."
  EQUB 2
  EQUB 64, 67, 63, 75, 0, 68, 80, 77, 75, 0, 77, 76
  EQUB 67, 0, 77, 68, 0, 82, 70, 67, 0, 63, 81, 82
  EQUB 67, 80, 77, 71, 66, 81, 89
  EQUB &FE
  EQUB &FF
.brRow_1_22
  EQUB &FF
.brRow_1_23
  \ "All  of the  robots on  the ships,"
  EQUB 3
  EQUB 11, 74, 74, 0, 0, 77, 68, 0, 82, 70, 67, 0
  EQUB 0, 80, 77, 64, 77, 82, 81, 0, 77, 76, 0, 0
  EQUB 82, 70, 67, 0, 81, 70, 71, 78, 81, 104
  EQUB &FE
  EQUB &FF
.brRow_1_24
  EQUB &FF
.brRow_1_25
  \ "including those in storage,  became"
  EQUB 2
  EQUB 71, 76, 65, 74, 83, 66, 71, 76, 69, 0, 82, 70
  EQUB 77, 81, 67, 0, 71, 76, 0, 81, 82, 77, 80, 63
  EQUB 69, 67, 104, 0, 0, 64, 67, 65, 63, 75, 67
  EQUB &FE
  EQUB &FF
.brRow_1_26
  EQUB &FF
.brRow_1_27
  \ "hyper-active. The crews report  an"
  EQUB 2
  EQUB 70, 87, 78, 67, 80, 98, 63, 65, 82, 71, 84, 67
  EQUB 89, 0, 30, 70, 67, 0, 65, 80, 67, 85, 81, 0
  EQUB 80, 67, 78, 77, 80, 82, 0, 0, 63, 76
  EQUB &FE
  EQUB &FF
.brRow_1_28
  EQUB &FF
.brRow_1_29
  \ "attack by droids, isolating them on"
  EQUB 2
  EQUB 63, 82, 82, 63, 65, 73, 0, 64, 87, 0, 66, 80
  EQUB 77, 71, 66, 81, 104, 0, 71, 81, 77, 74, 63, 82
  EQUB 71, 76, 69, 0, 82, 70, 67, 75, 0, 77, 76
  EQUB &FE
  EQUB &FF
.brRow_1_30
  EQUB &FF
.brRow_1_31
  \ "the bridge. They  cannot  reach the"
  EQUB 2
  EQUB 82, 70, 67, 0, 64, 80, 71, 66, 69, 67, 89, 0
  EQUB 30, 70, 67, 87, 0, 0, 65, 63, 76, 76, 77, 82
  EQUB 0, 0, 80, 67, 63, 65, 70, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_1_32
  EQUB &FF
.brRow_1_33
  \ "shuttle  and can hold out for only a"
  EQUB 2
  EQUB 81, 70, 83, 82, 82, 74, 67, 0, 0, 63, 76, 66
  EQUB 0, 65, 63, 76, 0, 70, 77, 74, 66, 0, 77, 83
  EQUB 82, 0, 68, 77, 80, 0, 77, 76, 74, 87, 0, 63
  EQUB &FE
  EQUB &FF
.brRow_1_34
  EQUB &FF
.brRow_1_35
  \ "couple more hours."
  EQUB 2
  EQUB 65, 77, 83, 78, 74, 67, 0, 75, 77, 80, 67, 0
  EQUB 70, 77, 83, 80, 81, 89
  EQUB &FE
  EQUB &FF
.brRow_1_36
  EQUB &FF
.brRow_1_37
  \ "Since these beacons were  located"
  EQUB 3
  EQUB 29, 71, 76, 65, 67, 0, 82, 70, 67, 81, 67, 0
  EQUB 64, 67, 63, 65, 77, 76, 81, 0, 85, 67, 80, 67
  EQUB 0, 0, 74, 77, 65, 63, 82, 67, 66
  EQUB &FE
  EQUB &FF
.brRow_1_38
  EQUB &FF
.brRow_1_39
  \ "two days ago, we can only fear the"
  EQUB 2
  EQUB 82, 85, 77, 0, 66, 63, 87, 81, 0, 63, 69, 77
  EQUB 104, 0, 85, 67, 0, 65, 63, 76, 0, 77, 76, 74
  EQUB 87, 0, 68, 67, 63, 80, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_1_40
  EQUB &FF
.brRow_1_41
  \ "worst."
  EQUB 2
  EQUB 85, 77, 80, 81, 82, 89
  EQUB &FE
  EQUB &FF
.brRow_1_42
  EQUB &FF
.brRow_1_43
  \ "Some of the  fleet was last seen"
  EQUB 3
  EQUB 29, 77, 75, 67, 0, 77, 68, 0, 82, 70, 67, 0
  EQUB 0, 68, 74, 67, 67, 82, 0, 85, 63, 81, 0, 74
  EQUB 63, 81, 82, 0, 81, 67, 67, 76
  EQUB &FE
  EQUB &FF
.brRow_1_44
  EQUB &FF
.brRow_1_45
  \ "heading for enemy space.  In enemy"
  EQUB 2
  EQUB 70, 67, 63, 66, 71, 76, 69, 0, 68, 77, 80, 0
  EQUB 67, 76, 67, 75, 87, 0, 81, 78, 63, 65, 67, 89
  EQUB 0, 0, 19, 76, 0, 67, 76, 67, 75, 87
  EQUB &FE
  EQUB &FF
.brRow_1_46
  EQUB &FF
.brRow_1_47
  \ "hands the droids can be used against"
  EQUB 2
  EQUB 70, 63, 76, 66, 81, 0, 82, 70, 67, 0, 66, 80
  EQUB 77, 71, 66, 81, 0, 65, 63, 76, 0, 64, 67, 0
  EQUB 83, 81, 67, 66, 0, 63, 69, 63, 71, 76, 81, 82
  EQUB &FE
  EQUB &FF
.brRow_1_48
  EQUB &FF
.brRow_1_49
  \ "our forces."
  EQUB 2
  EQUB 77, 83, 80, 0, 68, 77, 80, 65, 67, 81, 89
  EQUB &FE
  EQUB &FF
.brRow_1_50
  EQUB &FF
.brRow_1_51
  \ "Docking would  be impossible but"
  EQUB 3
  EQUB 14, 77, 65, 73, 71, 76, 69, 0, 85, 77, 83, 74
  EQUB 66, 0, 0, 64, 67, 0, 71, 75, 78, 77, 81, 81
  EQUB 71, 64, 74, 67, 0, 64, 83, 82
  EQUB &FE
  EQUB &FF
.brRow_1_52
  EQUB &FF
.brRow_1_53
  \ "we  can beam  aboard  a  prototype"
  EQUB 2
  EQUB 85, 67, 0, 0, 65, 63, 76, 0, 64, 67, 63, 75
  EQUB 0, 0, 63, 64, 77, 63, 80, 66, 0, 0, 63, 0
  EQUB 0, 78, 80, 77, 82, 77, 82, 87, 78, 67
  EQUB &FE
  EQUB &FF
.brRow_1_54
  EQUB &FF
.brRow_1_55
  \ "Influence Device."
  EQUB 2
  EQUB 19, 76, 68, 74, 83, 67, 76, 65, 67, 0, 14, 67
  EQUB 84, 71, 65, 67, 89
  EQUB &FE
  EQUB &FF
.brRow_1_56
  EQUB &FF
.brRow_1_57
  EQUB &FF
.brRow_2_1
  \ "The 001 Influence Device consists"
  EQUB 3
  EQUB 30, 70, 67, 0, 1, 1, 2, 0, 19, 76, 68, 74
  EQUB 83, 67, 76, 65, 67, 0, 14, 67, 84, 71, 65, 67
  EQUB 0, 65, 77, 76, 81, 71, 81, 82, 81
  EQUB &FE
  EQUB &FF
.brRow_2_2
  EQUB &FF
.brRow_2_3
  \ "of a  helmet, which, when  placed"
  EQUB 2
  EQUB 77, 68, 0, 63, 0, 0, 70, 67, 74, 75, 67, 82
  EQUB 104, 0, 85, 70, 71, 65, 70, 104, 0, 85, 70, 67
  EQUB 76, 0, 0, 78, 74, 63, 65, 67, 66
  EQUB &FE
  EQUB &FF
.brRow_2_4
  EQUB &FF
.brRow_2_5
  \ "over a robot's control unit can halt"
  EQUB 2
  EQUB 77, 84, 67, 80, 0, 63, 0, 80, 77, 64, 77, 82
  EQUB 105, 81, 0, 65, 77, 76, 82, 80, 77, 74, 0, 83
  EQUB 76, 71, 82, 0, 65, 63, 76, 0, 70, 63, 74, 82
  EQUB &FE
  EQUB &FF
.brRow_2_6
  EQUB &FF
.brRow_2_7
  \ "the normal activities of that robot"
  EQUB 2
  EQUB 82, 70, 67, 0, 76, 77, 80, 75, 63, 74, 0, 63
  EQUB 65, 82, 71, 84, 71, 82, 71, 67, 81, 0, 77, 68
  EQUB 0, 82, 70, 63, 82, 0, 80, 77, 64, 77, 82
  EQUB &FE
  EQUB &FF
.brRow_2_8
  EQUB &FF
.brRow_2_9
  \ "for a short time. The helmet  has"
  EQUB 2
  EQUB 68, 77, 80, 0, 63, 0, 81, 70, 77, 80, 82, 0
  EQUB 82, 71, 75, 67, 89, 0, 30, 70, 67, 0, 70, 67
  EQUB 74, 75, 67, 82, 0, 0, 70, 63, 81
  EQUB &FE
  EQUB &FF
.brRow_2_10
  EQUB &FF
.brRow_2_11
  \ "its  own energy supply  and powers"
  EQUB 2
  EQUB 71, 82, 81, 0, 0, 77, 85, 76, 0, 67, 76, 67
  EQUB 80, 69, 87, 0, 81, 83, 78, 78, 74, 87, 0, 0
  EQUB 63, 76, 66, 0, 78, 77, 85, 67, 80, 81
  EQUB &FE
  EQUB &FF
.brRow_2_12
  EQUB &FF
.brRow_2_13
  \ "the  robot itself,  at  an  upgraded"
  EQUB 2
  EQUB 82, 70, 67, 0, 0, 80, 77, 64, 77, 82, 0, 71
  EQUB 82, 81, 67, 74, 68, 104, 0, 0, 63, 82, 0, 0
  EQUB 63, 76, 0, 0, 83, 78, 69, 80, 63, 66, 67, 66
  EQUB &FE
  EQUB &FF
.brRow_2_14
  EQUB &FF
.brRow_2_15
  \ "capability. The  helmet also  uses"
  EQUB 2
  EQUB 65, 63, 78, 63, 64, 71, 74, 71, 82, 87, 89, 0
  EQUB 30, 70, 67, 0, 0, 70, 67, 74, 75, 67, 82, 0
  EQUB 63, 74, 81, 77, 0, 0, 83, 81, 67, 81
  EQUB &FE
  EQUB &FF
.brRow_2_16
  EQUB &FF
.brRow_2_17
  \ "an energy  cloak for  protection  of"
  EQUB 2
  EQUB 63, 76, 0, 67, 76, 67, 80, 69, 87, 0, 0, 65
  EQUB 74, 77, 63, 73, 0, 68, 77, 80, 0, 0, 78, 80
  EQUB 77, 82, 67, 65, 82, 71, 77, 76, 0, 0, 77, 68
  EQUB &FE
  EQUB &FF
.brRow_2_18
  EQUB &FF
.brRow_2_19
  \ "the host."
  EQUB 2
  EQUB 82, 70, 67, 0, 70, 77, 81, 82, 89
  EQUB &FE
  EQUB &FF
.brRow_2_20
  EQUB &FF
.brRow_2_21
  \ "The helmet is  fitted with twin"
  EQUB 3
  EQUB 30, 70, 67, 0, 70, 67, 74, 75, 67, 82, 0, 71
  EQUB 81, 0, 0, 68, 71, 82, 82, 67, 66, 0, 85, 71
  EQUB 82, 70, 0, 82, 85, 71, 76
  EQUB &FE
  EQUB &FF
.brRow_2_22
  EQUB &FF
.brRow_2_23
  \ "lasers mounted  in a turret. These"
  EQUB 2
  EQUB 74, 63, 81, 67, 80, 81, 0, 75, 77, 83, 76, 82
  EQUB 67, 66, 0, 0, 71, 76, 0, 63, 0, 82, 83, 80
  EQUB 80, 67, 82, 89, 0, 30, 70, 67, 81, 67
  EQUB &FE
  EQUB &FF
.brRow_2_24
  EQUB &FF
.brRow_2_25
  \ "are low powered  and have  a slow"
  EQUB 2
  EQUB 63, 80, 67, 0, 74, 77, 85, 0, 78, 77, 85, 67
  EQUB 80, 67, 66, 0, 0, 63, 76, 66, 0, 70, 63, 84
  EQUB 67, 0, 0, 63, 0, 81, 74, 77, 85
  EQUB &FE
  EQUB &FF
.brRow_2_26
  EQUB &FF
.brRow_2_27
  \ "recycle rate."
  EQUB 2
  EQUB 80, 67, 65, 87, 65, 74, 67, 0, 80, 63, 82, 67
  EQUB 89
  EQUB &FE
  EQUB &FF
.brRow_2_28
  EQUB &FF
.brRow_2_29
  \ "Most of the device's resources are"
  EQUB 3
  EQUB 23, 77, 81, 82, 0, 77, 68, 0, 82, 70, 67, 0
  EQUB 66, 67, 84, 71, 65, 67, 105, 81, 0, 80, 67, 81
  EQUB 77, 83, 80, 65, 67, 81, 0, 63, 80, 67
  EQUB &FE
  EQUB &FF
.brRow_2_30
  EQUB &FF
.brRow_2_31
  \ "channelled towards holding  control"
  EQUB 2
  EQUB 65, 70, 63, 76, 76, 67, 74, 74, 67, 66, 0, 82
  EQUB 77, 85, 63, 80, 66, 81, 0, 70, 77, 74, 66, 71
  EQUB 76, 69, 0, 0, 65, 77, 76, 82, 80, 77, 74
  EQUB &FE
  EQUB &FF
.brRow_2_32
  EQUB &FF
.brRow_2_33
  \ "of the host  robot, as it  attempts"
  EQUB 2
  EQUB 77, 68, 0, 82, 70, 67, 0, 70, 77, 81, 82, 0
  EQUB 0, 80, 77, 64, 77, 82, 104, 0, 63, 81, 0, 71
  EQUB 82, 0, 0, 63, 82, 82, 67, 75, 78, 82, 81
  EQUB &FE
  EQUB &FF
.brRow_2_34
  EQUB &FF
.brRow_2_35
  \ "to resume 'normal' operation."
  EQUB 2
  EQUB 82, 77, 0, 80, 67, 81, 83, 75, 67, 0, 105, 76
  EQUB 77, 80, 75, 63, 74, 105, 0, 77, 78, 67, 80, 63
  EQUB 82, 71, 77, 76, 89
  EQUB &FE
  EQUB &FF
.brRow_2_36
  EQUB &FF
.brRow_2_37
  \ "It is therefore necessary to change"
  EQUB 3
  EQUB 19, 82, 0, 71, 81, 0, 82, 70, 67, 80, 67, 68
  EQUB 77, 80, 67, 0, 76, 67, 65, 67, 81, 81, 63, 80
  EQUB 87, 0, 82, 77, 0, 65, 70, 63, 76, 69, 67
  EQUB &FE
  EQUB &FF
.brRow_2_38
  EQUB &FF
.brRow_2_39
  \ "the host robot often  to prevent the"
  EQUB 2
  EQUB 82, 70, 67, 0, 70, 77, 81, 82, 0, 80, 77, 64
  EQUB 77, 82, 0, 77, 68, 82, 67, 76, 0, 0, 82, 77
  EQUB 0, 78, 80, 67, 84, 67, 76, 82, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_2_40
  EQUB &FF
.brRow_2_41
  \ "device  from burning out. Transfer"
  EQUB 2
  EQUB 66, 67, 84, 71, 65, 67, 0, 0, 68, 80, 77, 75
  EQUB 0, 64, 83, 80, 76, 71, 76, 69, 0, 77, 83, 82
  EQUB 89, 0, 30, 80, 63, 76, 81, 68, 67, 80
  EQUB &FE
  EQUB &FF
.brRow_2_42
  EQUB &FF
.brRow_2_43
  \ "to a new robot  requires the device"
  EQUB 2
  EQUB 82, 77, 0, 63, 0, 76, 67, 85, 0, 80, 77, 64
  EQUB 77, 82, 0, 0, 80, 67, 79, 83, 71, 80, 67, 81
  EQUB 0, 82, 70, 67, 0, 66, 67, 84, 71, 65, 67
  EQUB &FE
  EQUB &FF
.brRow_2_44
  EQUB &FF
.brRow_2_45
  \ "to drain its host of energy in order"
  EQUB 2
  EQUB 82, 77, 0, 66, 80, 63, 71, 76, 0, 71, 82, 81
  EQUB 0, 70, 77, 81, 82, 0, 77, 68, 0, 67, 76, 67
  EQUB 80, 69, 87, 0, 71, 76, 0, 77, 80, 66, 67, 80
  EQUB &FE
  EQUB &FF
.brRow_2_46
  EQUB &FF
.brRow_2_47
  \ "to take it over. Failure to achieve"
  EQUB 2
  EQUB 82, 77, 0, 82, 63, 73, 67, 0, 71, 82, 0, 77
  EQUB 84, 67, 80, 89, 0, 16, 63, 71, 74, 83, 80, 67
  EQUB 0, 82, 77, 0, 63, 65, 70, 71, 67, 84, 67
  EQUB &FE
  EQUB &FF
.brRow_2_48
  EQUB &FF
.brRow_2_49
  \ "transfer results in the device being"
  EQUB 2
  EQUB 82, 80, 63, 76, 81, 68, 67, 80, 0, 80, 67, 81
  EQUB 83, 74, 82, 81, 0, 71, 76, 0, 82, 70, 67, 0
  EQUB 66, 67, 84, 71, 65, 67, 0, 64, 67, 71, 76, 69
  EQUB &FE
  EQUB &FF
.brRow_2_50
  EQUB &FF
.brRow_2_51
  \ "a free agent once more."
  EQUB 2
  EQUB 63, 0, 68, 80, 67, 67, 0, 63, 69, 67, 76, 82
  EQUB 0, 77, 76, 65, 67, 0, 75, 77, 80, 67, 89
  EQUB &FE
  EQUB &FF
.brRow_2_52
  EQUB &FF
.brRow_2_53
  EQUB &FF
.brRow_2_54
  EQUB &FF
.brRow_2_55
  \ "Press fire to play"
  EQUB 10
  EQUB 26, 80, 67, 81, 81, 0, 68, 71, 80, 67, 0, 82
  EQUB 77, 0, 78, 74, 63, 87
  EQUB &FE
  EQUB &FF
.brRow_2_56
  EQUB &FF
.brRow_2_57
  EQUB &FF
.brRow_3_1
  \ "An Influence Device can transmit"
  EQUB 3
  EQUB 11, 76, 0, 19, 76, 68, 74, 83, 67, 76, 65, 67
  EQUB 0, 14, 67, 84, 71, 65, 67, 0, 65, 63, 76, 0
  EQUB 82, 80, 63, 76, 81, 75, 71, 82
  EQUB &FE
  EQUB &FF
.brRow_3_2
  EQUB &FF
.brRow_3_3
  \ "only certain data, namely its  own"
  EQUB 2
  EQUB 77, 76, 74, 87, 0, 65, 67, 80, 82, 63, 71, 76
  EQUB 0, 66, 63, 82, 63, 104, 0, 76, 63, 75, 67, 74
  EQUB 87, 0, 71, 82, 81, 0, 0, 77, 85, 76
  EQUB &FE
  EQUB &FF
.brRow_3_4
  EQUB &FF
.brRow_3_5
  \ "location  and the  location of other"
  EQUB 2
  EQUB 74, 77, 65, 63, 82, 71, 77, 76, 0, 0, 63, 76
  EQUB 66, 0, 82, 70, 67, 0, 0, 74, 77, 65, 63, 82
  EQUB 71, 77, 76, 0, 77, 68, 0, 77, 82, 70, 67, 80
  EQUB &FE
  EQUB &FF
.brRow_3_6
  EQUB &FF
.brRow_3_7
  \ "robots in visual range.This data is"
  EQUB 2
  EQUB 80, 77, 64, 77, 82, 81, 0, 71, 76, 0, 84, 71
  EQUB 81, 83, 63, 74, 0, 80, 63, 76, 69, 67, 89, 30
  EQUB 70, 71, 81, 0, 66, 63, 82, 63, 0, 71, 81
  EQUB &FE
  EQUB &FF
.brRow_3_8
  EQUB &FF
.brRow_3_9
  \ "merged with known ship layouts at"
  EQUB 2
  EQUB 75, 67, 80, 69, 67, 66, 0, 85, 71, 82, 70, 0
  EQUB 73, 76, 77, 85, 76, 0, 81, 70, 71, 78, 0, 74
  EQUB 63, 87, 77, 83, 82, 81, 0, 63, 82
  EQUB &FE
  EQUB &FF
.brRow_3_10
  EQUB &FF
.brRow_3_11
  \ "your BBC remote terminal."
  EQUB 2
  EQUB 87, 77, 83, 80, 0, 12, 12, 13, 0, 80, 67, 75
  EQUB 77, 82, 67, 0, 82, 67, 80, 75, 71, 76, 63, 74
  EQUB 89
  EQUB &FE
  EQUB &FF
.brRow_3_12
  EQUB &FF
.brRow_3_13
  \ "Additional information  about the"
  EQUB 3
  EQUB 11, 66, 66, 71, 82, 71, 77, 76, 63, 74, 0, 71
  EQUB 76, 68, 77, 80, 75, 63, 82, 71, 77, 76, 0, 0
  EQUB 63, 64, 77, 83, 82, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_3_14
  EQUB &FF
.brRow_3_15
  \ "ship and robots may be obtained  by"
  EQUB 2
  EQUB 81, 70, 71, 78, 0, 63, 76, 66, 0, 80, 77, 64
  EQUB 77, 82, 81, 0, 75, 63, 87, 0, 64, 67, 0, 77
  EQUB 64, 82, 63, 71, 76, 67, 66, 0, 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_3_16
  EQUB &FF
.brRow_3_17
  \ "accessing the  ship's computer at a"
  EQUB 2
  EQUB 63, 65, 65, 67, 81, 81, 71, 76, 69, 0, 82, 70
  EQUB 67, 0, 0, 81, 70, 71, 78, 105, 81, 0, 65, 77
  EQUB 75, 78, 83, 82, 67, 80, 0, 63, 82, 0, 63
  EQUB &FE
  EQUB &FF
.brRow_3_18
  EQUB &FF
.brRow_3_19
  \ "console. A small-scale plan of the"
  EQUB 2
  EQUB 65, 77, 76, 81, 77, 74, 67, 89, 0, 11, 0, 81
  EQUB 75, 63, 74, 74, 98, 81, 65, 63, 74, 67, 0, 78
  EQUB 74, 63, 76, 0, 77, 68, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_3_20
  EQUB &FF
.brRow_3_21
  \ "whole deck  is available, as  well"
  EQUB 2
  EQUB 85, 70, 77, 74, 67, 0, 66, 67, 65, 73, 0, 0
  EQUB 71, 81, 0, 63, 84, 63, 71, 74, 63, 64, 74, 67
  EQUB 104, 0, 63, 81, 0, 0, 85, 67, 74, 74
  EQUB &FE
  EQUB &FF
.brRow_3_22
  EQUB &FF
.brRow_3_23
  \ "as a side elevation of the ship."
  EQUB 2
  EQUB 63, 81, 0, 63, 0, 81, 71, 66, 67, 0, 67, 74
  EQUB 67, 84, 63, 82, 71, 77, 76, 0, 77, 68, 0, 82
  EQUB 70, 67, 0, 81, 70, 71, 78, 89
  EQUB &FE
  EQUB &FF
.brRow_3_24
  EQUB &FF
.brRow_3_25
  \ "Robots are  represented  on-screen"
  EQUB 3
  EQUB 28, 77, 64, 77, 82, 81, 0, 63, 80, 67, 0, 0
  EQUB 80, 67, 78, 80, 67, 81, 67, 76, 82, 67, 66, 0
  EQUB 0, 77, 76, 98, 81, 65, 80, 67, 67, 76
  EQUB &FE
  EQUB &FF
.brRow_3_26
  EQUB &FF
.brRow_3_27
  \ "as a symbol  showing a three-digit"
  EQUB 2
  EQUB 63, 81, 0, 63, 0, 81, 87, 75, 64, 77, 74, 0
  EQUB 0, 81, 70, 77, 85, 71, 76, 69, 0, 63, 0, 82
  EQUB 70, 80, 67, 67, 98, 66, 71, 69, 71, 82
  EQUB &FE
  EQUB &FF
.brRow_3_28
  EQUB &FF
.brRow_3_29
  \ "number. The first digit shown  is"
  EQUB 2
  EQUB 76, 83, 75, 64, 67, 80, 89, 0, 30, 70, 67, 0
  EQUB 68, 71, 80, 81, 82, 0, 66, 71, 69, 71, 82, 0
  EQUB 81, 70, 77, 85, 76, 0, 0, 71, 81
  EQUB &FE
  EQUB &FF
.brRow_3_30
  EQUB &FF
.brRow_3_31
  \ "the important one, the class of the"
  EQUB 2
  EQUB 82, 70, 67, 0, 71, 75, 78, 77, 80, 82, 63, 76
  EQUB 82, 0, 77, 76, 67, 104, 0, 82, 70, 67, 0, 65
  EQUB 74, 63, 81, 81, 0, 77, 68, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_3_32
  EQUB &FF
.brRow_3_33
  \ "robot. It denotes the strength also."
  EQUB 2
  EQUB 80, 77, 64, 77, 82, 89, 0, 19, 82, 0, 66, 67
  EQUB 76, 77, 82, 67, 81, 0, 82, 70, 67, 0, 81, 82
  EQUB 80, 67, 76, 69, 82, 70, 0, 63, 74, 81, 77, 89
  EQUB &FE
  EQUB &FF
.brRow_3_34
  EQUB &FF
.brRow_3_35
  \ "To find out more  about any  given"
  EQUB 2
  EQUB 30, 77, 0, 68, 71, 76, 66, 0, 77, 83, 82, 0
  EQUB 75, 77, 80, 67, 0, 0, 63, 64, 77, 83, 82, 0
  EQUB 63, 76, 87, 0, 0, 69, 71, 84, 67, 76
  EQUB &FE
  EQUB &FF
.brRow_3_36
  EQUB &FF
.brRow_3_37
  \ "robot, use the robot enquiry system"
  EQUB 2
  EQUB 80, 77, 64, 77, 82, 104, 0, 83, 81, 67, 0, 82
  EQUB 70, 67, 0, 80, 77, 64, 77, 82, 0, 67, 76, 79
  EQUB 83, 71, 80, 87, 0, 81, 87, 81, 82, 67, 75
  EQUB &FE
  EQUB &FF
.brRow_3_38
  EQUB &FF
.brRow_3_39
  \ "at a console. Only data about units"
  EQUB 2
  EQUB 63, 82, 0, 63, 0, 65, 77, 76, 81, 77, 74, 67
  EQUB 89, 0, 25, 76, 74, 87, 0, 66, 63, 82, 63, 0
  EQUB 63, 64, 77, 83, 82, 0, 83, 76, 71, 82, 81
  EQUB &FE
  EQUB &FF
.brRow_3_40
  EQUB &FF
.brRow_3_41
  \ "of a lower class  than your current"
  EQUB 2
  EQUB 77, 68, 0, 63, 0, 74, 77, 85, 67, 80, 0, 65
  EQUB 74, 63, 81, 81, 0, 0, 82, 70, 63, 76, 0, 87
  EQUB 77, 83, 80, 0, 65, 83, 80, 80, 67, 76, 82
  EQUB &FE
  EQUB &FF
.brRow_3_42
  EQUB &FF
.brRow_3_43
  \ "host is available, since  it is  the"
  EQUB 2
  EQUB 70, 77, 81, 82, 0, 71, 81, 0, 63, 84, 63, 71
  EQUB 74, 63, 64, 74, 67, 104, 0, 81, 71, 76, 65, 67
  EQUB 0, 0, 71, 82, 0, 71, 81, 0, 0, 82, 70, 67
  EQUB &FE
  EQUB &FF
.brRow_3_44
  EQUB &FF
.brRow_3_45
  \ "host's security clearance  which is"
  EQUB 2
  EQUB 70, 77, 81, 82, 105, 81, 0, 81, 67, 65, 83, 80
  EQUB 71, 82, 87, 0, 65, 74, 67, 63, 80, 63, 76, 65
  EQUB 67, 0, 0, 85, 70, 71, 65, 70, 0, 71, 81
  EQUB &FE
  EQUB &FF
.brRow_3_46
  EQUB &FF
.brRow_3_47
  \ "used to access the console."
  EQUB 2
  EQUB 83, 81, 67, 66, 0, 82, 77, 0, 63, 65, 65, 67
  EQUB 81, 81, 0, 82, 70, 67, 0, 65, 77, 76, 81, 77
  EQUB 74, 67, 89
  EQUB &FE
  EQUB &FF
.brRow_3_48
  EQUB &FF
.brRow_3_49
  EQUB &FF
.brRow_3_50
  EQUB &FF
.brRow_3_51
  EQUB &FF
.brRow_3_52
  EQUB &FF
.brRow_3_53
  EQUB &FF
.brRow_3_54
  EQUB &FF
.brRow_3_55
  \ "Press fire to play"
  EQUB 10
  EQUB 26, 80, 67, 81, 81, 0, 68, 71, 80, 67, 0, 82
  EQUB 77, 0, 78, 74, 63, 87
  EQUB &FE
  EQUB &FF
.brRow_3_56
  EQUB &FF
.brRow_3_57
  EQUB &FF
.brRow_4_1
  \ "Top score of the day:"
  EQUB 13
  EQUB 30, 77, 78, 0, 81, 65, 77, 80, 67, 0, 77, 68
  EQUB 0, 82, 70, 67, 0, 66, 63, 87, 99
  EQUB &FE
  EQUB &FF
.brRow_4_2
  EQUB &FF
.brRow_4_3
  EQUB &FF
.brRow_4_4
.br_hiscore
  \ "    6809 - AEB"
  EQUB 15
  EQUB 0, 0, 0, 0, 7, 9, 1, 10, 0, 98, 0, 11
  EQUB 15, 12
  EQUB &FE
  EQUB &FF
.brRow_4_5
  EQUB &FF
.brRow_4_6
  EQUB &FF
.brRow_4_7
  EQUB &FF
.brRow_4_8
  EQUB &FF
.brRow_4_9
  \ "Worst score of the day:"
  EQUB 12
  EQUB 33, 77, 80, 81, 82, 0, 81, 65, 77, 80, 67, 0
  EQUB 77, 68, 0, 82, 70, 67, 0, 66, 63, 87, 99
  EQUB &FE
  EQUB &FF
.brRow_4_10
  EQUB &FF
.brRow_4_11
  EQUB &FF
.brRow_4_12
.br_loscore
  \ "    6502 - BBC"
  EQUB 15
  EQUB 0, 0, 0, 0, 7, 6, 1, 3, 0, 98, 0, 12
  EQUB 12, 13
  EQUB &FE
  EQUB &FF
.brRow_4_13
  EQUB &FF
.brRow_4_14
  EQUB &FF
.brRow_4_15
  EQUB &FF
.brRow_4_16
  EQUB &FF
.brRow_4_17
  \ "To pause:      Ctrl-P"
  EQUB 6
  EQUB 30, 77, 0, 78, 63, 83, 81, 67, 99, 0, 0, 0
  EQUB 0, 0, 0, 13, 82, 80, 74, 98, 26
  EQUB &FE
  EQUB &FF
.brRow_4_18
  EQUB &FF
.brRow_4_19
  \ "Mute sound:    Ctrl-Q"
  EQUB 6
  EQUB 23, 83, 82, 67, 0, 81, 77, 83, 76, 66, 99, 0
  EQUB 0, 0, 0, 13, 82, 80, 74, 98, 27
  EQUB &FE
  EQUB &FF
.brRow_4_20
  EQUB &FF
.brRow_4_21
  \ "Volume up:    Ctrl-Up"
  EQUB 6
  EQUB 32, 77, 74, 83, 75, 67, 0, 83, 78, 99, 0, 0
  EQUB 0, 0, 13, 82, 80, 74, 98, 31, 78
  EQUB &FE
  EQUB &FF
.brRow_4_22
  EQUB &FF
.brRow_4_23
  \ "Volume down: Ctrl-Down"
  EQUB 6
  EQUB 32, 77, 74, 83, 75, 67, 0, 66, 77, 85, 76, 99
  EQUB 0, 13, 82, 80, 74, 98, 14, 77, 85, 76
  EQUB &FE
  EQUB &FF
.brRow_4_24
  EQUB &FF
.brRow_4_25
  \ "Quit game:    Escape"
  EQUB 6
  EQUB 27, 83, 71, 82, 0, 69, 63, 75, 67, 99, 0, 0
  EQUB 0, 0, 15, 81, 65, 63, 78, 67
  EQUB &FE
  EQUB &FF
.brRow_4_26
  EQUB &FF
.brRow_4_27
  EQUB &FF
.brRow_4_28
  EQUB &FF
.brRow_4_29
  \ "During briefing only:"
  EQUB 4
  EQUB 14, 83, 80, 71, 76, 69, 0, 64, 80, 71, 67, 68
  EQUB 71, 76, 69, 0, 77, 76, 74, 87, 99
  EQUB &FE
  EQUB &FF
.brRow_4_30
  EQUB &FF
.brRow_4_31
  EQUB &FF
.brRow_4_32
  \ "Redefine keys: Ctrl-R"
  EQUB 6
  EQUB 28, 67, 66, 67, 68, 71, 76, 67, 0, 73, 67, 87
  EQUB 81, 99, 0, 13, 82, 80, 74, 98, 28
  EQUB &FE
  EQUB &FF
.brRow_4_33
  EQUB &FF
.brRow_4_34
  EQUB &FF
.brRow_4_35
  EQUB &FF
.brRow_4_36
  EQUB &FF
.brRow_4_37
  \ "Paradroid-90 music by"
  EQUB 11
  EQUB 26, 63, 80, 63, 66, 80, 77, 71, 66, 98, 10, 1
  EQUB 0, 75, 83, 81, 71, 65, 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_4_38
  EQUB &FF
.brRow_4_39
  \ "Jason Page."
  EQUB 16
  EQUB 20, 63, 81, 77, 76, 0, 26, 63, 69, 67, 89
  EQUB &FE
  EQUB &FF
.brRow_4_40
  EQUB &FF
.brRow_4_41
  \ "Converted to the BBC by"
  EQUB 11
  EQUB 13, 77, 76, 84, 67, 80, 82, 67, 66, 0, 82, 77
  EQUB 0, 82, 70, 67, 0, 12, 12, 13, 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_4_42
  EQUB &FF
.brRow_4_43
  \ "scarybeasts."
  EQUB 16
  EQUB 81, 65, 63, 80, 87, 64, 67, 63, 81, 82, 81, 89
  EQUB &FE
  EQUB &FF
.brRow_4_44
  EQUB &FF
.brRow_4_45
  EQUB &FF
.brRow_4_46
  EQUB &FF
.brRow_4_47
  \ "Paradroid programmed by"
  EQUB 11
  EQUB 26, 63, 80, 63, 66, 80, 77, 71, 66, 0, 78, 80
  EQUB 77, 69, 80, 63, 75, 75, 67, 66, 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_4_48
  EQUB &FF
.brRow_4_49
  \ "Andrew Braybrook."
  EQUB 14
  EQUB 11, 76, 66, 80, 67, 85, 0, 12, 80, 63, 87, 64
  EQUB 80, 77, 77, 73, 89
  EQUB &FE
  EQUB &FF
.brRow_4_50
  EQUB &FF
.brRow_4_51
  \ "Sound advice by"
  EQUB 16
  EQUB 29, 77, 83, 76, 66, 0, 63, 66, 84, 71, 65, 67
  EQUB 0, 64, 87
  EQUB &FE
  EQUB &FF
.brRow_4_52
  EQUB &FF
.brRow_4_53
  \ "Steve Turner."
  EQUB 16
  EQUB 29, 82, 67, 84, 67, 0, 30, 83, 80, 76, 67, 80
  EQUB 89
  EQUB &FE
  EQUB &FF
.brRow_4_54
  EQUB &FF
.brRow_4_55
  EQUB &FF
.brRow_4_56
  \ "Press fire to play"
  EQUB 13
  EQUB 26, 80, 67, 81, 81, 0, 68, 71, 80, 67, 0, 82
  EQUB 77, 0, 78, 74, 63, 87
  EQUB &FE
  EQUB &FF
.brRow_4_57
  EQUB &FF

.brExtra
  \ ',' = index 104
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  \ "'" = index 105
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  \ ';' = index 106
  EQUB &00, &00, &00, &00, &70, &70, &00, &00
  EQUB &00, &00, &70, &70, &30, &60, &00, &00
  \ '@' = index 107
  EQUB &00, &00, &00, &3C, &42, &9D, &A1, &A1
  EQUB &9D, &42, &3C, &00, &00, &00, &00, &00

