\ ============================================================
\ brstream0.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 1, ZX0-packed: 624 bytes -> 409.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_0
  EQUB &06, &0E, &12, &0F, &21, &1D, &19, &18, &FE, &FF, &20, &7E, &10, &4E, &50, &43
  EQUB &51, &43, &4C, &52, &51, &E6, &13, &0F, &1A, &3F, &50, &3F, &42, &50, &4D, &47
  EQUB &42, &E1, &CA, &A5, &09, &0D, &4D, &4B, &4E, &AE, &52, &47, &52, &47, &4D, &4C
  EQUB &00, &42, &F0, &3E, &9A, &5A, &09, &6B, &00, &11, &50, &3F, &44, &56, &45, &4D
  EQUB &4A, &42, &00, &16, &52, &42, &59, &00, &02, &0A, &09, &07, &59, &09, &58, &FF
  EQUB &07, &0C, &0C, &0D, &00, &4E, &4D, &50, &52, &00, &40, &57, &00, &0C, &9E, &51
  EQUB &46, &47, &AF, &3F, &43, &50, &44, &9B, &29, &03, &0D, &4A, &97, &3F, &00, &00
  EQUB &52, &46, &43, &00, &44, &9F, &13, &47, &45, &46, &CB, &A7, &E2, &4D, &44, &00
  EQUB &8F, &1B, &40, &4D, &A9, &BA, &98, &B0, &36, &02, &42, &DF, &E0, &52, &DF, &F8
  EQUB &57, &47, &4C, &45, &AC, &3F, &4B, &00, &55, &47, &F3, &ED, &B9, &F5, &4C, &AB
  EQUB &EF, &4A, &3F, &51, &66, &B6, &FF, &3B, &3C, &83, &B1, &3F, &4C, &51, &44, &BE
  EQUB &DB, &50, &A6, &DE, &41, &C3, &90, &82, &4A, &00, &52, &4D, &1D, &E3, &DF, &1A
  EQUB &CB, &D6, &47, &FE, &45, &89, &15, &ED, &1F, &4A, &4D, &55, &51, &63, &CB, &A4
  EQUB &30, &BD, &1F, &51, &43, &00, &49, &43, &0D, &BE, &D9, &42, &96, &78, &4B, &4D
  EQUB &54, &DF, &36, &57, &4D, &53, &50, &E2, &6F, &59, &32, &AD, &1A, &EB, &E7, &92
  EQUB &47, &FA, &F3, &52, &51, &BE, &4D, &D1, &BA, &77, &EC, &FF, &F5, &05, &8D, &EF
  EQUB &B2, &53, &E7, &DB, &DD, &2C, &DD, &AB, &D1, &EF, &F0, &51, &31, &AB, &91, &59
  EQUB &12, &2E, &BC, &86, &7E, &68, &0B, &55, &46, &47, &4A, &EC, &83, &FB, &3F, &FA
  EQUB &6C, &17, &57, &0C, &AF, &02, &4E, &EB, &2F, &E0, &8F, &8D, &B6, &DD, &5C, &AB
  EQUB &E4, &42, &FD, &64, &BF, &FD, &FC, &D2, &CE, &C0, &6F, &40, &53, &52, &81, &8D
  EQUB &45, &17, &3F, &FE, &85, &26, &61, &32, &41, &52, &B6, &7B, &B9, &4D, &E7, &F5
  EQUB &B6, &63, &7A, &F3, &3E, &CD, &5B, &8E, &FB, &1D, &AD, &CC, &83, &72, &6E, &48
  EQUB &B9, &5B, &04, &0E, &43, &44, &3F, &53, &4A, &3C, &F6, &99, &DA, &DA, &0A, &16
  EQUB &43, &79, &63, &F2, &FE, &FB, &24, &DB, &DD, &1C, &5F, &B4, &DB, &DA, &22, &E3
  EQUB &DC, &1F, &4E, &FC, &E2, &DC, &A0, &15, &B2, &0E, &5B, &F6, &4C, &BA, &82, &17
  EQUB &DB, &10, &1A, &82, &72, &8D, &16, &55, &56
.brStream_0_end

