\ ============================================================
\ brstream2.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 3, ZX0-packed: 962 bytes -> 574.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_2
  EQUB &4A, &03, &1E, &46, &43, &00, &01, &13, &02, &00, &13, &4C, &44, &4A, &53, &43
  EQUB &4C, &41, &83, &E5, &0E, &43, &54, &47, &A5, &F2, &58, &41, &4D, &4C, &51, &47
  EQUB &51, &52, &51, &FE, &FF, &FF, &02, &4D, &44, &00, &3F, &00, &00, &46, &43, &4A
  EQUB &4B, &43, &52, &68, &00, &55, &46, &47, &41, &46, &3E, &A3, &D7, &7B, &4E, &4A
  EQUB &3F, &A7, &42, &89, &B6, &E9, &54, &43, &50, &B2, &7E, &50, &4D, &40, &4D, &52
  EQUB &69, &51, &80, &E4, &52, &E9, &EB, &4A, &00, &53, &4C, &47, &52, &E7, &3F, &AB
  EQUB &83, &3F, &52, &EE, &B0, &52, &1C, &83, &4C, &4D, &50, &4B, &E7, &E3, &A5, &41
  EQUB &52, &47, &EF, &27, &F9, &43, &A3, &BB, &3A, &CF, &3F, &FE, &AD, &82, &B2, &2F
  EQUB &44, &BB, &AB, &16, &51, &FE, &F3, &D7, &BD, &0F, &36, &59, &00, &AA, &DC, &F8
  EQUB &FD, &13, &AB, &8F, &CE, &89, &EF, &8D, &8B, &55, &47, &78, &EB, &07, &E3, &45
  EQUB &57, &A3, &53, &4E, &7E, &DF, &F3, &8F, &37, &4C, &42, &CD, &EF, &D1, &D9, &51
  EQUB &1C, &78, &4E, &FB, &8F, &9E, &8F, &7D, &44, &68, &E3, &FF, &2B, &B4, &F9, &83
  EQUB &9F, &45, &50, &3F, &42, &67, &7C, &60, &B5, &BB, &4E, &3F, &40, &47, &B9, &57
  EQUB &9F, &26, &24, &76, &AD, &3B, &51, &4D, &AC, &E3, &8D, &64, &F6, &95, &24, &4B
  EQUB &00, &41, &4A, &4D, &3F, &49, &7E, &AC, &25, &ED, &50, &45, &43, &AF, &62, &4D
  EQUB &C5, &6F, &68, &14, &77, &85, &29, &7D, &59, &CF, &32, &DC, &64, &EF, &57, &BD
  EQUB &44, &39, &DB, &A5, &BB, &55, &B7, &F3, &46, &47, &BE, &F5, &4C, &04, &AF, &4A
  EQUB &51, &55, &6A, &63, &4B, &BF, &53, &C8, &F6, &B1, &6D, &01, &6F, &52, &53, &50
  EQUB &99, &63, &E2, &E3, &C5, &04, &BB, &E3, &00, &15, &55, &67, &44, &D9, &B3, &2A
  EQUB &CB, &E5, &54, &CF, &D5, &A4, &BF, &CC, &B6, &8D, &CF, &41, &57, &EB, &C9, &DB
  EQUB &50, &E2, &6D, &02, &DB, &17, &F0, &27, &3A, &5A, &41, &42, &1D, &6F, &BC, &B5
  EQUB &7F, &53, &43, &EB, &ED, &ED, &56, &8E, &00, &71, &37, &4C, &4C, &B7, &CA, &8F
  EQUB &87, &52, &3B, &D7, &42, &6A, &E5, &46, &1B, &4A, &42, &47, &4C, &45, &5D, &62
  EQUB &D3, &E4, &37, &48, &73, &52, &33, &61, &72, &89, &4A, &CF, &54, &8D, &1F, &4B
  EQUB &4E, &27, &96, &F8, &7B, &3C, &ED, &53, &4B, &AD, &69, &66, &22, &D8, &69, &FD
  EQUB &DC, &4E, &43, &DB, &F6, &B8, &D6, &2C, &13, &FF, &E8, &6A, &CB, &B3, &7A, &F6
  EQUB &B3, &0B, &E8, &A3, &51, &3B, &4F, &8A, &7A, &E8, &45, &C9, &70, &75, &CF, &7C
  EQUB &05, &CF, &3B, &CD, &BA, &CD, &1B, &FF, &6D, &EB, &DD, &BF, &8D, &B0, &9C, &50
  EQUB &B4, &48, &AB, &15, &4B, &40, &6D, &4F, &4C, &F7, &90, &3F, &3F, &86, &17, &1B
  EQUB &69, &44, &DC, &33, &D4, &BA, &3F, &2C, &F3, &55, &64, &6A, &BA, &4F, &B6, &47
  EQUB &B0, &C9, &CA, &39, &B2, &FF, &E7, &95, &7D, &4F, &9E, &FF, &04, &10, &5D, &12
  EQUB &FC, &D5, &E7, &E0, &C9, &62, &9B, &52, &3F, &49, &7C, &06, &7E, &00, &29, &F0
  EQUB &10, &97, &DB, &71, &66, &F6, &30, &79, &F9, &47, &5F, &62, &DC, &FC, &C8, &DC
  EQUB &BE, &4A, &5B, &78, &E1, &1E, &EB, &F3, &40, &6D, &A8, &63, &44, &7E, &85, &BD
  EQUB &E1, &37, &3F, &45, &50, &CF, &B3, &CB, &4B, &E2, &CF, &DF, &A4, &8B, &77, &0A
  EQUB &1A, &2D, &C2, &2E, &8A, &44, &30, &EF, &0E, &57, &D0, &D5, &55, &60
.brStream_2_end

