\ ============================================================
\ brstream3.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 4, ZX0-packed: 932 bytes -> 566.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_3
  EQUB &04, &E8, &03, &0B, &4C, &00, &13, &4C, &44, &4A, &53, &43, &4C, &41, &43, &00
  EQUB &0E, &43, &54, &47, &F2, &E0, &41, &3F, &D7, &0B, &52, &50, &3F, &4C, &51, &4B
  EQUB &47, &52, &FE, &FF, &FF, &02, &4D, &4C, &4A, &57, &8A, &D1, &50, &52, &0B, &47
  EQUB &4C, &00, &42, &93, &F3, &68, &00, &4C, &3F, &4B, &43, &B8, &D6, &C1, &6F, &51
  EQUB &00, &00, &4D, &55, &B4, &9E, &4A, &4D, &41, &CB, &FE, &47, &A9, &DF, &8D, &E3
  EQUB &42, &81, &46, &43, &F7, &EF, &DA, &BF, &BB, &44, &FB, &DD, &FA, &7D, &B0, &50
  EQUB &BF, &40, &E9, &93, &B8, &6A, &27, &7A, &51, &53, &3F, &4A, &00, &2C, &1F, &45
  EQUB &43, &59, &1E, &46, &E5, &8B, &46, &00, &FB, &F1, &B2, &4B, &FB, &A5, &D5, &71
  EQUB &55, &A8, &3B, &46, &FB, &49, &4C, &39, &A3, &51, &AA, &BD, &4E, &4A, &9E, &57
  EQUB &4D, &53, &82, &FF, &AF, &B6, &A1, &E8, &E3, &50, &00, &0C, &0C, &0D, &79, &43
  EQUB &4B, &F8, &57, &1D, &FB, &FB, &50, &4B, &4F, &59, &59, &B6, &C6, &4B, &7F, &42
  EQUB &42, &47, &04, &B8, &3A, &D9, &F7, &44, &4D, &CD, &C2, &7F, &01, &7D, &7F, &BE
  EQUB &7C, &FD, &56, &8D, &9E, &CF, &D2, &B7, &6F, &55, &40, &6F, &DF, &E7, &26, &BB
  EQUB &00, &E7, &57, &78, &96, &6E, &3F, &41, &41, &43, &51, &DD, &D9, &45, &4E, &FB
  EQUB &94, &69, &6A, &0B, &41, &7B, &4B, &4E, &53, &18, &6F, &E4, &FB, &F8, &B2, &DF
  EQUB &2A, &4C, &51, &4D, &4A, &59, &B9, &0B, &BB, &2F, &4B, &3F, &4A, &4A, &62, &51
  EQUB &F5, &B7, &A1, &4E, &95, &3F, &F8, &18, &6B, &55, &B6, &B8, &29, &6D, &43, &41
  EQUB &49, &BB, &26, &8D, &54, &EE, &2B, &BF, &40, &DB, &FD, &68, &EB, &E5, &BE, &1D
  EQUB &43, &91, &1A, &3B, &CC, &BB, &75, &47, &B3, &00, &D7, &DF, &D1, &7F, &88, &78
  EQUB &78, &02, &D8, &3A, &B7, &1C, &96, &ED, &B0, &FB, &03, &91, &F9, &4E, &B5, &FB
  EQUB &51, &B7, &71, &52, &94, &FB, &A9, &0A, &F8, &E3, &E5, &6C, &67, &57, &4B, &40
  EQUB &DF, &13, &8A, &37, &69, &70, &FE, &DD, &6D, &BE, &B2, &62, &B9, &B2, &45, &68
  EQUB &23, &4C, &53, &DD, &BF, &6B, &D7, &8B, &EF, &22, &71, &44, &47, &B7, &51, &5B
  EQUB &8E, &CA, &9E, &3D, &0D, &73, &D4, &BD, &04, &ED, &CC, &17, &67, &FB, &C3, &2F
  EQUB &34, &6F, &98, &DA, &B7, &41, &81, &36, &C5, &3C, &4C, &8E, &66, &6B, &ED, &13
  EQUB &78, &F7, &FB, &ED, &D3, &8F, &B4, &5B, &F5, &1F, &0D, &B3, &60, &D9, &2F, &B5
  EQUB &59, &B0, &AE, &1E, &2A, &CB, &06, &5F, &DE, &5F, &7F, &C5, &5D, &C6, &EF, &47
  EQUB &57, &EB, &BE, &07, &54, &A3, &64, &0E, &2F, &2E, &53, &51, &72, &3F, &E2, &E3
  EQUB &BB, &CB, &4F, &53, &7D, &B5, &B3, &F5, &51, &53, &D8, &07, &32, &A7, &52, &58
  EQUB &FC, &2C, &19, &7D, &96, &3F, &60, &5A, &2B, &53, &1B, &A6, &E2, &B2, &4D, &44
  EQUB &6A, &4A, &DD, &55, &29, &CE, &92, &56, &D6, &C2, &D3, &6A, &FD, &DF, &F9, &B2
  EQUB &BA, &E2, &37, &15, &D7, &51, &C4, &4D, &70, &E7, &FE, &B6, &D7, &D0, &37, &EA
  EQUB &F7, &B0, &4B, &EA, &7B, &C9, &88, &C2, &CD, &B0, &F5, &AD, &FF, &E3, &61, &AE
  EQUB &5C, &31, &2C, &65, &46, &CD, &8E, &B0, &86, &B7, &D6, &23, &49, &6E, &FD, &86
  EQUB &83, &AA, &F2, &C3, &FE, &7F, &0A, &1A, &50, &C8, &3E, &DD, &F3, &AA, &D3, &94
  EQUB &BF, &57, &C8, &55, &55, &80
.brStream_3_end

