\ ============================================================
\ brstream1.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 2, ZX0-packed: 967 bytes -> 604.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_1
  EQUB &4A, &03, &0B, &00, &44, &4A, &43, &29, &52, &00, &A5, &4D, &44, &00, &7A, &1C
  EQUB &4D, &40, &4D, &62, &10, &50, &43, &47, &45, &46, &52, &43, &50, &51, &D6, &5E
  EQUB &4C, &FE, &FF, &FF, &02, &47, &52, &EB, &12, &55, &3F, &57, &00, &52, &4D, &00
  EQUB &52, &46, &43, &BA, &0C, &A3, &3F, &BB, &0D, &F7, &47, &9E, &C1, &51, &57, &51
  EQUB &AF, &FE, &4B, &B8, &97, &62, &4E, &4D, &50, &0E, &42, &00, &43, &4C, &8A, &90
  EQUB &FE, &47, &4C, &45, &00, &3F, &4C, &00, &53, &4C, &41, &46, &3F, &D4, &37, &A3
  EQUB &47, &4A, &42, &FB, &B0, &32, &F8, &CD, &97, &BB, &0F, &4D, &47, &42, &51, &59
  EQUB &00, &0F, &3F, &BD, &A1, &72, &F8, &46, &47, &4E, &00, &41, &AD, &91, &8F, &43
  EQUB &51, &B2, &EB, &E6, &45, &EA, &25, &A6, &40, &AB, &52, &4A, &B8, &19, &42, &A0
  EQUB &DB, &FC, &FB, &A7, &2D, &45, &44, &AF, &29, &41, &B0, &DE, &E0, &2B, &4D, &53
  EQUB &55, &F8, &E1, &43, &B7, &FF, &43, &44, &05, &D1, &53, &A3, &CC, &03, &1E, &D8
  EQUB &D9, &C1, &8B, &42, &47, &50, &E3, &DF, &8F, &40, &43, &DD, &2F, &67, &B6, &5C
  EQUB &E1, &FB, &54, &9D, &E2, &D9, &AF, &94, &FE, &D5, &E1, &BD, &29, &42, &59, &6B
  EQUB &1D, &47, &4B, &47, &4A, &3F, &50, &4B, &A2, &A2, &3F, &45, &DB, &1C, &BF, &D0
  EQUB &B8, &E8, &7D, &47, &43, &F7, &85, &4B, &6E, &A6, &AF, &F6, &1E, &1B, &9E, &3E
  EQUB &BD, &69, &E1, &42, &6A, &C8, &8D, &DA, &4B, &40, &29, &42, &3B, &DD, &57, &CC
  EQUB &D5, &BF, &E9, &E3, &7E, &DB, &44, &53, &4A, &9E, &B8, &B3, &47, &85, &E3, &47
  EQUB &41, &B4, &B3, &79, &4B, &E7, &7F, &67, &F7, &DD, &DC, &73, &41, &F2, &5E, &E0
  EQUB &4D, &E3, &8E, &0B, &4A, &F7, &99, &CC, &D6, &89, &DC, &CF, &05, &06, &FD, &E1
  EQUB &10, &B5, &68, &8D, &D8, &9C, &2F, &4A, &53, &42, &F8, &30, &D1, &FB, &4D, &51
  EQUB &CD, &ED, &00, &7D, &AE, &AD, &8C, &68, &F3, &D8, &81, &75, &71, &E2, &D2, &46
  EQUB &57, &ED, &4B, &62, &D7, &91, &A7, &76, &33, &8A, &6C, &41, &A3, &E1, &55, &59
  EQUB &A2, &DB, &B0, &63, &88, &2E, &38, &BB, &DB, &49, &8E, &33, &30, &C8, &7B, &91
  EQUB &F8, &4D, &4A, &D5, &42, &F7, &99, &A6, &CC, &26, &F5, &B9, &AE, &49, &42, &6A
  EQUB &7F, &A5, &67, &B7, &81, &4C, &C1, &6C, &B2, &FF, &CA, &AA, &EA, &B2, &51, &D7
  EQUB &53, &98, &FB, &46, &42, &F3, &BC, &B1, &CB, &69, &80, &DF, &D7, &0F, &19, &A3
  EQUB &6A, &4A, &57, &5C, &38, &EE, &DB, &4E, &B2, &B2, &4B, &42, &FB, &BB, &E9, &50
  EQUB &67, &02, &5D, &F1, &6E, &7A, &6A, &D6, &95, &81, &43, &CB, &6C, &2A, &E8, &4A
  EQUB &F4, &67, &BF, &68, &8A, &5B, &1E, &71, &AB, &F6, &DD, &CD, &21, &BB, &4D, &C2
  EQUB &F9, &32, &4C, &D3, &FD, &5D, &F7, &DD, &EE, &2C, &D4, &E7, &D9, &56, &32, &1F
  EQUB &24, &0C, &73, &1E, &1F, &5F, &85, &7C, &3B, &C1, &D7, &93, &7E, &3B, &CB, &3F
  EQUB &3D, &60, &8F, &B6, &DD, &6E, &17, &57, &CD, &F7, &4E, &03, &2B, &6B, &71, &13
  EQUB &9E, &DE, &B4, &3C, &2F, &FC, &C1, &70, &CF, &AA, &0C, &DB, &B0, &1E, &2B, &73
  EQUB &DA, &42, &E4, &FF, &3F, &7D, &5B, &B0, &DB, &60, &F1, &6C, &DB, &E4, &0E, &6F
  EQUB &89, &49, &46, &C6, &AF, &9F, &53, &9E, &D3, &23, &5C, &FD, &6B, &CF, &47, &7C
  EQUB &E7, &E5, &D8, &CB, &A2, &F9, &ED, &64, &D3, &B8, &DA, &4D, &40, &D2, &62, &D3
  EQUB &6C, &D3, &6B, &4A, &F5, &52, &35, &B5, &6C, &EA, &0E, &13, &8C, &44, &6D, &32
  EQUB &9B, &FF, &0E, &43, &54, &EF, &F3, &42, &FF, &55, &55, &80
.brStream_1_end

