\ ============================================================
\ brstream4b.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 5, SECOND CHUNK: bytes 270.. of the page,
\ CUT-CACHE 270 cd9cadbb77789ecc
\ ZX0-packed to 154.
\ It depacks straight on from where chunk A stopped -
\ Zx0Unpack leaves mapptr past its last byte, so BrDepack
\ just points src at this and calls it again. The two
\ chunks are in DIFFERENT banks on purpose; see main.asm.
.brStream_4b
  EQUB &60, &1C, &FE, &FF, &85, &3A, &0B, &1A, &3F, &50, &3F, &42, &50, &4D, &47, &42
  EQUB &62, &0A, &01, &00, &4B, &53, &51, &47, &41, &00, &40, &57, &C8, &5E, &10, &14
  EQUB &3F, &51, &4D, &4C, &00, &C3, &7E, &45, &43, &59, &E3, &B1, &E0, &0D, &E7, &A0
  EQUB &54, &43, &50, &52, &E4, &42, &00, &52, &4D, &FB, &F2, &46, &43, &00, &0C, &0C
  EQUB &0D, &AC, &39, &51, &41, &79, &E3, &57, &40, &43, &A1, &52, &51, &F0, &AB, &56
  EQUB &EE, &A7, &4E, &F5, &E3, &45, &E9, &4B, &4B, &E6, &91, &A6, &78, &0E, &0B, &4C
  EQUB &CF, &FF, &43, &55, &85, &D7, &9B, &8F, &C9, &4D, &49, &46, &8A, &10, &1D, &EE
  EQUB &53, &D3, &00, &9B, &FF, &54, &05, &4F, &B1, &8F, &DA, &2B, &87, &21, &00, &1E
  EQUB &53, &50, &4C, &FA, &15, &B9, &56, &B8, &0D, &91, &7D, &51, &51, &00, &44, &47
  EQUB &F3, &E7, &FA, &4E, &4A, &3F, &F5, &B0, &55, &58
.brStream_4b_end

