\ ============================================================
\ brstream4.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 5, ZX0-packed: 469 bytes -> 175.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_4
  EQUB &40, &88, &0D, &1E, &4D, &4E, &00, &51, &41, &4D, &50, &43, &00, &4D, &44, &00
  EQUB &52, &46, &43, &00, &42, &3F, &57, &63, &FE, &FF, &99, &0F, &00, &08, &07, &09
  EQUB &01, &0A, &00, &62, &00, &0B, &0F, &0C, &FE, &FF, &23, &0C, &21, &8F, &AD, &51
  EQUB &52, &9E, &16, &A9, &06, &03, &99, &0C, &0C, &0D, &2E, &06, &41, &5B, &00, &4E
  EQUB &3F, &53, &51, &43, &63, &89, &FE, &7A, &0D, &52, &50, &4A, &62, &1A, &FE, &CE
  EQUB &16, &17, &53, &52, &43, &00, &51, &4D, &53, &4C, &42, &63, &06, &82, &1B, &5A
  EQUB &20, &4D, &4A, &53, &4B, &43, &00, &E1, &4E, &D0, &8E, &1F, &4E, &CE, &0E, &99
  EQUB &AA, &42, &55, &E6, &63, &D0, &EF, &0E, &EA, &68, &A8, &1B, &A7, &47, &52, &45
  EQUB &3F, &4B, &9B, &34, &0F, &62, &C3, &3F, &4E, &D8, &9E, &96, &04, &0E, &53, &50
  EQUB &47, &4C, &45, &B8, &40, &F5, &F9, &43, &44, &EE, &DF, &4D, &4C, &4A, &A4, &A7
  EQUB &98, &1C, &43, &42, &F8, &DA, &61, &25, &49, &43, &57, &51, &D5, &55, &60
.brStream_4_end

