\ ============================================================
\ brstream0.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 1, ZX0-packed: 622 bytes -> 404.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_0
  EQUB &06, &0E, &12, &0F, &21, &1D, &19, &18, &FE, &FF, &20, &7E, &10, &4E, &50, &43
  EQUB &51, &43, &4C, &52, &51, &E6, &13, &0F, &1A, &3F, &50, &3F, &42, &50, &4D, &47
  EQUB &42, &E1, &CA, &A5, &09, &0D, &4D, &4B, &4E, &AE, &52, &47, &52, &47, &4D, &4C
  EQUB &00, &42, &F0, &3E, &9A, &5A, &09, &6B, &00, &11, &50, &3F, &44, &56, &45, &4D
  EQUB &4A, &42, &00, &16, &52, &42, &59, &00, &02, &0A, &09, &07, &59, &09, &58, &FF
  EQUB &07, &0C, &0C, &0D, &00, &4E, &4D, &50, &52, &00, &40, &57, &00, &0C, &9E, &51
  EQUB &46, &47, &AF, &3F, &43, &50, &44, &9B, &29, &03, &0D, &4A, &97, &3F, &00, &00
  EQUB &52, &46, &43, &00, &44, &9F, &13, &47, &45, &46, &CB, &A7, &E2, &4D, &44, &00
  EQUB &8F, &1B, &40, &4D, &A9, &BA, &98, &B0, &36, &02, &42, &DF, &E0, &52, &DF, &F8
  EQUB &57, &47, &4C, &45, &AC, &3F, &4B, &00, &55, &47, &F3, &ED, &B9, &F5, &4C, &AB
  EQUB &EF, &4A, &3F, &51, &66, &B6, &FF, &3B, &3C, &83, &B1, &3F, &4C, &51, &44, &BE
  EQUB &DB, &50, &A6, &DE, &41, &C3, &90, &82, &4A, &00, &52, &4D, &1D, &E3, &DF, &1A
  EQUB &CB, &D6, &47, &FE, &45, &89, &15, &ED, &1F, &4A, &4D, &55, &51, &63, &CB, &A4
  EQUB &30, &BD, &1F, &51, &43, &00, &49, &43, &0D, &BE, &D9, &42, &96, &78, &4B, &4D
  EQUB &54, &DF, &36, &57, &4D, &53, &50, &E2, &6F, &59, &32, &AD, &1A, &EB, &E7, &92
  EQUB &47, &FA, &F3, &52, &51, &BE, &4D, &D1, &BA, &36, &EC, &78, &BA, &B2, &12, &F2
  EQUB &E6, &BC, &D8, &55, &27, &FB, &4A, &51, &C1, &FB, &3F, &3E, &AA, &55, &6B, &57
  EQUB &68, &00, &50, &E8, &74, &4E, &77, &A6, &6F, &68, &6A, &EB, &DA, &4E, &CB, &BD
  EQUB &F0, &9F, &BC, &C8, &76, &F6, &AC, &42, &8D, &5F, &17, &3F, &DF, &CF, &60, &BD
  EQUB &6D, &41, &61, &FF, &00, &B8, &F7, &BD, &07, &51, &73, &C4, &F7, &78, &17, &5B
  EQUB &D8, &BD, &29, &43, &EF, &97, &A6, &DF, &6A, &34, &8A, &53, &51, &B7, &00, &A9
  EQUB &5B, &F8, &73, &EC, &F7, &59, &C9, &A1, &E0, &3D, &19, &A7, &04, &0E, &43, &44
  EQUB &53, &4A, &52, &3C, &FA, &98, &DE, &E7, &0A, &16, &DD, &52, &63, &00, &CB, &FE
  EQUB &24, &ED, &DB, &DD, &1C, &7F, &B8, &DA, &6F, &22, &DC, &8F, &1F, &4E, &E2, &F2
  EQUB &DC, &82, &15, &CB, &0E, &5F, &4C, &DA, &BA, &17, &0B, &10, &2E, &E8, &72, &0A
  EQUB &16, &35, &55, &58
.brStream_0_end

