\ ============================================================
\ brstream4.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 5, ZX0-packed: 483 bytes -> 325.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_4
  EQUB &40, &88, &0D, &1E, &4D, &4E, &00, &51, &41, &4D, &50, &43, &00, &4D, &44, &00
  EQUB &52, &46, &43, &00, &42, &3F, &57, &63, &FE, &FF, &99, &0F, &00, &08, &07, &09
  EQUB &01, &0A, &00, &62, &00, &0B, &0F, &0C, &FE, &FF, &23, &0C, &21, &8F, &AD, &51
  EQUB &52, &9E, &16, &A9, &06, &03, &99, &0C, &0C, &0D, &2E, &06, &41, &5B, &00, &4E
  EQUB &3F, &53, &51, &43, &63, &89, &FE, &7A, &0D, &52, &50, &4A, &62, &1A, &FE, &CE
  EQUB &16, &17, &53, &52, &43, &00, &51, &4D, &53, &4C, &42, &63, &06, &82, &1B, &5A
  EQUB &20, &4D, &4A, &53, &4B, &43, &00, &E1, &4E, &D0, &8E, &1F, &4E, &CE, &0E, &99
  EQUB &AA, &42, &55, &E6, &63, &D0, &EF, &0E, &EA, &68, &A8, &1B, &A7, &47, &52, &45
  EQUB &3F, &4B, &9B, &34, &0F, &62, &C3, &3F, &4E, &D8, &9E, &96, &04, &0E, &53, &50
  EQUB &47, &4C, &45, &B8, &40, &F5, &F9, &43, &44, &EE, &DF, &4D, &4C, &4A, &A4, &A7
  EQUB &98, &1C, &43, &42, &F8, &DA, &61, &25, &49, &43, &57, &51, &B7, &1C, &96, &24
  EQUB &2B, &1A, &3F, &50, &3F, &42, &50, &4D, &47, &42, &62, &0A, &01, &4B, &63, &85
  EQUB &47, &41, &BA, &7D, &57, &C8, &0E, &0C, &14, &3F, &51, &7D, &E7, &00, &C3, &45
  EQUB &43, &59, &EE, &10, &0D, &E7, &0F, &54, &43, &50, &52, &6D, &2C, &EF, &4D, &F7
  EQUB &E8, &10, &F3, &AC, &79, &F9, &79, &E3, &57, &40, &43, &A1, &52, &51, &F1, &AB
  EQUB &56, &CE, &DF, &F5, &E3, &45, &E9, &4B, &4B, &E6, &91, &A6, &33, &0A, &0B, &F7
  EQUB &2F, &61, &55, &85, &F8, &D7, &9B, &C9, &E3, &4D, &49, &46, &BB, &68, &AD, &4D
  EQUB &E8, &45, &B8, &DE, &00, &15, &83, &C9, &E2, &4C, &D2, &76, &0B, &42, &42, &27
  EQUB &E1, &47, &0F, &B6, &3F, &4A, &00, &41, &4D, &83, &A0, &12, &FE, &56, &55, &3F
  EQUB &40, &CA, &71, &E7, &1A, &75, &51, &51, &00, &7D, &55, &F3, &E7, &DE, &4E, &4A
  EQUB &3F, &F5, &44, &55, &58
.brStream_4_end

