\ ============================================================
\ brstream0.asm - GENERATED by tools/make_briefing.py
\ ============================================================
\ Briefing page 1, ZX0-packed: 668 bytes -> 424.
\ The row lists and nothing else. It depacks to BR_RECS and
\ the driver rebuilds brRowLo/Hi at BR_BUF by scanning it for
\ the $FF row terminators - 332 bytes cheaper across the five
\ pages than carrying the tables in (docs/no-load.md 15d).
\ Placed in a bank by main.asm; nothing here may span one.
.brStream_0
  EQUB &06, &0E, &12, &0F, &21, &1D, &19, &18, &FE, &FF, &20, &7E, &10, &4E, &50, &43
  EQUB &51, &43, &4C, &52, &51, &E6, &13, &0F, &1A, &3F, &50, &3F, &42, &50, &4D, &47
  EQUB &42, &E1, &CA, &A5, &09, &0D, &4D, &4B, &4E, &AE, &52, &47, &52, &47, &4D, &4C
  EQUB &00, &42, &F0, &3E, &9A, &5A, &09, &6B, &00, &11, &50, &3F, &44, &56, &45, &4D
  EQUB &4A, &42, &00, &16, &52, &42, &59, &00, &02, &0A, &09, &07, &59, &09, &58, &FF
  EQUB &07, &0C, &0C, &0D, &00, &4E, &4D, &50, &52, &00, &40, &57, &00, &0C, &9E, &51
  EQUB &46, &47, &AF, &3F, &43, &50, &44, &9B, &29, &03, &0D, &4A, &97, &3F, &00, &00
  EQUB &52, &46, &43, &00, &44, &9F, &13, &47, &45, &46, &CB, &A7, &E2, &4D, &44, &00
  EQUB &8F, &1B, &40, &4D, &A9, &BA, &98, &B0, &36, &02, &42, &DF, &E0, &52, &DF, &F8
  EQUB &57, &47, &4C, &45, &AC, &3F, &4B, &00, &55, &47, &F3, &ED, &B9, &F5, &4C, &AB
  EQUB &EF, &4A, &3F, &51, &66, &B6, &FF, &3B, &3C, &83, &B1, &3F, &4C, &51, &44, &BE
  EQUB &DB, &50, &A6, &DE, &41, &C3, &90, &82, &4A, &00, &52, &4D, &1D, &FB, &DF, &1A
  EQUB &1F, &83, &9F, &00, &49, &43, &57, &EF, &43, &0F, &42, &CC, &83, &4B, &4D, &54
  EQUB &43, &9B, &1B, &57, &4D, &53, &9B, &16, &59, &EB, &66, &1A, &F6, &1B, &05, &D9
  EQUB &EF, &47, &F1, &00, &82, &AB, &51, &4D, &E7, &CD, &B4, &CE, &18, &B2, &2D, &12
  EQUB &BC, &1E, &B4, &82, &55, &46, &47, &4A, &EE, &BA, &F9, &CF, &3F, &D2, &8F, &47
  EQUB &57, &68, &E7, &7E, &D9, &66, &86, &4E, &3E, &3F, &41, &D0, &F9, &68, &64, &E1
  EQUB &4E, &53, &52, &1E, &F7, &EB, &AB, &FD, &D9, &B0, &DD, &88, &AA, &DA, &42, &EA
  EQUB &59, &31, &17, &B6, &49, &78, &3B, &8A, &63, &18, &FB, &B6, &BB, &4D, &CF, &EF
  EQUB &B6, &CF, &86, &60, &FD, &FF, &7B, &6E, &E6, &0F, &FD, &43, &EA, &97, &7C, &CE
  EQUB &14, &B4, &6D, &53, &ED, &93, &DE, &B5, &80, &B7, &FC, &C8, &7F, &43, &1B, &6D
  EQUB &77, &43, &BB, &A8, &4F, &42, &8F, &F9, &45, &3F, &6D, &F5, &A8, &B3, &D2, &D5
  EQUB &9E, &6A, &B7, &4A, &04, &0E, &43, &44, &3F, &53, &CE, &52, &92, &35, &51, &63
  EQUB &A2, &DE, &0A, &16, &EB, &7D, &63, &CB, &FE, &24, &ED, &DC, &1C, &7F, &88, &DA
  EQUB &6F, &22, &DC, &8F, &1F, &4E, &E2, &F2, &DC, &82, &15, &0F, &0E, &4D, &55, &4C
  EQUB &BA, &68, &17, &2C, &10, &B8, &8E, &72, &28, &16, &2D, &0B, &8F, &A2, &8E, &21
  EQUB &8D, &1D, &1A, &0B, &0D, &0F, &55, &56
.brStream_0_end

