\ ============================================================
\ conicons.asm - GENERATED by tools/export_icons.py, do not edit
\ ============================================================
\ The console menu icons, C64 sprites 2, 3 and 4 of conRedraw's
\ table at $6B94, converted to MODE 1.
\
\ SPRITE 1 IS NOT HERE. Its image pointer is $4F, and $53C0 is blank
\ in ROM: that is where BuildDroidSprite composes the PLAYER'S OWN
\ droid at run time, which is why conRedraw sets dType from droidType
\ before it draws. Ours is drawn from the sprite bank instead.
\
\ Each icon is 24 x 21 px = THREE character rows of six 4-pixel
\ columns. Consecutive columns are eight bytes apart and a column is
\ eight consecutive scanlines, so the six columns of one row are 48
\ CONSECUTIVE bytes in the buffer -- an icon is three flat 48-byte
\ copies at base, base + 640 and base + 1280.

GEN_ICON_COUNT = 3
GEN_ICON_ROWS  = 3
GEN_ICON_LINES = 21

.conicons
  \ droid ? emblem  (pointer $50 at $5400)
  EQUB &00, &38, &00, &00, &38, &00, &03, &FF, &80, &0F, &FF, &E0, &3F, &FF, &F8, &00
  EQUB &00, &00, &00, &FC, &00, &00, &FE, &00, &00, &0E, &00, &00, &3E, &00, &00, &3C
  EQUB &00, &00, &00, &00, &00, &38, &00, &00, &38, &00, &00, &00, &00, &3F, &FF, &F8
  EQUB &0F, &FF, &E0, &03, &FF, &80, &00, &10, &00, &00, &00, &00, &00, &00, &00
  \ ship plan badge  (pointer $A1 at $6840, X-EXPANDED at draw time)
  EQUB &00, &FC, &00, &0E, &FF, &00, &3F, &CF, &80, &7F, &FF, &80, &D8, &3F, &C0, &DB
  EQUB &A0, &F0, &D8, &2E, &F0, &7F, &E6, &30, &3F, &F7, &BC, &0C, &16, &9E, &0D, &D6
  EQUB &57, &0C, &16, &9E, &3F, &F7, &BC, &7F, &E6, &30, &D8, &2E, &F0, &DB, &A0, &F0
  EQUB &D8, &3F, &C0, &7F, &FF, &80, &3F, &CF, &80, &0E, &FF, &00, &00, &FC, &00
  \ ship side view  (pointer $A2 at $6880, X-EXPANDED at draw time)
  EQUB &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &01
  EQUB &83, &00, &03, &EF, &D0, &0F, &FF, &BC, &3E, &03, &AE, &70, &FD, &AB, &D6, &FE
  EQUB &AE, &D6, &FE, &BC, &D6, &FE, &B0, &70, &FE, &80, &3E, &FE, &80, &00, &FE, &00
  EQUB &00, &F8, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00, &00
.conicons_end
ASSERT conicons_end - conicons == 189
ASSERT GEN_ICON_COUNT == CON_ICON_COUNT

\ All three are stored 24 px wide. CON_ICON_EXP is a bit per icon
\ saying which the VIC draws X-expanded; ConIcons doubles those as
\ it copies, from a 16-entry nibble table.
CON_ICON0_OFS = 0     \ droid ? emblem    
CON_ICON1_OFS = 63    \ ship plan badge     X-EXPANDED
CON_ICON2_OFS = 126   \ ship side view      X-EXPANDED
CON_ICON_EXP  = %110

