\ ============================================================
\ droids.asm
\ GENERATED by tools/export_droids.py - do not edit by hand.
\ Source: paradroid_ce.lst (Paradroid, C64 - original/CE lineage)
\ 24 droid types, 8 rotor phases, waypoints for 16 decks
\ ============================================================
\ Shifts 0 and 1 px. The other two are in the other
\ sprite bank, at the same table addresses.

DR_W        = 7                 \ 24 px, plus one for the shift spill
DR_H        = 21
DR_FRAMES   = 8
DR_TYPES    = 24
DR_ROWS     = 249              \ distinct stored rows
DR_DATASIZE = DR_ROWS * DR_W
DR_DIGIT0   = 6                 \ first digit row
DR_DIGITN   = 8                 \ how many digit rows
DR_SEQSHIFT = 80                \ sequence stride between this bank's two shifts
DR_GLYPHS   = 10                \ digit glyphs, and the glyph-table stride
DR_COLPAT_N = 11                 \ colPix entries, asserted against SPR_COLPATS

\ ==== fixed section: SAME SIZE AND ORDER IN BOTH BANKS ====
\ Everything the blitter reaches by name. Sizes here are
\ independent of which shifts the bank holds, so the
\ addresses match and one set of labels serves both.
\ The stored artwork is not among them: drSprData and
\ drOfs are in the DATA bank, read only by SprFetchRow.

\ p * 21, to index drOfs.
.drMulRows
  EQUB &00,&15,&2A,&3F,&54,&69,&7E,&93

\ Byte offset of each type's 8 digit rows into drSprData.
.drDigitLo
  EQUB &88,&C0,&F8,&30,&68,&A0,&D8,&10,&48,&80,&B8,&F0
  EQUB &28,&60,&98,&D0,&08,&40,&78,&B0,&E8,&20,&58,&90
.drDigitHi
  EQUB &01,&01,&01,&02,&02,&02,&02,&03,&03,&03,&03,&03
  EQUB &04,&04,&04,&04,&05,&05,&05,&05,&05,&06,&06,&06

\ Rotor dispatch, at index (shift AND 1)*80 + phase*10 + n,
\ where n counts the ten drawn rotor rows in drawing order.
\ This bank holds shifts 0 and 1 px; the other holds the
\ other two, at the same addresses with its own contents.
.drSeqLo
  EQUB LO(drD0_00),LO(drD0_02),LO(drD0_04),LO(drD0_05),LO(drD0_06),LO(drD0_06),LO(drD0_05),LO(drD0_04),LO(drD0_03),LO(drD0_01)
  EQUB LO(drD0_00),LO(drD0_02),LO(drD0_07),LO(drD0_08),LO(drD0_09),LO(drD0_09),LO(drD0_08),LO(drD0_07),LO(drD0_03),LO(drD0_01)
  EQUB LO(drD0_00),LO(drD0_02),LO(drD0_10),LO(drD0_11),LO(drD0_12),LO(drD0_12),LO(drD0_11),LO(drD0_10),LO(drD0_03),LO(drD0_01)
  EQUB LO(drD0_00),LO(drD0_02),LO(drD0_13),LO(drD0_14),LO(drD0_15),LO(drD0_15),LO(drD0_14),LO(drD0_13),LO(drD0_03),LO(drD0_01)
  EQUB LO(drD0_01),LO(drD0_03),LO(drD0_16),LO(drD0_17),LO(drD0_18),LO(drD0_18),LO(drD0_17),LO(drD0_16),LO(drD0_02),LO(drD0_00)
  EQUB LO(drD0_01),LO(drD0_03),LO(drD0_19),LO(drD0_20),LO(drD0_21),LO(drD0_21),LO(drD0_20),LO(drD0_19),LO(drD0_02),LO(drD0_00)
  EQUB LO(drD0_01),LO(drD0_03),LO(drD0_22),LO(drD0_23),LO(drD0_24),LO(drD0_24),LO(drD0_23),LO(drD0_22),LO(drD0_02),LO(drD0_00)
  EQUB LO(drD0_01),LO(drD0_03),LO(drD0_25),LO(drD0_26),LO(drD0_27),LO(drD0_27),LO(drD0_26),LO(drD0_25),LO(drD0_02),LO(drD0_00)
  EQUB LO(drD1_00),LO(drD1_02),LO(drD1_04),LO(drD1_05),LO(drD1_06),LO(drD1_06),LO(drD1_05),LO(drD1_04),LO(drD1_03),LO(drD1_01)
  EQUB LO(drD1_00),LO(drD1_02),LO(drD1_07),LO(drD1_08),LO(drD1_09),LO(drD1_09),LO(drD1_08),LO(drD1_07),LO(drD1_03),LO(drD1_01)
  EQUB LO(drD1_00),LO(drD1_02),LO(drD1_10),LO(drD1_11),LO(drD1_12),LO(drD1_12),LO(drD1_11),LO(drD1_10),LO(drD1_03),LO(drD1_01)
  EQUB LO(drD1_00),LO(drD1_02),LO(drD1_13),LO(drD1_14),LO(drD1_15),LO(drD1_15),LO(drD1_14),LO(drD1_13),LO(drD1_03),LO(drD1_01)
  EQUB LO(drD1_01),LO(drD1_03),LO(drD1_16),LO(drD1_17),LO(drD1_18),LO(drD1_18),LO(drD1_17),LO(drD1_16),LO(drD1_02),LO(drD1_00)
  EQUB LO(drD1_01),LO(drD1_03),LO(drD1_19),LO(drD1_20),LO(drD1_21),LO(drD1_21),LO(drD1_20),LO(drD1_19),LO(drD1_02),LO(drD1_00)
  EQUB LO(drD1_01),LO(drD1_03),LO(drD1_22),LO(drD1_23),LO(drD1_24),LO(drD1_24),LO(drD1_23),LO(drD1_22),LO(drD1_02),LO(drD1_00)
  EQUB LO(drD1_01),LO(drD1_03),LO(drD1_25),LO(drD1_26),LO(drD1_27),LO(drD1_27),LO(drD1_26),LO(drD1_25),LO(drD1_02),LO(drD1_00)
.drSeqHi
  EQUB HI(drD0_00),HI(drD0_02),HI(drD0_04),HI(drD0_05),HI(drD0_06),HI(drD0_06),HI(drD0_05),HI(drD0_04),HI(drD0_03),HI(drD0_01)
  EQUB HI(drD0_00),HI(drD0_02),HI(drD0_07),HI(drD0_08),HI(drD0_09),HI(drD0_09),HI(drD0_08),HI(drD0_07),HI(drD0_03),HI(drD0_01)
  EQUB HI(drD0_00),HI(drD0_02),HI(drD0_10),HI(drD0_11),HI(drD0_12),HI(drD0_12),HI(drD0_11),HI(drD0_10),HI(drD0_03),HI(drD0_01)
  EQUB HI(drD0_00),HI(drD0_02),HI(drD0_13),HI(drD0_14),HI(drD0_15),HI(drD0_15),HI(drD0_14),HI(drD0_13),HI(drD0_03),HI(drD0_01)
  EQUB HI(drD0_01),HI(drD0_03),HI(drD0_16),HI(drD0_17),HI(drD0_18),HI(drD0_18),HI(drD0_17),HI(drD0_16),HI(drD0_02),HI(drD0_00)
  EQUB HI(drD0_01),HI(drD0_03),HI(drD0_19),HI(drD0_20),HI(drD0_21),HI(drD0_21),HI(drD0_20),HI(drD0_19),HI(drD0_02),HI(drD0_00)
  EQUB HI(drD0_01),HI(drD0_03),HI(drD0_22),HI(drD0_23),HI(drD0_24),HI(drD0_24),HI(drD0_23),HI(drD0_22),HI(drD0_02),HI(drD0_00)
  EQUB HI(drD0_01),HI(drD0_03),HI(drD0_25),HI(drD0_26),HI(drD0_27),HI(drD0_27),HI(drD0_26),HI(drD0_25),HI(drD0_02),HI(drD0_00)
  EQUB HI(drD1_00),HI(drD1_02),HI(drD1_04),HI(drD1_05),HI(drD1_06),HI(drD1_06),HI(drD1_05),HI(drD1_04),HI(drD1_03),HI(drD1_01)
  EQUB HI(drD1_00),HI(drD1_02),HI(drD1_07),HI(drD1_08),HI(drD1_09),HI(drD1_09),HI(drD1_08),HI(drD1_07),HI(drD1_03),HI(drD1_01)
  EQUB HI(drD1_00),HI(drD1_02),HI(drD1_10),HI(drD1_11),HI(drD1_12),HI(drD1_12),HI(drD1_11),HI(drD1_10),HI(drD1_03),HI(drD1_01)
  EQUB HI(drD1_00),HI(drD1_02),HI(drD1_13),HI(drD1_14),HI(drD1_15),HI(drD1_15),HI(drD1_14),HI(drD1_13),HI(drD1_03),HI(drD1_01)
  EQUB HI(drD1_01),HI(drD1_03),HI(drD1_16),HI(drD1_17),HI(drD1_18),HI(drD1_18),HI(drD1_17),HI(drD1_16),HI(drD1_02),HI(drD1_00)
  EQUB HI(drD1_01),HI(drD1_03),HI(drD1_19),HI(drD1_20),HI(drD1_21),HI(drD1_21),HI(drD1_20),HI(drD1_19),HI(drD1_02),HI(drD1_00)
  EQUB HI(drD1_01),HI(drD1_03),HI(drD1_22),HI(drD1_23),HI(drD1_24),HI(drD1_24),HI(drD1_23),HI(drD1_22),HI(drD1_02),HI(drD1_00)
  EQUB HI(drD1_01),HI(drD1_03),HI(drD1_25),HI(drD1_26),HI(drD1_27),HI(drD1_27),HI(drD1_26),HI(drD1_25),HI(drD1_02),HI(drD1_00)
.drRSeqLo
  EQUB LO(drR0_00),LO(drR0_00),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_01),LO(drR0_01)
  EQUB LO(drR0_00),LO(drR0_00),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_01),LO(drR0_01)
  EQUB LO(drR0_00),LO(drR0_00),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_01),LO(drR0_01)
  EQUB LO(drR0_00),LO(drR0_00),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_01),LO(drR0_01)
  EQUB LO(drR0_01),LO(drR0_01),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_00),LO(drR0_00)
  EQUB LO(drR0_01),LO(drR0_01),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_00),LO(drR0_00)
  EQUB LO(drR0_01),LO(drR0_01),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_00),LO(drR0_00)
  EQUB LO(drR0_01),LO(drR0_01),LO(drR0_02),LO(drR0_02),LO(drR0_03),LO(drR0_03),LO(drR0_02),LO(drR0_02),LO(drR0_00),LO(drR0_00)
  EQUB LO(drR1_00),LO(drR1_00),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_01),LO(drR1_01)
  EQUB LO(drR1_00),LO(drR1_00),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_01),LO(drR1_01)
  EQUB LO(drR1_00),LO(drR1_00),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_01),LO(drR1_01)
  EQUB LO(drR1_00),LO(drR1_00),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_01),LO(drR1_01)
  EQUB LO(drR1_01),LO(drR1_01),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_00),LO(drR1_00)
  EQUB LO(drR1_01),LO(drR1_01),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_00),LO(drR1_00)
  EQUB LO(drR1_01),LO(drR1_01),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_00),LO(drR1_00)
  EQUB LO(drR1_01),LO(drR1_01),LO(drR1_02),LO(drR1_02),LO(drR1_03),LO(drR1_03),LO(drR1_02),LO(drR1_02),LO(drR1_00),LO(drR1_00)
.drRSeqHi
  EQUB HI(drR0_00),HI(drR0_00),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_01),HI(drR0_01)
  EQUB HI(drR0_00),HI(drR0_00),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_01),HI(drR0_01)
  EQUB HI(drR0_00),HI(drR0_00),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_01),HI(drR0_01)
  EQUB HI(drR0_00),HI(drR0_00),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_01),HI(drR0_01)
  EQUB HI(drR0_01),HI(drR0_01),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_00),HI(drR0_00)
  EQUB HI(drR0_01),HI(drR0_01),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_00),HI(drR0_00)
  EQUB HI(drR0_01),HI(drR0_01),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_00),HI(drR0_00)
  EQUB HI(drR0_01),HI(drR0_01),HI(drR0_02),HI(drR0_02),HI(drR0_03),HI(drR0_03),HI(drR0_02),HI(drR0_02),HI(drR0_00),HI(drR0_00)
  EQUB HI(drR1_00),HI(drR1_00),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_01),HI(drR1_01)
  EQUB HI(drR1_00),HI(drR1_00),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_01),HI(drR1_01)
  EQUB HI(drR1_00),HI(drR1_00),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_01),HI(drR1_01)
  EQUB HI(drR1_00),HI(drR1_00),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_01),HI(drR1_01)
  EQUB HI(drR1_01),HI(drR1_01),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_00),HI(drR1_00)
  EQUB HI(drR1_01),HI(drR1_01),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_00),HI(drR1_00)
  EQUB HI(drR1_01),HI(drR1_01),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_00),HI(drR1_00)
  EQUB HI(drR1_01),HI(drR1_01),HI(drR1_02),HI(drR1_02),HI(drR1_03),HI(drR1_03),HI(drR1_02),HI(drR1_02),HI(drR1_00),HI(drR1_00)

.drPrgLo
  EQUB LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0),LO(drPrg0_0)
  EQUB LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1),LO(drPrg0_1)
  EQUB LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2),LO(drPrg0_2)
  EQUB LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3),LO(drPrg0_3)
  EQUB LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4),LO(drPrg0_4)
  EQUB LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5),LO(drPrg0_5)
  EQUB LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6),LO(drPrg0_6)
  EQUB LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7),LO(drPrg0_7)
  EQUB LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0),LO(drPrg1_0)
  EQUB LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1),LO(drPrg1_1)
  EQUB LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2),LO(drPrg1_2)
  EQUB LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3),LO(drPrg1_3)
  EQUB LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4),LO(drPrg1_4)
  EQUB LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5),LO(drPrg1_5)
  EQUB LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6),LO(drPrg1_6)
  EQUB LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7),LO(drPrg1_7)
.drPrgHi
  EQUB HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0),HI(drPrg0_0)
  EQUB HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1),HI(drPrg0_1)
  EQUB HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2),HI(drPrg0_2)
  EQUB HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3),HI(drPrg0_3)
  EQUB HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4),HI(drPrg0_4)
  EQUB HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5),HI(drPrg0_5)
  EQUB HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6),HI(drPrg0_6)
  EQUB HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7),HI(drPrg0_7)
  EQUB HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0),HI(drPrg1_0)
  EQUB HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1),HI(drPrg1_1)
  EQUB HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2),HI(drPrg1_2)
  EQUB HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3),HI(drPrg1_3)
  EQUB HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4),HI(drPrg1_4)
  EQUB HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5),HI(drPrg1_5)
  EQUB HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6),HI(drPrg1_6)
  EQUB HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7),HI(drPrg1_7)
.drRPrgLo
  EQUB LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0),LO(drRPrg0_0)
  EQUB LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1),LO(drRPrg0_1)
  EQUB LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2),LO(drRPrg0_2)
  EQUB LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3),LO(drRPrg0_3)
  EQUB LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4),LO(drRPrg0_4)
  EQUB LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5),LO(drRPrg0_5)
  EQUB LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6),LO(drRPrg0_6)
  EQUB LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7),LO(drRPrg0_7)
  EQUB LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0),LO(drRPrg1_0)
  EQUB LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1),LO(drRPrg1_1)
  EQUB LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2),LO(drRPrg1_2)
  EQUB LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3),LO(drRPrg1_3)
  EQUB LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4),LO(drRPrg1_4)
  EQUB LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5),LO(drRPrg1_5)
  EQUB LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6),LO(drRPrg1_6)
  EQUB LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7),LO(drRPrg1_7)
.drRPrgHi
  EQUB HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0),HI(drRPrg0_0)
  EQUB HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1),HI(drRPrg0_1)
  EQUB HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2),HI(drRPrg0_2)
  EQUB HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3),HI(drRPrg0_3)
  EQUB HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4),HI(drRPrg0_4)
  EQUB HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5),HI(drRPrg0_5)
  EQUB HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6),HI(drRPrg0_6)
  EQUB HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7),HI(drRPrg0_7)
  EQUB HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0),HI(drRPrg1_0)
  EQUB HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1),HI(drRPrg1_1)
  EQUB HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2),HI(drRPrg1_2)
  EQUB HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3),HI(drRPrg1_3)
  EQUB HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4),HI(drRPrg1_4)
  EQUB HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5),HI(drRPrg1_5)
  EQUB HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6),HI(drRPrg1_6)
  EQUB HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7),HI(drRPrg1_7)

\ Sprite row -> position in that sequence; &FF means the row is
\ not the rotor's (a digit row, or one of the three blank ones).
\ Only the wrap fallback needs it - the fast path knows the
\ shape and walks the list straight through.
.drSeqIdx
  EQUB &00,&01,&02,&03,&04,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&05,&06,&07,&08,&09,&FF
.drMul10                     \ phase * 10
  EQUB &00,&0A,&14,&1E,&28,&32,&3C,&46


\ drBlkSave6 - the digit block's column 6, all eight rows.
\ Nothing owns it: it is only ever written by the last
\ position's spill under a shift. See SprDigitBlock.
.drBlkSave6
  LDY #6*UNIT_BYTES
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA (rowp+14),Y : STA (rowq+14),Y
  RTS

\ Glyph dispatch, at index (shift AND 1)*10 + digit.
.drGlyphLo
  EQUB LO(drGlyph0_0),LO(drGlyph0_1),LO(drGlyph0_2),LO(drGlyph0_3),LO(drGlyph0_4),LO(drGlyph0_5),LO(drGlyph0_6),LO(drGlyph0_7),LO(drGlyph0_8),LO(drGlyph0_9)
  EQUB LO(drGlyph1_0),LO(drGlyph1_1),LO(drGlyph1_2),LO(drGlyph1_3),LO(drGlyph1_4),LO(drGlyph1_5),LO(drGlyph1_6),LO(drGlyph1_7),LO(drGlyph1_8),LO(drGlyph1_9)
.drGlyphHi
  EQUB HI(drGlyph0_0),HI(drGlyph0_1),HI(drGlyph0_2),HI(drGlyph0_3),HI(drGlyph0_4),HI(drGlyph0_5),HI(drGlyph0_6),HI(drGlyph0_7),HI(drGlyph0_8),HI(drGlyph0_9)
  EQUB HI(drGlyph1_0),HI(drGlyph1_1),HI(drGlyph1_2),HI(drGlyph1_3),HI(drGlyph1_4),HI(drGlyph1_5),HI(drGlyph1_6),HI(drGlyph1_7),HI(drGlyph1_8),HI(drGlyph1_9)

\ The three digits of each droid type, as glyph numbers.
.drDigit0
  EQUB &00,&01,&01,&02,&02,&02,&03,&03,&04,&04,&04,&05
  EQUB &05,&05,&06,&06,&06,&07,&07,&07,&08,&08,&08,&09
.drDigit1
  EQUB &00,&02,&03,&04,&04,&09,&00,&02,&02,&07,&09,&01
  EQUB &07,&09,&01,&01,&02,&01,&04,&05,&02,&03,&08,&09
.drDigit2
  EQUB &01,&03,&09,&07,&09,&06,&02,&09,&00,&06,&03,&06
  EQUB &01,&08,&04,&05,&09,&01,&02,&01,&01,&04,&03,&09

\ ==== code: sizes differ between the banks ================
\ ---- shift 0 px -------------------------------------
.drD0_00
  SCANSTEP
  RTS
.drD0_01
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_02
  SCANSTEP
  RTS
.drD0_03
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_04
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_05
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_06
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_07
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_08
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_09
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_10
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_11
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_12
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_13
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_14
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_15
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_16
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_17
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_18
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_19
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_20
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_21
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_22
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_23
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&99 : ORA colPix+4 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_24
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_25
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_26
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  SCANSTEP
  RTS
.drD0_27
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drR0_00
  SCANSTEP
  RTS
.drR0_01
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR0_02
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR0_03
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
\ ---- shift 1 px -------------------------------------
.drD1_00
  SCANSTEP
  RTS
.drD1_01
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_02
  SCANSTEP
  RTS
.drD1_03
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_04
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_05
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_06
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_07
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_08
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&99 : ORA colPix+4 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_09
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_10
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_11
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_12
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_13
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_14
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_15
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_16
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_17
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_18
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_19
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_20
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_21
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_22
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_23
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_24
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_25
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_26
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  SCANSTEP
  RTS
.drD1_27
  LDY #0*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  SCANSTEP
  RTS
.drR1_00
  SCANSTEP
  RTS
.drR1_01
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR1_02
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR1_03
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS

\ Five rows of restore inlined. Only the column set matters, and
\ that depends on shift and phase>>2 alone - so eight of these
\ cover all sixteen sequences. The last row of the bottom half
\ does not walk: nothing reads the pointers after it.
.drRHalf0_0_0
  SCANSTEP
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf0_0_1
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  RTS
.drRHalf0_1_0
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf0_1_1
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  SCANSTEP
  RTS
.drRHalf1_0_0
  SCANSTEP
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf1_0_1
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  RTS
.drRHalf1_1_0
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf1_1_1
  LDY #0*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  SCANSTEP
  RTS

.drPrg0_0
  JSR drD0_00
  JSR drD0_02
  JSR drD0_04
  JSR drD0_05
  JSR drD0_06
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_06
  JSR drD0_05
  JSR drD0_04
  JSR drD0_03
  JMP drD0_01
.drPrg0_1
  JSR drD0_00
  JSR drD0_02
  JSR drD0_07
  JSR drD0_08
  JSR drD0_09
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_09
  JSR drD0_08
  JSR drD0_07
  JSR drD0_03
  JMP drD0_01
.drPrg0_2
  JSR drD0_00
  JSR drD0_02
  JSR drD0_10
  JSR drD0_11
  JSR drD0_12
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_12
  JSR drD0_11
  JSR drD0_10
  JSR drD0_03
  JMP drD0_01
.drPrg0_3
  JSR drD0_00
  JSR drD0_02
  JSR drD0_13
  JSR drD0_14
  JSR drD0_15
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_15
  JSR drD0_14
  JSR drD0_13
  JSR drD0_03
  JMP drD0_01
.drPrg0_4
  JSR drD0_01
  JSR drD0_03
  JSR drD0_16
  JSR drD0_17
  JSR drD0_18
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_18
  JSR drD0_17
  JSR drD0_16
  JSR drD0_02
  JMP drD0_00
.drPrg0_5
  JSR drD0_01
  JSR drD0_03
  JSR drD0_19
  JSR drD0_20
  JSR drD0_21
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_21
  JSR drD0_20
  JSR drD0_19
  JSR drD0_02
  JMP drD0_00
.drPrg0_6
  JSR drD0_01
  JSR drD0_03
  JSR drD0_22
  JSR drD0_23
  JSR drD0_24
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_24
  JSR drD0_23
  JSR drD0_22
  JSR drD0_02
  JMP drD0_00
.drPrg0_7
  JSR drD0_01
  JSR drD0_03
  JSR drD0_25
  JSR drD0_26
  JSR drD0_27
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD0_27
  JSR drD0_26
  JSR drD0_25
  JSR drD0_02
  JMP drD0_00
.drPrg1_0
  JSR drD1_00
  JSR drD1_02
  JSR drD1_04
  JSR drD1_05
  JSR drD1_06
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_06
  JSR drD1_05
  JSR drD1_04
  JSR drD1_03
  JMP drD1_01
.drPrg1_1
  JSR drD1_00
  JSR drD1_02
  JSR drD1_07
  JSR drD1_08
  JSR drD1_09
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_09
  JSR drD1_08
  JSR drD1_07
  JSR drD1_03
  JMP drD1_01
.drPrg1_2
  JSR drD1_00
  JSR drD1_02
  JSR drD1_10
  JSR drD1_11
  JSR drD1_12
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_12
  JSR drD1_11
  JSR drD1_10
  JSR drD1_03
  JMP drD1_01
.drPrg1_3
  JSR drD1_00
  JSR drD1_02
  JSR drD1_13
  JSR drD1_14
  JSR drD1_15
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_15
  JSR drD1_14
  JSR drD1_13
  JSR drD1_03
  JMP drD1_01
.drPrg1_4
  JSR drD1_01
  JSR drD1_03
  JSR drD1_16
  JSR drD1_17
  JSR drD1_18
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_18
  JSR drD1_17
  JSR drD1_16
  JSR drD1_02
  JMP drD1_00
.drPrg1_5
  JSR drD1_01
  JSR drD1_03
  JSR drD1_19
  JSR drD1_20
  JSR drD1_21
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_21
  JSR drD1_20
  JSR drD1_19
  JSR drD1_02
  JMP drD1_00
.drPrg1_6
  JSR drD1_01
  JSR drD1_03
  JSR drD1_22
  JSR drD1_23
  JSR drD1_24
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_24
  JSR drD1_23
  JSR drD1_22
  JSR drD1_02
  JMP drD1_00
.drPrg1_7
  JSR drD1_01
  JSR drD1_03
  JSR drD1_25
  JSR drD1_26
  JSR drD1_27
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD1_27
  JSR drD1_26
  JSR drD1_25
  JSR drD1_02
  JMP drD1_00

.drRPrg0_0
  JSR drRHalf0_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_0_1
.drRPrg0_1
  JSR drRHalf0_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_0_1
.drRPrg0_2
  JSR drRHalf0_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_0_1
.drRPrg0_3
  JSR drRHalf0_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_0_1
.drRPrg0_4
  JSR drRHalf0_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_1_1
.drRPrg0_5
  JSR drRHalf0_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_1_1
.drRPrg0_6
  JSR drRHalf0_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_1_1
.drRPrg0_7
  JSR drRHalf0_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf0_1_1
.drRPrg1_0
  JSR drRHalf1_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_0_1
.drRPrg1_1
  JSR drRHalf1_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_0_1
.drRPrg1_2
  JSR drRHalf1_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_0_1
.drRPrg1_3
  JSR drRHalf1_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_0_1
.drRPrg1_4
  JSR drRHalf1_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_1_1
.drRPrg1_5
  JSR drRHalf1_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_1_1
.drRPrg1_6
  JSR drRHalf1_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_1_1
.drRPrg1_7
  JSR drRHalf1_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf1_1_1
.drGlyph0_0
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&99 : ORA colPix+4 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&99 : ORA colPix+4 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&99 : ORA colPix+4 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_1
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_2
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph0_3
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&11 : ORA colPix+9 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_4
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_5
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_6
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&11 : ORA colPix+9 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_7
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  RTS
.drGlyph0_8
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&99 : ORA colPix+4 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&99 : ORA colPix+4 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph0_9
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&99 : ORA colPix+4 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&99 : ORA colPix+4 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&99 : ORA colPix+4 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph1_0
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&99 : ORA colPix+4 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&99 : ORA colPix+4 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&99 : ORA colPix+4 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_1
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&11 : ORA colPix+9 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_2
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph1_3
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&88 : ORA colPix+5 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_4
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_5
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_6
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&99 : ORA colPix+4 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&99 : ORA colPix+4 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&99 : ORA colPix+4 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&88 : ORA colPix+5 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_7
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph1_8
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&99 : ORA colPix+4 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&99 : ORA colPix+4 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph1_9
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&11 : ORA colPix+9 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
