\ ============================================================
\ droids.asm
\ GENERATED by tools/export_droids.py - do not edit by hand.
\ Source: paradroid_ce.lst (Paradroid, C64 - original/CE lineage)
\ 24 droid types, 8 rotor phases, waypoints for 16 decks
\ ============================================================

\ The half of the droid export that is GAME DATA, not sprite: speeds,
\ waypoints and the per-deck type base. These live in the DATA bank
\ with the tiles and levels, because the sprite bank is only paged
\ in around the blitter and none of this is read there.

\ ---- droid artwork, read only by the wrap fallback --------
\ Every distinct row, seven bytes each, unshifted; the shift is
\ done on the fly by SprFetchRow and the masks are derived from
\ a table, not stored.
\
\ IN THIS BANK RATHER THAN THE SPRITE BANK because SprFetchRow
\ is the only thing that reads it, on about one row in fifty,
\ and it pages this bank in around itself for ~24 cycles. The
\ sprite bank is the scarce one - it has to hold two compiled
\ shifts - and this is 2,079 bytes of it that need not be.
.drSprData
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&22,&77,&FF,&88,&00,&00
  EQUB &00,&99,&FF,&FF,&EE,&00,&00
  EQUB &22,&33,&FF,&FF,&FF,&88,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&33,&33,&FF,&88,&00,&00
  EQUB &00,&CC,&FF,&FF,&EE,&00,&00
  EQUB &33,&88,&FF,&FF,&FF,&88,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&33,&99,&FF,&88,&00,&00
  EQUB &00,&EE,&33,&FF,&EE,&00,&00
  EQUB &33,&EE,&33,&FF,&FF,&88,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&33,&CC,&FF,&88,&00,&00
  EQUB &00,&FF,&88,&FF,&EE,&00,&00
  EQUB &33,&FF,&88,&FF,&FF,&88,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&33,&EE,&77,&88,&00,&00
  EQUB &00,&FF,&EE,&33,&EE,&00,&00
  EQUB &33,&FF,&EE,&33,&FF,&88,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&33,&FF,&33,&88,&00,&00
  EQUB &00,&FF,&FF,&88,&EE,&00,&00
  EQUB &33,&FF,&FF,&88,&FF,&88,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&33,&FF,&99,&88,&00,&00
  EQUB &00,&FF,&FF,&EE,&66,&00,&00
  EQUB &33,&FF,&FF,&EE,&33,&88,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&33,&FF,&CC,&88,&00,&00
  EQUB &00,&FF,&FF,&FF,&22,&00,&00
  EQUB &33,&FF,&FF,&FF,&88,&88,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&33,&88,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &00,&00,&00,&00,&00,&00,&00
  EQUB &77,&CC,&77,&CC,&33,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&77,&CC,&00
  EQUB &00,&00,&00,&00,&11,&CC,&00
  EQUB &CC,&66,&CC,&66,&11,&CC,&00
  EQUB &CC,&66,&CC,&66,&11,&CC,&00
  EQUB &CC,&66,&CC,&66,&11,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&11,&CC,&00
  EQUB &77,&CC,&77,&CC,&11,&CC,&00
  EQUB &33,&CC,&FF,&CC,&FF,&EE,&00
  EQUB &77,&CC,&FF,&EE,&FF,&CC,&00
  EQUB &11,&CC,&00,&EE,&00,&00,&00
  EQUB &11,&CC,&77,&EE,&33,&CC,&00
  EQUB &11,&CC,&FF,&CC,&77,&EE,&00
  EQUB &11,&CC,&00,&00,&00,&EE,&00
  EQUB &11,&CC,&FF,&EE,&FF,&EE,&00
  EQUB &11,&CC,&FF,&EE,&FF,&CC,&00
  EQUB &33,&CC,&FF,&EE,&77,&CC,&00
  EQUB &77,&CC,&FF,&CC,&FF,&EE,&00
  EQUB &11,&CC,&00,&00,&EE,&66,&00
  EQUB &11,&CC,&33,&CC,&66,&66,&00
  EQUB &11,&CC,&77,&EE,&11,&CC,&00
  EQUB &11,&CC,&00,&EE,&11,&CC,&00
  EQUB &11,&CC,&FF,&EE,&33,&88,&00
  EQUB &11,&CC,&FF,&CC,&33,&88,&00
  EQUB &FF,&CC,&11,&CC,&FF,&EE,&00
  EQUB &FF,&EE,&33,&88,&FF,&EE,&00
  EQUB &00,&EE,&77,&00,&00,&00,&00
  EQUB &77,&EE,&FF,&EE,&11,&CC,&00
  EQUB &FF,&CC,&FF,&EE,&11,&CC,&00
  EQUB &00,&00,&00,&00,&33,&88,&00
  EQUB &FF,&EE,&11,&CC,&33,&88,&00
  EQUB &FF,&EE,&11,&CC,&77,&00,&00
  EQUB &FF,&CC,&11,&CC,&77,&CC,&00
  EQUB &FF,&EE,&33,&88,&FF,&EE,&00
  EQUB &00,&EE,&77,&00,&EE,&66,&00
  EQUB &77,&EE,&FF,&EE,&66,&66,&00
  EQUB &FF,&CC,&FF,&EE,&11,&CC,&00
  EQUB &00,&00,&00,&00,&11,&CC,&00
  EQUB &FF,&EE,&11,&CC,&33,&88,&00
  EQUB &FF,&EE,&11,&CC,&33,&88,&00
  EQUB &FF,&CC,&77,&CC,&33,&88,&00
  EQUB &FF,&EE,&FF,&EE,&33,&88,&00
  EQUB &00,&EE,&EE,&66,&77,&00,&00
  EQUB &77,&EE,&66,&66,&77,&00,&00
  EQUB &FF,&CC,&11,&CC,&CC,&CC,&00
  EQUB &00,&00,&11,&CC,&CC,&EE,&00
  EQUB &FF,&EE,&33,&88,&FF,&EE,&00
  EQUB &FF,&EE,&33,&88,&77,&CC,&00
  EQUB &FF,&EE,&77,&CC,&FF,&CC,&00
  EQUB &FF,&CC,&FF,&EE,&FF,&EE,&00
  EQUB &00,&00,&00,&00,&00,&EE,&00
  EQUB &33,&CC,&CC,&66,&77,&EE,&00
  EQUB &77,&EE,&CC,&66,&FF,&CC,&00
  EQUB &00,&EE,&CC,&66,&00,&00,&00
  EQUB &FF,&EE,&FF,&EE,&FF,&EE,&00
  EQUB &FF,&CC,&77,&CC,&FF,&EE,&00
  EQUB &FF,&EE,&FF,&CC,&77,&CC,&00
  EQUB &FF,&CC,&FF,&EE,&FF,&EE,&00
  EQUB &00,&00,&00,&EE,&EE,&66,&00
  EQUB &33,&CC,&77,&EE,&66,&66,&00
  EQUB &77,&EE,&FF,&CC,&11,&CC,&00
  EQUB &00,&EE,&00,&00,&11,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&33,&88,&00
  EQUB &FF,&CC,&FF,&EE,&33,&88,&00
  EQUB &11,&CC,&FF,&CC,&77,&CC,&00
  EQUB &33,&88,&FF,&EE,&FF,&EE,&00
  EQUB &77,&00,&00,&EE,&00,&00,&00
  EQUB &FF,&EE,&77,&EE,&CC,&66,&00
  EQUB &FF,&EE,&FF,&CC,&CC,&66,&00
  EQUB &00,&00,&00,&00,&CC,&66,&00
  EQUB &11,&CC,&FF,&EE,&FF,&EE,&00
  EQUB &11,&CC,&FF,&EE,&77,&CC,&00
  EQUB &11,&CC,&FF,&EE,&33,&88,&00
  EQUB &33,&88,&FF,&EE,&33,&88,&00
  EQUB &77,&00,&00,&00,&77,&00,&00
  EQUB &FF,&EE,&11,&CC,&77,&00,&00
  EQUB &FF,&EE,&11,&CC,&CC,&CC,&00
  EQUB &00,&00,&33,&88,&CC,&EE,&00
  EQUB &11,&CC,&33,&88,&FF,&EE,&00
  EQUB &11,&CC,&77,&00,&77,&CC,&00
  EQUB &11,&CC,&77,&CC,&FF,&EE,&00
  EQUB &33,&88,&FF,&EE,&FF,&CC,&00
  EQUB &77,&00,&EE,&66,&00,&00,&00
  EQUB &FF,&EE,&66,&66,&33,&CC,&00
  EQUB &FF,&EE,&11,&CC,&77,&EE,&00
  EQUB &00,&00,&11,&CC,&00,&EE,&00
  EQUB &11,&CC,&33,&88,&FF,&EE,&00
  EQUB &11,&CC,&33,&88,&FF,&CC,&00
  EQUB &FF,&EE,&33,&CC,&33,&88,&00
  EQUB &FF,&EE,&77,&CC,&33,&88,&00
  EQUB &EE,&00,&11,&CC,&77,&00,&00
  EQUB &FF,&CC,&11,&CC,&77,&00,&00
  EQUB &FF,&EE,&11,&CC,&CC,&CC,&00
  EQUB &00,&00,&11,&CC,&CC,&EE,&00
  EQUB &FF,&EE,&11,&CC,&FF,&EE,&00
  EQUB &FF,&CC,&11,&CC,&77,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&33,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&77,&CC,&00
  EQUB &EE,&00,&00,&00,&11,&CC,&00
  EQUB &FF,&CC,&11,&CC,&11,&CC,&00
  EQUB &FF,&EE,&11,&CC,&11,&CC,&00
  EQUB &00,&00,&33,&88,&11,&CC,&00
  EQUB &FF,&EE,&33,&88,&11,&CC,&00
  EQUB &FF,&CC,&77,&00,&11,&CC,&00
  EQUB &FF,&EE,&77,&CC,&77,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&FF,&EE,&00
  EQUB &EE,&00,&EE,&66,&CC,&66,&00
  EQUB &FF,&CC,&66,&66,&33,&88,&00
  EQUB &FF,&EE,&11,&CC,&33,&88,&00
  EQUB &00,&00,&11,&CC,&CC,&66,&00
  EQUB &FF,&EE,&33,&88,&FF,&EE,&00
  EQUB &FF,&CC,&33,&88,&77,&CC,&00
  EQUB &33,&88,&33,&CC,&11,&CC,&00
  EQUB &33,&88,&77,&CC,&33,&88,&00
  EQUB &77,&00,&11,&CC,&77,&00,&00
  EQUB &77,&00,&11,&CC,&FF,&EE,&00
  EQUB &CC,&CC,&11,&CC,&FF,&EE,&00
  EQUB &CC,&EE,&11,&CC,&00,&00,&00
  EQUB &FF,&EE,&11,&CC,&11,&CC,&00
  EQUB &77,&CC,&11,&CC,&11,&CC,&00
  EQUB &33,&88,&33,&CC,&FF,&EE,&00
  EQUB &33,&88,&77,&CC,&FF,&EE,&00
  EQUB &77,&00,&11,&CC,&EE,&00,&00
  EQUB &77,&00,&11,&CC,&FF,&CC,&00
  EQUB &CC,&CC,&11,&CC,&FF,&EE,&00
  EQUB &CC,&EE,&11,&CC,&00,&00,&00
  EQUB &FF,&EE,&11,&CC,&FF,&EE,&00
  EQUB &77,&CC,&11,&CC,&FF,&CC,&00
  EQUB &33,&88,&FF,&CC,&77,&CC,&00
  EQUB &33,&88,&FF,&EE,&FF,&EE,&00
  EQUB &77,&00,&00,&EE,&EE,&66,&00
  EQUB &77,&00,&77,&EE,&66,&66,&00
  EQUB &CC,&CC,&FF,&CC,&11,&CC,&00
  EQUB &CC,&EE,&00,&00,&11,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&33,&88,&00
  EQUB &77,&CC,&FF,&EE,&33,&88,&00
  EQUB &FF,&EE,&33,&CC,&33,&CC,&00
  EQUB &FF,&EE,&77,&CC,&77,&CC,&00
  EQUB &00,&00,&11,&CC,&11,&CC,&00
  EQUB &11,&CC,&11,&CC,&11,&CC,&00
  EQUB &11,&CC,&11,&CC,&11,&CC,&00
  EQUB &33,&88,&11,&CC,&11,&CC,&00
  EQUB &33,&88,&11,&CC,&11,&CC,&00
  EQUB &77,&00,&11,&CC,&11,&CC,&00
  EQUB &FF,&EE,&11,&CC,&FF,&CC,&00
  EQUB &FF,&EE,&33,&88,&FF,&EE,&00
  EQUB &00,&00,&77,&00,&00,&EE,&00
  EQUB &11,&CC,&FF,&EE,&77,&EE,&00
  EQUB &11,&CC,&FF,&EE,&FF,&CC,&00
  EQUB &33,&88,&00,&00,&00,&00,&00
  EQUB &33,&88,&11,&CC,&FF,&EE,&00
  EQUB &77,&00,&11,&CC,&FF,&EE,&00
  EQUB &FF,&EE,&FF,&EE,&33,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&77,&CC,&00
  EQUB &00,&00,&EE,&00,&11,&CC,&00
  EQUB &11,&CC,&FF,&CC,&11,&CC,&00
  EQUB &11,&CC,&FF,&EE,&11,&CC,&00
  EQUB &33,&88,&00,&00,&11,&CC,&00
  EQUB &33,&88,&FF,&EE,&11,&CC,&00
  EQUB &77,&00,&FF,&CC,&11,&CC,&00
  EQUB &77,&CC,&FF,&CC,&33,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&77,&CC,&00
  EQUB &CC,&66,&00,&EE,&11,&CC,&00
  EQUB &33,&88,&77,&EE,&11,&CC,&00
  EQUB &33,&88,&FF,&CC,&11,&CC,&00
  EQUB &CC,&66,&00,&00,&11,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&11,&CC,&00
  EQUB &77,&CC,&FF,&EE,&11,&CC,&00
  EQUB &77,&CC,&FF,&EE,&11,&CC,&00
  EQUB &FF,&EE,&FF,&CC,&33,&88,&00
  EQUB &CC,&66,&00,&00,&77,&00,&00
  EQUB &33,&88,&33,&CC,&FF,&EE,&00
  EQUB &33,&88,&77,&EE,&FF,&EE,&00
  EQUB &CC,&66,&00,&EE,&00,&00,&00
  EQUB &FF,&EE,&FF,&EE,&11,&CC,&00
  EQUB &77,&CC,&FF,&CC,&11,&CC,&00
  EQUB &77,&CC,&77,&CC,&FF,&EE,&00
  EQUB &FF,&EE,&FF,&EE,&FF,&CC,&00
  EQUB &CC,&66,&CC,&66,&00,&00,&00
  EQUB &33,&88,&33,&88,&33,&CC,&00
  EQUB &33,&88,&33,&88,&77,&EE,&00
  EQUB &CC,&66,&CC,&66,&00,&EE,&00
  EQUB &FF,&EE,&FF,&EE,&FF,&EE,&00
  EQUB &77,&CC,&77,&CC,&FF,&CC,&00
  EQUB &77,&CC,&77,&CC,&77,&CC,&00
  EQUB &FF,&EE,&FF,&EE,&FF,&EE,&00
  EQUB &EE,&66,&EE,&66,&EE,&66,&00
  EQUB &66,&66,&66,&66,&66,&66,&00
  EQUB &11,&CC,&11,&CC,&11,&CC,&00
  EQUB &11,&CC,&11,&CC,&11,&CC,&00
  EQUB &33,&88,&33,&88,&33,&88,&00
  EQUB &33,&88,&33,&88,&33,&88,&00
  EQUB &00,&00,&00,&00,&00,&00,&00

\ Byte offset into drSprData for sprite row r of phase p, at
\ index p*21 + r. Rows 6-13 (the number) point at the blank
\ row: they depend on the droid type, not the phase, so the
\ blitter takes them from drDigit instead.
.drOfsLo
  EQUB &00,&07,&0E,&15,&1C,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&1C,&15,&0E,&1F,&18,&C8
  EQUB &23,&2A,&31,&38,&3F,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&3F,&38,&31,&2D,&26,&C8
  EQUB &46,&4D,&54,&5B,&62,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&62,&5B,&54,&3B,&34,&C8
  EQUB &69,&70,&77,&7E,&85,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&85,&7E,&77,&49,&42,&C8
  EQUB &8C,&93,&9A,&A1,&A8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&A8,&A1,&9A,&57,&50,&C8
  EQUB &AF,&B6,&BD,&C4,&CB,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&CB,&C4,&BD,&65,&5E,&C8
  EQUB &D2,&D9,&E0,&E7,&EE,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&EE,&E7,&E0,&73,&6C,&C8
  EQUB &F5,&FC,&03,&0A,&11,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&C8,&11,&0A,&03,&81,&7A,&C8
.drOfsHi
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&00,&00,&00,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&00,&00,&00,&01,&01,&06
  EQUB &00,&00,&01,&01,&01,&06,&06,&06,&06,&06,&06,&06,&06,&06,&06,&01,&01,&01,&01,&01,&06

\ Speed in pixels per GameLoop ITERATION, straight from the
\ C64's DSpeed_t. Enemy droids use this value directly; only
\ the player chains it through PlayerSpeed_t. An iteration is
\ 2 frames here, so 1/2/4/8 becomes 0.5/1/2/4 px per frame.
.drSpeed
  EQUB &04,&01,&02,&04,&02,&01,&08,&02,&01,&04,&04,&02
  EQUB &02,&02,&01,&04,&01,&02,&02,&02,&04,&08,&01,&04

\ ---- Layer 7 combat stats -------------------------------
\ drCent is the C64's DCent_t, the hundreds digit of the
\ droid number - which rises with how dangerous the droid is,
\ so the original uses it as a CLASS index and looks the aging
\ and score tables up through it rather than through the type.
.drCent
  EQUB &00,&01,&01,&02,&02,&02,&03,&03,&04,&04,&04,&05
  EQUB &05,&05,&06,&06,&06,&07,&07,&07,&08,&08,&08,&09

\ DNum_t ($EA20): the tens and units of the droid number, as
\ PACKED BCD in one byte. With drCent above it that is the whole
\ three-digit number, which is what Layer 9's panel prints. The
\ blitter has drDigit0/1/2 for the same digits, but those live in
\ the SPRITE bank and the panel, in bank 4, cannot page it in.
.drNum
  EQUB &01,&23,&39,&47,&49,&96,&02,&29,&20,&76,&93,&16
  EQUB &71,&98,&14,&15,&29,&11,&42,&51,&21,&34,&83,&99

\ Weapon class per type: 0 = unarmed, 3 = the disruptor.
\ The player's own is weaponType, seeded from entry 0 here.
.drWeapon
  EQUB &00,&00,&00,&00,&00,&00,&00,&00,&00,&01,&00,&00
  EQUB &00,&00,&01,&01,&02,&03,&03,&01,&02,&01,&01,&02

\ DoAlertAndAging ($3E32). drAgingMask is ANDed with the
\ iteration counter, so a SMALLER mask ages the droid faster:
\ $7F for class 0 against $0F for class 9. drAlertScore pays
\ out as the alert level decays, indexed by Alert >> 6.
.drAgingMask
  EQUB &7F,&3F,&3F,&3F,&3F,&1F,&1F,&1F,&1F,&0F
.drAlertScore
  EQUB &00,&05,&0A,&19

\ What a kill is worth, by class again: KillDroid ($1C53)
\ banks it in byte_0_79 and FreePlyBullet pays it out when the
\ bullet is freed. We free the bullet at the same moment, so
\ the port pays it straight away.
.drShootScore
  EQUB &00,&19,&32,&4B,&64,&7D,&96,&AF,&C8,&FA
\ Ramming one to death pays less, except for the 999.
.drBumpScore
  EQUB &00,&0A,&14,&1E,&28,&32,&3C,&46,&50,&C8

\ Droid numbers, for reference: 0=001, 1=123, 2=139, 3=247, 4=249, 5=296, 6=302, 7=329, 8=420, 9=476, 10=493, 11=516, 12=571, 13=598, 14=614, 15=615, 16=629, 17=711, 18=742, 19=751, 20=821, 21=834, 22=883, 23=999

\ ---- waypoints ------------------------------------------
\ 3 bytes per record: char X, char Y, permitted directions.
\ Sorted by Y ascending within a deck - FindWaypoint bails
\ out as soon as it passes the droid's row.
\
\ Direction bit n gives a delta pair via the C64's overlapping
\ dirXdelta/dirYdelta tables, 0 = -speed, 1 = 0, 2 = +speed:
\   bit  7   6   5   4   3   2   1   0
\   dx   0   0   1   2   2   2   1   0
\   dy   1   2   2   2   1   0   0   0
\        W  SW   S  SE   E  NE   N  NW
DR_WP_TOTAL = 239
.wpCount
  EQUB &07,&0E,&05,&12,&11,&13,&18,&0E,&0F,&08,&14,&12,&10,&08,&11,&13
.wpOfsLo
  EQUB &00,&15,&3F,&4E,&84,&B7,&F0,&38,&62,&8F,&A7,&E3,&19,&49,&61,&94
.wpOfsHi
  EQUB &00,&00,&00,&00,&00,&00,&00,&01,&01,&01,&01,&01,&02,&02,&02,&02
.wpData
  EQUB &42,&12,&08,&4A,&12,&80,&6E,&22,&70
  EQUB &6A,&26,&1C,&72,&26,&49,&7E,&26,&80
  EQUB &6E,&2A,&07,&16,&06,&08,&36,&06,&A8
  EQUB &4E,&06,&A8,&56,&06,&80,&36,&0E,&02
  EQUB &4E,&12,&4A,&56,&12,&A8,&86,&12,&80
  EQUB &3E,&1A,&18,&56,&1A,&82,&16,&1E,&08
  EQUB &42,&1E,&85,&9A,&2A,&08,&A2,&2A,&80
  EQUB &66,&12,&48,&76,&12,&90,&3A,&16,&08
  EQUB &62,&16,&8C,&7A,&16,&81,&3A,&06,&28
  EQUB &7A,&06,&A8,&9A,&06,&A0,&56,&12,&28
  EQUB &66,&12,&90,&3A,&1E,&0A,&56,&1E,&A2
  EQUB &72,&1E,&29,&7A,&1E,&A8,&9A,&1E,&82
  EQUB &56,&2A,&0A,&72,&2A,&82,&86,&2A,&48
  EQUB &8E,&2A,&A0,&26,&36,&08,&7A,&36,&86
  EQUB &8E,&36,&0A,&9A,&36,&80,&16,&06,&08
  EQUB &42,&06,&20,&1E,&0E,&20,&42,&0E,&80
  EQUB &52,&0E,&28,&76,&0E,&80,&3A,&16,&2C
  EQUB &52,&16,&82,&32,&1E,&08,&3A,&1E,&8A
  EQUB &9E,&1E,&80,&3A,&2A,&1A,&66,&2A,&80
  EQUB &1E,&2E,&08,&3E,&2E,&21,&16,&36,&02
  EQUB &3E,&36,&80,&16,&06,&28,&32,&06,&A0
  EQUB &32,&0E,&0A,&46,&0E,&80,&5E,&0E,&20
  EQUB &16,&1A,&0A,&26,&1A,&A8,&32,&1A,&A8
  EQUB &5E,&1A,&8A,&7A,&1A,&90,&7E,&1E,&09
  EQUB &9E,&1E,&80,&26,&26,&52,&22,&2A,&0C
  EQUB &2A,&2A,&81,&32,&2A,&2A,&52,&2A,&80
  EQUB &16,&36,&08,&32,&36,&82,&16,&0E,&28
  EQUB &2E,&0E,&A8,&3A,&0E,&A8,&52,&0E,&90
  EQUB &5A,&16,&09,&6A,&16,&A8,&82,&16,&A0
  EQUB &82,&1A,&0A,&8A,&1A,&B0,&5A,&1E,&28
  EQUB &62,&1E,&80,&8E,&1E,&49,&9E,&1E,&80
  EQUB &4A,&22,&20,&6E,&22,&48,&8A,&22,&86
  EQUB &62,&26,&28,&6A,&26,&86,&2E,&2E,&02
  EQUB &3A,&2E,&0A,&4A,&2E,&8A,&5A,&2E,&8A
  EQUB &62,&2E,&82,&16,&36,&02,&32,&0A,&20
  EQUB &26,&16,&08,&32,&16,&8A,&5E,&16,&20
  EQUB &46,&1E,&20,&5E,&1E,&28,&76,&1E,&A8
  EQUB &92,&1E,&80,&76,&22,&02,&22,&2A,&08
  EQUB &32,&2A,&82,&36,&2E,&01,&46,&2E,&82
  EQUB &5E,&2E,&80,&26,&16,&28,&32,&16,&A8
  EQUB &5E,&16,&A0,&6E,&16,&80,&32,&1E,&0A
  EQUB &56,&1E,&A0,&7A,&1E,&48,&8A,&1E,&80
  EQUB &5E,&22,&08,&6E,&22,&0A,&76,&22,&84
  EQUB &26,&2A,&0A,&36,&2A,&80,&46,&2E,&04
  EQUB &56,&2E,&80,&4E,&0E,&40,&3E,&16,&28
  EQUB &46,&16,&8C,&5A,&16,&A0,&5A,&1E,&0A
  EQUB &7A,&1E,&80,&3E,&2A,&0A,&4E,&2A,&80
  EQUB &56,&06,&08,&86,&06,&20,&22,&0A,&10
  EQUB &36,&0A,&80,&2A,&12,&20,&3E,&12,&89
  EQUB &56,&12,&92,&5A,&16,&29,&86,&16,&88
  EQUB &9A,&16,&A0,&82,&26,&18,&9A,&26,&82
  EQUB &2A,&2A,&22,&4E,&2A,&88,&5A,&2A,&8A
  EQUB &7A,&2A,&A8,&86,&2A,&81,&2A,&3A,&08
  EQUB &4E,&3A,&02,&7A,&3A,&02,&22,&06,&60
  EQUB &2E,&06,&A0,&4E,&06,&A0,&9A,&06,&80
  EQUB &1E,&0A,&08,&5A,&0A,&08,&8E,&0A,&28
  EQUB &96,&0A,&20,&22,&0E,&03,&5A,&12,&12
  EQUB &6E,&26,&21,&2E,&32,&40,&2A,&36,&08
  EQUB &4E,&36,&0A,&6E,&36,&82,&8E,&36,&82
  EQUB &96,&36,&08,&9A,&36,&02,&32,&06,&28
  EQUB &3A,&06,&A8,&4A,&06,&20,&6A,&06,&A0
  EQUB &8A,&06,&80,&3A,&12,&12,&3E,&16,&21
  EQUB &5A,&16,&20,&7A,&16,&20,&3E,&2A,&02
  EQUB &32,&3A,&0A,&4A,&3A,&88,&5A,&3A,&8A
  EQUB &6A,&3A,&8A,&7A,&3A,&8A,&8A,&3A,&82
  EQUB &4E,&06,&08,&66,&06,&20,&5A,&12,&20
  EQUB &4E,&2A,&02,&66,&2E,&02,&56,&32,&01
  EQUB &5A,&32,&8A,&6A,&32,&81,&7A,&06,&08
  EQUB &8A,&06,&20,&C2,&0A,&20,&32,&0E,&10
  EQUB &36,&12,&09,&56,&12,&A0,&C2,&16,&4A
  EQUB &D2,&16,&80,&4A,&1E,&08,&56,&1E,&8A
  EQUB &7A,&1E,&82,&B6,&22,&04,&2E,&2A,&08
  EQUB &3E,&2A,&90,&42,&2E,&09,&7A,&2E,&82
  EQUB &8A,&2E,&80,&56,&06,&40,&5E,&06,&A8
  EQUB &76,&06,&A8,&8A,&06,&A0,&2E,&0E,&08
  EQUB &4E,&0E,&88,&5E,&0E,&2A,&6A,&0E,&80
  EQUB &B6,&0E,&20,&B6,&16,&0A,&C2,&16,&80
  EQUB &76,&1E,&02,&5E,&22,&02,&6E,&26,&28
  EQUB &76,&26,&A8,&8A,&26,&82,&56,&2E,&08
  EQUB &6E,&2E,&82,&76,&36,&20

\ Per-deck droid type base, from the C64's deckDroidBase.
\ NextLevel adds shipLevel and a random spread on top; that
\ arrives with shipLevel in Layer 6. Deck counts are already
\ exported as deckDroids in levels.asm.
.deckDroidBase
  EQUB &0A,&0D,&00,&02,&03,&01,&05,&07,&11,&07,&11,&13,&0F,&0D,&07,&08

