\ ============================================================
\ droidinfo.asm - GENERATED by tools/export_droidinfo.py
\ ============================================================
\ DroidInfo_dat ($EB00), 24 records of 64 bytes, one per droid
\ type. See the tool for the layout; in short:
\
\   dbiStats   8 bytes a type - the original's record bytes 8-15:
\              height (two BCD nibbles), weight, then the token
\              indices for drive, brain, armament and three sensors
\   dbiDesc    the description, a token list ending $FF, with $FE
\              a sentence break. Packed and pointed at, because the
\              lengths run 8 to 35 against a 40-byte stride
\
\ THE INTRO SPRITE IMAGES (record bytes 0-7) ARE NOT HERE. They
\ are the C64's 48x84 portrait, which the port does not have and
\ cannot build - see docs/layer-9-hud.md.

GEN_DBI_TYPES = 24
GEN_DBI_STATS = 8

\ height, weight, drive, brain, armament, sensor 1, 2, 3
.dbiStats
  EQUB &00, &1B, &1A, &19, &4F, &32, &32, &32  \ 0
  EQUB &37, &55, &1E, &19, &19, &1F, &23, &32  \ 1
  EQUB &22, &3D, &1A, &19, &19, &1F, &32, &32  \ 2
  EQUB &56, &4E, &1A, &31, &19, &1F, &32, &32  \ 3
  EQUB &63, &53, &25, &31, &19, &1F, &32, &32  \ 4
  EQUB &20, &2F, &1E, &31, &19, &1F, &32, &32  \ 5
  EQUB &07, &17, &1A, &19, &19, &1F, &32, &32  \ 6
  EQUB &07, &1F, &1D, &19, &19, &1F, &32, &32  \ 7
  EQUB &41, &39, &1E, &31, &19, &1F, &32, &32  \ 8
  EQUB &32, &2A, &1A, &31, &4F, &1F, &23, &32  \ 9
  EQUB &48, &33, &1A, &31, &19, &1F, &32, &32  \ 10
  EQUB &57, &4A, &1B, &31, &19, &1F, &32, &32  \ 11
  EQUB &76, &3E, &1B, &31, &19, &1F, &32, &32  \ 12
  EQUB &72, &5D, &1B, &31, &19, &1F, &32, &32  \ 13
  EQUB &93, &79, &1B, &31, &40, &1F, &22, &32  \ 14
  EQUB &20, &1D, &1A, &31, &4F, &1F, &23, &32  \ 15
  EQUB &09, &3B, &1E, &31, &4F, &1F, &22, &32  \ 16
  EQUB &93, &66, &1B, &31, &41, &21, &24, &32  \ 17
  EQUB &87, &8C, &1B, &31, &41, &1F, &24, &32  \ 18
  EQUB &93, &E3, &1B, &31, &4F, &1F, &32, &32  \ 19
  EQUB &00, &1C, &1A, &31, &4F, &1F, &24, &23  \ 20
  EQUB &10, &22, &1A, &31, &4F, &1F, &24, &32  \ 21
  EQUB &62, &4F, &1D, &31, &C5, &1F, &24, &32  \ 22
  EQUB &87, &A2, &1A, &D8, &4F, &23, &24, &22  \ 23

.dbiDescLo
  EQUB LO(dbiDesc0), LO(dbiDesc1), LO(dbiDesc2), LO(dbiDesc3), LO(dbiDesc4), LO(dbiDesc5), LO(dbiDesc6), LO(dbiDesc7)
  EQUB LO(dbiDesc8), LO(dbiDesc9), LO(dbiDesc10), LO(dbiDesc11), LO(dbiDesc12), LO(dbiDesc13), LO(dbiDesc14), LO(dbiDesc15)
  EQUB LO(dbiDesc16), LO(dbiDesc17), LO(dbiDesc18), LO(dbiDesc19), LO(dbiDesc20), LO(dbiDesc21), LO(dbiDesc22), LO(dbiDesc23)
.dbiDescHi
  EQUB HI(dbiDesc0), HI(dbiDesc1), HI(dbiDesc2), HI(dbiDesc3), HI(dbiDesc4), HI(dbiDesc5), HI(dbiDesc6), HI(dbiDesc7)
  EQUB HI(dbiDesc8), HI(dbiDesc9), HI(dbiDesc10), HI(dbiDesc11), HI(dbiDesc12), HI(dbiDesc13), HI(dbiDesc14), HI(dbiDesc15)
  EQUB HI(dbiDesc16), HI(dbiDesc17), HI(dbiDesc18), HI(dbiDesc19), HI(dbiDesc20), HI(dbiDesc21), HI(dbiDesc22), HI(dbiDesc23)

.dbiDesc
.dbiDesc0
  EQUB &0A, &50, &00, &37, &FE, &2A, &51, &33, &52, &53, &61, &54
  EQUB &55, &0A, &56, &3D, &57, &58, &FE, &4F, &59, &5A, &5B, &FF
.dbiDesc1
  EQUB &34, &35, &01, &0A, &FE, &36, &37, &38, &39, &3A, &3B, &2E
  EQUB &3C, &3D, &3E, &3F, &FF
.dbiDesc2
  EQUB &8A, &74, &75, &76, &2E, &3E, &8B, &8C, &8D, &2C, &35, &FE
  EQUB &8E, &8C, &8F, &33, &43, &2E, &90, &35, &FE, &91, &33, &92
  EQUB &DC, &93, &FF
.dbiDesc3
  EQUB &26, &28, &02, &0A, &FE, &2B, &2C, &29, &2D, &2E, &2F, &29
  EQUB &1A, &30, &FF
.dbiDesc4
  EQUB &94, &5C, &2C, &29, &1A, &02, &0A, &FF
.dbiDesc5
  EQUB &2A, &0A, &33, &43, &95, &56, &96, &97, &FE, &3D, &98, &33
  EQUB &5B, &99, &29, &4E, &FE, &4C, &74, &9A, &53, &9B, &9C, &FF
.dbiDesc6
  EQUB &36, &37, &56, &9D, &9E, &9F, &FE, &A0, &33, &5B, &99, &29
  EQUB &A1, &A2, &FF
.dbiDesc7
  EQUB &A3, &A4, &03, &0A, &FE, &8C, &1D, &A5, &A6, &99, &9E, &3B
  EQUB &FF
.dbiDesc8
  EQUB &48, &04, &0A, &FE, &A7, &2E, &11, &04, &A8, &A9, &FF
.dbiDesc9
  EQUB &3F, &04, &0A, &FE, &77, &78, &AA, &AB, &2E, &AC, &AD, &81
  EQUB &2E, &29, &3F, &AE, &FE, &66, &3B, &4C, &AF, &29, &B0, &B1
  EQUB &59, &B2, &78, &3D, &B3, &2C, &B4, &FF
.dbiDesc10
  EQUB &E9, &04, &0B, &FE, &BA, &5C, &61, &AC, &8E, &E4, &E8, &FF
.dbiDesc11
  EQUB &A3, &05, &0B, &FE, &B5, &2E, &AC, &AD, &34, &A9, &B6, &B7
  EQUB &FE, &B8, &B9, &B2, &FF
.dbiDesc12
  EQUB &BA, &05, &0B, &FE, &B2, &78, &29, &3F, &FF
.dbiDesc13
  EQUB &3D, &E2, &E3, &37, &FE, &B5, &2E, &54, &29, &64, &99, &8E
  EQUB &E4, &FF
.dbiDesc14
  EQUB &42, &08, &06, &0B, &FE, &43, &2E, &44, &45, &2C, &29, &3F
  EQUB &46, &47, &FE, &3D, &48, &49, &4A, &37, &FF
.dbiDesc15
  EQUB &E3, &06, &0B, &FE, &B7, &E1, &4C, &74, &29, &EB, &EC, &FE
  EQUB &B4, &59, &DF, &BD, &EA, &FF
.dbiDesc16
  EQUB &48, &06, &0B, &FE, &4F, &59, &4C, &4D, &29, &5A, &FE, &B4
  EQUB &59, &5B, &99, &3D, &9E, &ED, &A2, &FE, &DB, &F0, &77, &78
  EQUB &E5, &EF, &99, &29, &EE, &5C, &FF
.dbiDesc17
  EQUB &27, &28, &07, &0B, &FE, &41, &33, &4C, &4D, &29, &4E, &FE
  EQUB &2B, &2C, &29, &2D, &38, &BB, &78, &29, &BC, &FF
.dbiDesc18
  EQUB &2A, &5C, &33, &29, &2B, &95, &43, &74, &29, &BC, &FF
.dbiDesc19
  EQUB &BD, &27, &28, &07, &0B, &FE, &B7, &3D, &F1, &F2, &F7, &F6
  EQUB &F3, &BB, &FE, &B4, &59, &29, &39, &C3, &07, &F4, &F5, &4C
  EQUB &FF
.dbiDesc20
  EQUB &3D, &BD, &BE, &1A, &5D, &33, &77, &4D, &2A, &0B, &FE, &91
  EQUB &61, &BF, &29, &3F, &53, &65, &47, &C0, &C1, &C0, &C2, &74
  EQUB &C3, &C4, &FF
.dbiDesc21
  EQUB &A3, &A4, &1A, &08, &0B, &FE, &77, &78, &E5, &E6, &1A, &5D
  EQUB &FE, &2A, &0B, &33, &BD, &E7, &49, &33, &4B, &BE, &FF
.dbiDesc22
  EQUB &2A, &0B, &DA, &73, &46, &C6, &C7, &FE, &56, &C8, &CA, &C9
  EQUB &91, &CB, &CC, &CD, &38, &CE, &CF, &FF
.dbiDesc23
  EQUB &D4, &09, &0C, &FE, &77, &78, &3D, &D5, &A4, &2C, &12, &FE
  EQUB &5B, &99, &3D, &08, &0B, &1A, &5D, &56, &D6, &FE, &D7, &29
  EQUB &00, &37, &DB, &4B, &54, &3D, &D8, &12, &56, &D9, &FF
.dbiDesc_end

ASSERT dbiDescLo - dbiStats == GEN_DBI_TYPES * GEN_DBI_STATS
ASSERT dbiDesc_end - dbiDesc == 471
ASSERT GEN_DBI_TYPES == DB_TYPES
ASSERT GEN_DBI_STATS == DB_STATS

