\ ============================================================
\ droidicon.asm - GENERATED by tools/export_droidicon.py
\ ============================================================
\ The console's first menu icon: the PLAYER'S OWN DROID, which the
\ C64 builds at run time into $53C0 and cannot be copied as artwork.
\ BuildDroidSprite ($3C77) writes the number, AnimateDroids ($3CFB)
\ the rotor; ConDroid composes the two the same way.
\
\ The port's own droid artwork is COMPILED - 6502 with the pixels
\ baked in as immediates - and lives in the sprite banks, which the
\ console in bank 6 cannot see. Hence this separate copy - in
\ MAIN RAM (RAM pass 3b), the ONE copy that both bank 6
\ (console.asm) and bank 7 (xfericon.asm) read.
\
\ ONE ROTOR PHASE, because the console is a still screen.

GEN_DRICON_W      = 3        \ C64 sprite bytes a row
GEN_DRICON_DIGITS = 10

\ Rows 0-4 then 15-19, three C64 sprite bytes each.
.conDrRotor
  EQUB &00, &00, &00                          \ row 0
  EQUB &00, &00, &00                          \ row 1
  EQUB &02, &7F, &80                          \ row 2
  EQUB &09, &FF, &E0                          \ row 3
  EQUB &23, &FF, &F8                          \ row 4
  EQUB &23, &FF, &F8                          \ row 15
  EQUB &09, &FF, &E0                          \ row 16
  EQUB &02, &7F, &80                          \ row 17
  EQUB &00, &38, &00                          \ row 18
  EQUB &00, &38, &00                          \ row 19

\ Digit 0-9, eight rows of ONE byte. BuildDroidSprite writes each
\ digit into a byte column of its own, so a glyph is eight bytes and
\ the three sit side by side without touching.
.conDrDigits
  EQUB &7C, &FE, &00, &C6, &C6, &C6, &FE, &7C  \ 0
  EQUB &3C, &7C, &1C, &1C, &1C, &1C, &1C, &1C  \ 1
  EQUB &FC, &FE, &0E, &7E, &FC, &00, &FE, &FE  \ 2
  EQUB &FE, &FC, &00, &3C, &7E, &0E, &FE, &FC  \ 3
  EQUB &1C, &38, &70, &FE, &FE, &00, &1C, &1C  \ 4
  EQUB &FE, &FE, &E0, &FC, &FE, &00, &FE, &FC  \ 5
  EQUB &38, &38, &70, &70, &CC, &CE, &FE, &7C  \ 6
  EQUB &FE, &FE, &00, &1C, &1C, &38, &38, &70  \ 7
  EQUB &7C, &FE, &C6, &38, &38, &C6, &FE, &7C  \ 8
  EQUB &7C, &FE, &E6, &66, &1C, &1C, &38, &38  \ 9

ASSERT conDrDigits - conDrRotor == 30
ASSERT GEN_DRICON_W == CON_DRICON_W

