\ ============================================================
\ droids.asm
\ GENERATED by tools/export_droids.py - do not edit by hand.
\ Source: paradroid_ce.lst (Paradroid, C64 - original/CE lineage)
\ 24 droid types, 8 rotor phases, waypoints for 16 decks
\ ============================================================
\ Shifts 2 and 3 px. The other two are in the other
\ sprite bank, at the same table addresses.

\ ==== fixed section: SAME SIZE AND ORDER IN BOTH BANKS ====
\ Everything the blitter reaches by name. Sizes here are
\ independent of which shifts the bank holds, so the
\ addresses match and one set of labels serves both.
\ The stored artwork is not among them: drSprData and
\ drOfs are in the DATA bank, read only by SprFetchRow.

\ p * 21, to index drOfs.
.xdrMulRows
  EQUB &00,&15,&2A,&3F,&54,&69,&7E,&93

\ Byte offset of each type's 8 digit rows into drSprData.
.xdrDigitLo
  EQUB &88,&C0,&F8,&30,&68,&A0,&D8,&10,&48,&80,&B8,&F0
  EQUB &28,&60,&98,&D0,&08,&40,&78,&B0,&E8,&20,&58,&90
.xdrDigitHi
  EQUB &01,&01,&01,&02,&02,&02,&02,&03,&03,&03,&03,&03
  EQUB &04,&04,&04,&04,&05,&05,&05,&05,&05,&06,&06,&06

\ Rotor dispatch, at index (shift AND 1)*80 + phase*10 + n,
\ where n counts the ten drawn rotor rows in drawing order.
\ This bank holds shifts 2 and 3 px; the other holds the
\ other two, at the same addresses with its own contents.
.xdrSeqLo
  EQUB LO(drD2_00),LO(drD2_02),LO(drD2_04),LO(drD2_05),LO(drD2_06),LO(drD2_06),LO(drD2_05),LO(drD2_04),LO(drD2_03),LO(drD2_01)
  EQUB LO(drD2_00),LO(drD2_02),LO(drD2_07),LO(drD2_08),LO(drD2_09),LO(drD2_09),LO(drD2_08),LO(drD2_07),LO(drD2_03),LO(drD2_01)
  EQUB LO(drD2_00),LO(drD2_02),LO(drD2_10),LO(drD2_11),LO(drD2_12),LO(drD2_12),LO(drD2_11),LO(drD2_10),LO(drD2_03),LO(drD2_01)
  EQUB LO(drD2_00),LO(drD2_02),LO(drD2_13),LO(drD2_14),LO(drD2_15),LO(drD2_15),LO(drD2_14),LO(drD2_13),LO(drD2_03),LO(drD2_01)
  EQUB LO(drD2_01),LO(drD2_03),LO(drD2_16),LO(drD2_17),LO(drD2_18),LO(drD2_18),LO(drD2_17),LO(drD2_16),LO(drD2_02),LO(drD2_00)
  EQUB LO(drD2_01),LO(drD2_03),LO(drD2_19),LO(drD2_20),LO(drD2_21),LO(drD2_21),LO(drD2_20),LO(drD2_19),LO(drD2_02),LO(drD2_00)
  EQUB LO(drD2_01),LO(drD2_03),LO(drD2_22),LO(drD2_23),LO(drD2_24),LO(drD2_24),LO(drD2_23),LO(drD2_22),LO(drD2_02),LO(drD2_00)
  EQUB LO(drD2_01),LO(drD2_03),LO(drD2_25),LO(drD2_26),LO(drD2_27),LO(drD2_27),LO(drD2_26),LO(drD2_25),LO(drD2_02),LO(drD2_00)
  EQUB LO(drD3_00),LO(drD3_02),LO(drD3_04),LO(drD3_05),LO(drD3_06),LO(drD3_06),LO(drD3_05),LO(drD3_04),LO(drD3_03),LO(drD3_01)
  EQUB LO(drD3_00),LO(drD3_02),LO(drD3_07),LO(drD3_08),LO(drD3_09),LO(drD3_09),LO(drD3_08),LO(drD3_07),LO(drD3_03),LO(drD3_01)
  EQUB LO(drD3_00),LO(drD3_02),LO(drD3_10),LO(drD3_11),LO(drD3_12),LO(drD3_12),LO(drD3_11),LO(drD3_10),LO(drD3_03),LO(drD3_01)
  EQUB LO(drD3_00),LO(drD3_02),LO(drD3_13),LO(drD3_14),LO(drD3_15),LO(drD3_15),LO(drD3_14),LO(drD3_13),LO(drD3_03),LO(drD3_01)
  EQUB LO(drD3_01),LO(drD3_03),LO(drD3_16),LO(drD3_17),LO(drD3_18),LO(drD3_18),LO(drD3_17),LO(drD3_16),LO(drD3_02),LO(drD3_00)
  EQUB LO(drD3_01),LO(drD3_03),LO(drD3_19),LO(drD3_20),LO(drD3_21),LO(drD3_21),LO(drD3_20),LO(drD3_19),LO(drD3_02),LO(drD3_00)
  EQUB LO(drD3_01),LO(drD3_03),LO(drD3_22),LO(drD3_23),LO(drD3_24),LO(drD3_24),LO(drD3_23),LO(drD3_22),LO(drD3_02),LO(drD3_00)
  EQUB LO(drD3_01),LO(drD3_03),LO(drD3_25),LO(drD3_26),LO(drD3_27),LO(drD3_27),LO(drD3_26),LO(drD3_25),LO(drD3_02),LO(drD3_00)
.xdrSeqHi
  EQUB HI(drD2_00),HI(drD2_02),HI(drD2_04),HI(drD2_05),HI(drD2_06),HI(drD2_06),HI(drD2_05),HI(drD2_04),HI(drD2_03),HI(drD2_01)
  EQUB HI(drD2_00),HI(drD2_02),HI(drD2_07),HI(drD2_08),HI(drD2_09),HI(drD2_09),HI(drD2_08),HI(drD2_07),HI(drD2_03),HI(drD2_01)
  EQUB HI(drD2_00),HI(drD2_02),HI(drD2_10),HI(drD2_11),HI(drD2_12),HI(drD2_12),HI(drD2_11),HI(drD2_10),HI(drD2_03),HI(drD2_01)
  EQUB HI(drD2_00),HI(drD2_02),HI(drD2_13),HI(drD2_14),HI(drD2_15),HI(drD2_15),HI(drD2_14),HI(drD2_13),HI(drD2_03),HI(drD2_01)
  EQUB HI(drD2_01),HI(drD2_03),HI(drD2_16),HI(drD2_17),HI(drD2_18),HI(drD2_18),HI(drD2_17),HI(drD2_16),HI(drD2_02),HI(drD2_00)
  EQUB HI(drD2_01),HI(drD2_03),HI(drD2_19),HI(drD2_20),HI(drD2_21),HI(drD2_21),HI(drD2_20),HI(drD2_19),HI(drD2_02),HI(drD2_00)
  EQUB HI(drD2_01),HI(drD2_03),HI(drD2_22),HI(drD2_23),HI(drD2_24),HI(drD2_24),HI(drD2_23),HI(drD2_22),HI(drD2_02),HI(drD2_00)
  EQUB HI(drD2_01),HI(drD2_03),HI(drD2_25),HI(drD2_26),HI(drD2_27),HI(drD2_27),HI(drD2_26),HI(drD2_25),HI(drD2_02),HI(drD2_00)
  EQUB HI(drD3_00),HI(drD3_02),HI(drD3_04),HI(drD3_05),HI(drD3_06),HI(drD3_06),HI(drD3_05),HI(drD3_04),HI(drD3_03),HI(drD3_01)
  EQUB HI(drD3_00),HI(drD3_02),HI(drD3_07),HI(drD3_08),HI(drD3_09),HI(drD3_09),HI(drD3_08),HI(drD3_07),HI(drD3_03),HI(drD3_01)
  EQUB HI(drD3_00),HI(drD3_02),HI(drD3_10),HI(drD3_11),HI(drD3_12),HI(drD3_12),HI(drD3_11),HI(drD3_10),HI(drD3_03),HI(drD3_01)
  EQUB HI(drD3_00),HI(drD3_02),HI(drD3_13),HI(drD3_14),HI(drD3_15),HI(drD3_15),HI(drD3_14),HI(drD3_13),HI(drD3_03),HI(drD3_01)
  EQUB HI(drD3_01),HI(drD3_03),HI(drD3_16),HI(drD3_17),HI(drD3_18),HI(drD3_18),HI(drD3_17),HI(drD3_16),HI(drD3_02),HI(drD3_00)
  EQUB HI(drD3_01),HI(drD3_03),HI(drD3_19),HI(drD3_20),HI(drD3_21),HI(drD3_21),HI(drD3_20),HI(drD3_19),HI(drD3_02),HI(drD3_00)
  EQUB HI(drD3_01),HI(drD3_03),HI(drD3_22),HI(drD3_23),HI(drD3_24),HI(drD3_24),HI(drD3_23),HI(drD3_22),HI(drD3_02),HI(drD3_00)
  EQUB HI(drD3_01),HI(drD3_03),HI(drD3_25),HI(drD3_26),HI(drD3_27),HI(drD3_27),HI(drD3_26),HI(drD3_25),HI(drD3_02),HI(drD3_00)
.xdrRSeqLo
  EQUB LO(drR2_00),LO(drR2_00),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_01),LO(drR2_01)
  EQUB LO(drR2_00),LO(drR2_00),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_01),LO(drR2_01)
  EQUB LO(drR2_00),LO(drR2_00),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_01),LO(drR2_01)
  EQUB LO(drR2_00),LO(drR2_00),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_01),LO(drR2_01)
  EQUB LO(drR2_01),LO(drR2_01),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_00),LO(drR2_00)
  EQUB LO(drR2_01),LO(drR2_01),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_00),LO(drR2_00)
  EQUB LO(drR2_01),LO(drR2_01),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_00),LO(drR2_00)
  EQUB LO(drR2_01),LO(drR2_01),LO(drR2_02),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_03),LO(drR2_02),LO(drR2_00),LO(drR2_00)
  EQUB LO(drR3_00),LO(drR3_00),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_01),LO(drR3_01)
  EQUB LO(drR3_00),LO(drR3_00),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_01),LO(drR3_01)
  EQUB LO(drR3_00),LO(drR3_00),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_01),LO(drR3_01)
  EQUB LO(drR3_00),LO(drR3_00),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_01),LO(drR3_01)
  EQUB LO(drR3_01),LO(drR3_01),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_00),LO(drR3_00)
  EQUB LO(drR3_01),LO(drR3_01),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_00),LO(drR3_00)
  EQUB LO(drR3_01),LO(drR3_01),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_00),LO(drR3_00)
  EQUB LO(drR3_01),LO(drR3_01),LO(drR3_02),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_03),LO(drR3_02),LO(drR3_00),LO(drR3_00)
.xdrRSeqHi
  EQUB HI(drR2_00),HI(drR2_00),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_01),HI(drR2_01)
  EQUB HI(drR2_00),HI(drR2_00),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_01),HI(drR2_01)
  EQUB HI(drR2_00),HI(drR2_00),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_01),HI(drR2_01)
  EQUB HI(drR2_00),HI(drR2_00),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_01),HI(drR2_01)
  EQUB HI(drR2_01),HI(drR2_01),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_00),HI(drR2_00)
  EQUB HI(drR2_01),HI(drR2_01),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_00),HI(drR2_00)
  EQUB HI(drR2_01),HI(drR2_01),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_00),HI(drR2_00)
  EQUB HI(drR2_01),HI(drR2_01),HI(drR2_02),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_03),HI(drR2_02),HI(drR2_00),HI(drR2_00)
  EQUB HI(drR3_00),HI(drR3_00),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_01),HI(drR3_01)
  EQUB HI(drR3_00),HI(drR3_00),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_01),HI(drR3_01)
  EQUB HI(drR3_00),HI(drR3_00),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_01),HI(drR3_01)
  EQUB HI(drR3_00),HI(drR3_00),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_01),HI(drR3_01)
  EQUB HI(drR3_01),HI(drR3_01),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_00),HI(drR3_00)
  EQUB HI(drR3_01),HI(drR3_01),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_00),HI(drR3_00)
  EQUB HI(drR3_01),HI(drR3_01),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_00),HI(drR3_00)
  EQUB HI(drR3_01),HI(drR3_01),HI(drR3_02),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_03),HI(drR3_02),HI(drR3_00),HI(drR3_00)

.xdrPrgLo
  EQUB LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0),LO(drPrg2_0)
  EQUB LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1),LO(drPrg2_1)
  EQUB LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2),LO(drPrg2_2)
  EQUB LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3),LO(drPrg2_3)
  EQUB LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4),LO(drPrg2_4)
  EQUB LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5),LO(drPrg2_5)
  EQUB LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6),LO(drPrg2_6)
  EQUB LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7),LO(drPrg2_7)
  EQUB LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0),LO(drPrg3_0)
  EQUB LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1),LO(drPrg3_1)
  EQUB LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2),LO(drPrg3_2)
  EQUB LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3),LO(drPrg3_3)
  EQUB LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4),LO(drPrg3_4)
  EQUB LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5),LO(drPrg3_5)
  EQUB LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6),LO(drPrg3_6)
  EQUB LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7),LO(drPrg3_7)
.xdrPrgHi
  EQUB HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0),HI(drPrg2_0)
  EQUB HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1),HI(drPrg2_1)
  EQUB HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2),HI(drPrg2_2)
  EQUB HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3),HI(drPrg2_3)
  EQUB HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4),HI(drPrg2_4)
  EQUB HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5),HI(drPrg2_5)
  EQUB HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6),HI(drPrg2_6)
  EQUB HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7),HI(drPrg2_7)
  EQUB HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0),HI(drPrg3_0)
  EQUB HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1),HI(drPrg3_1)
  EQUB HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2),HI(drPrg3_2)
  EQUB HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3),HI(drPrg3_3)
  EQUB HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4),HI(drPrg3_4)
  EQUB HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5),HI(drPrg3_5)
  EQUB HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6),HI(drPrg3_6)
  EQUB HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7),HI(drPrg3_7)
.xdrRPrgLo
  EQUB LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0),LO(drRPrg2_0)
  EQUB LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1),LO(drRPrg2_1)
  EQUB LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2),LO(drRPrg2_2)
  EQUB LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3),LO(drRPrg2_3)
  EQUB LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4),LO(drRPrg2_4)
  EQUB LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5),LO(drRPrg2_5)
  EQUB LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6),LO(drRPrg2_6)
  EQUB LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7),LO(drRPrg2_7)
  EQUB LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0),LO(drRPrg3_0)
  EQUB LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1),LO(drRPrg3_1)
  EQUB LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2),LO(drRPrg3_2)
  EQUB LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3),LO(drRPrg3_3)
  EQUB LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4),LO(drRPrg3_4)
  EQUB LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5),LO(drRPrg3_5)
  EQUB LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6),LO(drRPrg3_6)
  EQUB LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7),LO(drRPrg3_7)
.xdrRPrgHi
  EQUB HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0),HI(drRPrg2_0)
  EQUB HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1),HI(drRPrg2_1)
  EQUB HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2),HI(drRPrg2_2)
  EQUB HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3),HI(drRPrg2_3)
  EQUB HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4),HI(drRPrg2_4)
  EQUB HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5),HI(drRPrg2_5)
  EQUB HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6),HI(drRPrg2_6)
  EQUB HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7),HI(drRPrg2_7)
  EQUB HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0),HI(drRPrg3_0)
  EQUB HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1),HI(drRPrg3_1)
  EQUB HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2),HI(drRPrg3_2)
  EQUB HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3),HI(drRPrg3_3)
  EQUB HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4),HI(drRPrg3_4)
  EQUB HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5),HI(drRPrg3_5)
  EQUB HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6),HI(drRPrg3_6)
  EQUB HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7),HI(drRPrg3_7)

\ Sprite row -> position in that sequence; &FF means the row is
\ not the rotor's (a digit row, or one of the three blank ones).
\ Only the wrap fallback needs it - the fast path knows the
\ shape and walks the list straight through.
.xdrSeqIdx
  EQUB &00,&01,&02,&03,&04,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&FF,&05,&06,&07,&08,&09,&FF
.xdrMul10                     \ phase * 10
  EQUB &00,&0A,&14,&1E,&28,&32,&3C,&46


\ drBlkSave6 - the digit block's column 6, all eight rows.
\ Nothing owns it: it is only ever written by the last
\ position's spill under a shift. See SprDigitBlock.
.xdrBlkSave6
  LDY #6*UNIT_BYTES
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA (rowp+14),Y : STA (rowq+14),Y
  RTS

\ The three digit positions, as column offsets. The glyphs
\ below index these with the position in X.
.xdrYcol0 EQUB 0, 16, 32
.xdrYcol1 EQUB 8, 24, 40
.xdrYcol2 EQUB 16, 32, 48

\ Glyph dispatch, at index (shift AND 1)*10 + digit.
.xdrGlyphLo
  EQUB LO(drGlyph2_0),LO(drGlyph2_1),LO(drGlyph2_2),LO(drGlyph2_3),LO(drGlyph2_4),LO(drGlyph2_5),LO(drGlyph2_6),LO(drGlyph2_7),LO(drGlyph2_8),LO(drGlyph2_9)
  EQUB LO(drGlyph3_0),LO(drGlyph3_1),LO(drGlyph3_2),LO(drGlyph3_3),LO(drGlyph3_4),LO(drGlyph3_5),LO(drGlyph3_6),LO(drGlyph3_7),LO(drGlyph3_8),LO(drGlyph3_9)
.xdrGlyphHi
  EQUB HI(drGlyph2_0),HI(drGlyph2_1),HI(drGlyph2_2),HI(drGlyph2_3),HI(drGlyph2_4),HI(drGlyph2_5),HI(drGlyph2_6),HI(drGlyph2_7),HI(drGlyph2_8),HI(drGlyph2_9)
  EQUB HI(drGlyph3_0),HI(drGlyph3_1),HI(drGlyph3_2),HI(drGlyph3_3),HI(drGlyph3_4),HI(drGlyph3_5),HI(drGlyph3_6),HI(drGlyph3_7),HI(drGlyph3_8),HI(drGlyph3_9)

\ The three digits of each droid type, as glyph numbers.
.xdrDigit0
  EQUB &00,&01,&01,&02,&02,&02,&03,&03,&04,&04,&04,&05
  EQUB &05,&05,&06,&06,&06,&07,&07,&07,&08,&08,&08,&09
.xdrDigit1
  EQUB &00,&02,&03,&04,&04,&09,&00,&02,&02,&07,&09,&01
  EQUB &07,&09,&01,&01,&02,&01,&04,&05,&02,&03,&08,&09
.xdrDigit2
  EQUB &01,&03,&09,&07,&09,&06,&02,&09,&00,&06,&03,&06
  EQUB &01,&08,&04,&05,&09,&01,&02,&01,&01,&04,&03,&09

\ ==== code: sizes differ between the banks ================
\ ---- shift 2 px -------------------------------------
.drD2_00
  SCANSTEP
  RTS
.drD2_01
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_02
  SCANSTEP
  RTS
.drD2_03
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_04
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_05
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_06
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_07
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_08
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_09
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_10
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_11
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_12
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_13
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_14
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_15
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_16
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_17
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_18
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_19
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_20
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_21
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_22
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&99 : ORA colPix+4 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_23
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_24
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_25
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_26
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&77 : ORA colPix+6 : STA (bufp),Y
  SCANSTEP
  RTS
.drD2_27
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&DD : ORA colPix+1 : STA (bufp),Y
  SCANSTEP
  RTS
.drR2_00
  SCANSTEP
  RTS
.drR2_01
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR2_02
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR2_03
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
\ ---- shift 3 px -------------------------------------
.drD3_00
  SCANSTEP
  RTS
.drD3_01
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_02
  SCANSTEP
  RTS
.drD3_03
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_04
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_05
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_06
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_07
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&99 : ORA colPix+4 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_08
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_09
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_10
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_11
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_12
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_13
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_14
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_15
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_16
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_17
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_18
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_19
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_20
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_21
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_22
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&CC : ORA colPix+2 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_23
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_24
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&33 : ORA colPix+8 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_25
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&66 : ORA colPix+7 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_26
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&11 : ORA colPix+9 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&BB : ORA colPix+3 : STA (bufp),Y
  SCANSTEP
  RTS
.drD3_27
  LDY #1*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&88 : ORA colPix+5 : STA (bufp),Y
  LDY #2*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #3*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #4*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  LDA colPix+10 : STA (bufp),Y
  LDY #5*UNIT_BYTES
  LDA (bufp),Y : STA (svp),Y
  AND #&EE : ORA colPix+0 : STA (bufp),Y
  SCANSTEP
  RTS
.drR3_00
  SCANSTEP
  RTS
.drR3_01
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR3_02
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drR3_03
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS

\ Five rows of restore inlined. Only the column set matters, and
\ that depends on shift and phase>>2 alone - so eight of these
\ cover all sixteen sequences. The last row of the bottom half
\ does not walk: nothing reads the pointers after it.
.drRHalf2_0_0
  SCANSTEP
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf2_0_1
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  RTS
.drRHalf2_1_0
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf2_1_1
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  SCANSTEP
  RTS
.drRHalf3_0_0
  SCANSTEP
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf3_0_1
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  RTS
.drRHalf3_1_0
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  RTS
.drRHalf3_1_1
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #1*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #5*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  LDY #2*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #3*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  LDY #4*UNIT_BYTES : LDA (svp),Y : STA (bufp),Y
  SCANSTEP
  SCANSTEP
  RTS

.drPrg2_0
  JSR drD2_00
  JSR drD2_02
  JSR drD2_04
  JSR drD2_05
  JSR drD2_06
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_06
  JSR drD2_05
  JSR drD2_04
  JSR drD2_03
  JMP drD2_01
.drPrg2_1
  JSR drD2_00
  JSR drD2_02
  JSR drD2_07
  JSR drD2_08
  JSR drD2_09
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_09
  JSR drD2_08
  JSR drD2_07
  JSR drD2_03
  JMP drD2_01
.drPrg2_2
  JSR drD2_00
  JSR drD2_02
  JSR drD2_10
  JSR drD2_11
  JSR drD2_12
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_12
  JSR drD2_11
  JSR drD2_10
  JSR drD2_03
  JMP drD2_01
.drPrg2_3
  JSR drD2_00
  JSR drD2_02
  JSR drD2_13
  JSR drD2_14
  JSR drD2_15
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_15
  JSR drD2_14
  JSR drD2_13
  JSR drD2_03
  JMP drD2_01
.drPrg2_4
  JSR drD2_01
  JSR drD2_03
  JSR drD2_16
  JSR drD2_17
  JSR drD2_18
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_18
  JSR drD2_17
  JSR drD2_16
  JSR drD2_02
  JMP drD2_00
.drPrg2_5
  JSR drD2_01
  JSR drD2_03
  JSR drD2_19
  JSR drD2_20
  JSR drD2_21
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_21
  JSR drD2_20
  JSR drD2_19
  JSR drD2_02
  JMP drD2_00
.drPrg2_6
  JSR drD2_01
  JSR drD2_03
  JSR drD2_22
  JSR drD2_23
  JSR drD2_24
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_24
  JSR drD2_23
  JSR drD2_22
  JSR drD2_02
  JMP drD2_00
.drPrg2_7
  JSR drD2_01
  JSR drD2_03
  JSR drD2_25
  JSR drD2_26
  JSR drD2_27
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD2_27
  JSR drD2_26
  JSR drD2_25
  JSR drD2_02
  JMP drD2_00
.drPrg3_0
  JSR drD3_00
  JSR drD3_02
  JSR drD3_04
  JSR drD3_05
  JSR drD3_06
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_06
  JSR drD3_05
  JSR drD3_04
  JSR drD3_03
  JMP drD3_01
.drPrg3_1
  JSR drD3_00
  JSR drD3_02
  JSR drD3_07
  JSR drD3_08
  JSR drD3_09
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_09
  JSR drD3_08
  JSR drD3_07
  JSR drD3_03
  JMP drD3_01
.drPrg3_2
  JSR drD3_00
  JSR drD3_02
  JSR drD3_10
  JSR drD3_11
  JSR drD3_12
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_12
  JSR drD3_11
  JSR drD3_10
  JSR drD3_03
  JMP drD3_01
.drPrg3_3
  JSR drD3_00
  JSR drD3_02
  JSR drD3_13
  JSR drD3_14
  JSR drD3_15
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_15
  JSR drD3_14
  JSR drD3_13
  JSR drD3_03
  JMP drD3_01
.drPrg3_4
  JSR drD3_01
  JSR drD3_03
  JSR drD3_16
  JSR drD3_17
  JSR drD3_18
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_18
  JSR drD3_17
  JSR drD3_16
  JSR drD3_02
  JMP drD3_00
.drPrg3_5
  JSR drD3_01
  JSR drD3_03
  JSR drD3_19
  JSR drD3_20
  JSR drD3_21
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_21
  JSR drD3_20
  JSR drD3_19
  JSR drD3_02
  JMP drD3_00
.drPrg3_6
  JSR drD3_01
  JSR drD3_03
  JSR drD3_22
  JSR drD3_23
  JSR drD3_24
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_24
  JSR drD3_23
  JSR drD3_22
  JSR drD3_02
  JMP drD3_00
.drPrg3_7
  JSR drD3_01
  JSR drD3_03
  JSR drD3_25
  JSR drD3_26
  JSR drD3_27
  SCANSTEP
  JSR SprDigitBlock
  SCANSTEP
  JSR drD3_27
  JSR drD3_26
  JSR drD3_25
  JSR drD3_02
  JMP drD3_00

.drRPrg2_0
  JSR drRHalf2_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_0_1
.drRPrg2_1
  JSR drRHalf2_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_0_1
.drRPrg2_2
  JSR drRHalf2_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_0_1
.drRPrg2_3
  JSR drRHalf2_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_0_1
.drRPrg2_4
  JSR drRHalf2_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_1_1
.drRPrg2_5
  JSR drRHalf2_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_1_1
.drRPrg2_6
  JSR drRHalf2_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_1_1
.drRPrg2_7
  JSR drRHalf2_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf2_1_1
.drRPrg3_0
  JSR drRHalf3_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_0_1
.drRPrg3_1
  JSR drRHalf3_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_0_1
.drRPrg3_2
  JSR drRHalf3_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_0_1
.drRPrg3_3
  JSR drRHalf3_0_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_0_1
.drRPrg3_4
  JSR drRHalf3_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_1_1
.drRPrg3_5
  JSR drRHalf3_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_1_1
.drRPrg3_6
  JSR drRHalf3_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_1_1
.drRPrg3_7
  JSR drRHalf3_1_0
  SCANSTEP
  JSR SprBlkRest
  SCANSTEP
  JMP drRHalf3_1_1
.drGlyph2_0
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph2_1
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&88 : ORA colPix+5 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&88 : ORA colPix+5 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  RTS
.drGlyph2_2
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph2_3
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph2_4
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  RTS
.drGlyph2_5
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph2_6
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&11 : ORA colPix+9 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&11 : ORA colPix+9 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph2_7
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&11 : ORA colPix+9 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph2_8
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&11 : ORA colPix+9 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  RTS
.drGlyph2_9
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&CC : ORA colPix+2 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&66 : ORA colPix+7 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&66 : ORA colPix+7 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&88 : ORA colPix+5 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&11 : ORA colPix+9 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph3_0
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_1
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&CC : ORA colPix+2 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_2
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&33 : ORA colPix+8 : STA (rowp+14),Y
  RTS
.drGlyph3_3
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&77 : ORA colPix+6 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_4
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&CC : ORA colPix+2 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&CC : ORA colPix+2 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&77 : ORA colPix+6 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&CC : ORA colPix+2 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_5
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&EE : ORA colPix+0 : STA (rowp+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDA colPix+10 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDA colPix+10 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&33 : ORA colPix+8 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&EE : ORA colPix+0 : STA (rowp+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_6
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&88 : ORA colPix+5 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&88 : ORA colPix+5 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&11 : ORA colPix+9 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&11 : ORA colPix+9 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&EE : ORA colPix+0 : STA (rowp+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&66 : ORA colPix+7 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&66 : ORA colPix+7 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_7
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  AND #&EE : ORA colPix+0 : STA (rowp+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&33 : ORA colPix+8 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&CC : ORA colPix+2 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&77 : ORA colPix+6 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&88 : ORA colPix+5 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&11 : ORA colPix+9 : STA (rowp+14),Y
  RTS
.drGlyph3_8
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&77 : ORA colPix+6 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&88 : ORA colPix+5 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&88 : ORA colPix+5 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&EE : ORA colPix+0 : STA (rowp+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&33 : ORA colPix+8 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&EE : ORA colPix+0 : STA (rowp+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDA colPix+10 : STA (rowp+12),Y
  LDY drYcol2,X
  LDA (rowp+12),Y : AND #&33 : ORA colPix+8 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDA colPix+10 : STA (rowp+14),Y
  LDY drYcol2,X
  LDA (rowp+14),Y : AND #&77 : ORA colPix+6 : STA (rowp+14),Y
  RTS
.drGlyph3_9
  LDY drYcol0,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDY drYcol1,X
  LDA (rowp+0),Y : STA (rowq+0),Y
  LDA colPix+10 : STA (rowp+0),Y
  LDY drYcol2,X
  LDA (rowp+0),Y : AND #&77 : ORA colPix+6 : STA (rowp+0),Y
  LDY drYcol0,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  AND #&EE : ORA colPix+0 : STA (rowp+2),Y
  LDY drYcol1,X
  LDA (rowp+2),Y : STA (rowq+2),Y
  LDA colPix+10 : STA (rowp+2),Y
  LDY drYcol2,X
  LDA (rowp+2),Y : AND #&33 : ORA colPix+8 : STA (rowp+2),Y
  LDY drYcol0,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&EE : ORA colPix+0 : STA (rowp+4),Y
  LDY drYcol1,X
  LDA (rowp+4),Y : STA (rowq+4),Y
  AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol2,X
  LDA (rowp+4),Y : AND #&33 : ORA colPix+8 : STA (rowp+4),Y
  LDY drYcol0,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  LDY drYcol1,X
  LDA (rowp+6),Y : STA (rowq+6),Y
  AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol2,X
  LDA (rowp+6),Y : AND #&33 : ORA colPix+8 : STA (rowp+6),Y
  LDY drYcol0,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  LDY drYcol1,X
  LDA (rowp+8),Y : STA (rowq+8),Y
  AND #&CC : ORA colPix+2 : STA (rowp+8),Y
  LDY drYcol2,X
  LDA (rowp+8),Y : AND #&77 : ORA colPix+6 : STA (rowp+8),Y
  LDY drYcol0,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  LDY drYcol1,X
  LDA (rowp+10),Y : STA (rowq+10),Y
  AND #&CC : ORA colPix+2 : STA (rowp+10),Y
  LDY drYcol2,X
  LDA (rowp+10),Y : AND #&77 : ORA colPix+6 : STA (rowp+10),Y
  LDY drYcol0,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  LDY drYcol1,X
  LDA (rowp+12),Y : STA (rowq+12),Y
  AND #&88 : ORA colPix+5 : STA (rowp+12),Y
  LDY drYcol0,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  LDY drYcol1,X
  LDA (rowp+14),Y : STA (rowq+14),Y
  AND #&88 : ORA colPix+5 : STA (rowp+14),Y
  RTS
