\ ============================================================
\ hsremap.asm - GENERATED by tools/export_hsremap.py, do not edit
\ ============================================================
\ DoHighScore's alphabet, as INDICES INTO textfont. It used to
\ be 1,152 bytes of its own glyphs, because PARTITL was
\ assembled over the text font; no-load step 3 moved PARTITL
\ off &3000, so the font survives the title and all 72 were
\ duplicates. The exporter re-derives both and compares every
\ byte on every run. See its header, and HsGlyph.

HS_GLYPHS   = 72
HS_UPPER    = 0
HS_UPPER_R  = 26
HS_SPACE    = 52
HS_DOT      = 53
HS_UPPER_I  = HS_UPPER + 8      \ narrow, a bare stem
\ 255 where a wide lowercase is used by no string, so the
\ plotter's test for it can never match.
HS_LOWER_M  = 255
HS_M_RIGHT  = 255
HS_LOWER_W  = 61
HS_W_RIGHT  = 62

\ ---- screen glyph -> textfont glyph ------------------------
\ 0-51 are uniformly index + 11, because textfont puts its own
\ capitals at 11 and 37 and this screen puts them at 0 and 26.
\ The table is emitted whole anyway: it costs 52 bytes of a
\ bank that has room, and it means HsGlyph has ONE path.
.hsRemap
  EQUB  11,  12,  13,  14,  15,  16,  17,  18   \  0  A B C D E F G H
  EQUB  19,  20,  21,  22,  23,  24,  25,  26   \  8  I J K L M N O P
  EQUB  27,  28,  29,  30,  31,  32,  33,  34   \ 16  Q R S T U V W X
  EQUB  35,  36,  37,  38,  39,  40,  41,  42   \ 24  Y Z > > > > > >
  EQUB  43,  44,   0,  46,  47,  48,  49,  50   \ 32  > >   > > > > >
  EQUB  51,  52,  53,  54,  55,  56,  57,  58   \ 40  > > > > > > > >
  EQUB  59,  60,  61,  62,   0,  89,  80,  67   \ 48  > > > >   . r e
  EQUB  63,  82,  65,  77, 102,  85, 101,  81   \ 56  a t c o ! w > s
  EQUB  68,  70,  87,  74,  76,  83,  71,  98   \ 64  f h y l n u i -
.hsRemap_end
ASSERT hsRemap_end - hsRemap == HS_GLYPHS

\ ---- the three strings, $E733 / $E742 / $E714 -------------
\ In THIS file's indices. A capital is ONE index and the
\ plotter draws its right half; so are lowercase m and w.

\ row 10 col 13  "Great Score!"
.hsTxtGreat
  EQUB 6, 54, 55, 56, 57, 52, 18, 58
  EQUB 59, 54, 55, 60, &FF

\ row 10 col 5  "Lowest Score of the Day!"
.hsTxtLowest
  EQUB 11, 59, 61, 55, 63, 57, 52, 18
  EQUB 58, 59, 54, 55, 52, 59, 64, 52
  EQUB 57, 65, 55, 52, 3, 56, 66, 60
  EQUB &FF

\ row 22 col 1  "Please enter your initials -"
.hsTxtEnter
  EQUB 15, 67, 55, 56, 63, 55, 52, 55
  EQUB 68, 57, 55, 54, 52, 66, 59, 69
  EQUB 54, 52, 70, 68, 70, 57, 70, 56
  EQUB 67, 63, 52, 71, &FF

