\ Generated by tools/export_intro.py - DO NOT EDIT.
\ Palettes and flash tables for PINTRO (docs/intro.md).
\ All values are ULA register form: (entry<<4) OR (phys EOR 7).

.palPicRest \ picture region, rest: L0-2 black, L3 sky
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&87,&97,&C7,&D7,&A3,&B3,&E3,&F3

.palCred \ credits region, constant
  EQUB &07,&17,&47,&57,&22,&32,&62,&72,&81,&91,&C1,&D1,&A5,&B5,&E5,&F5

\ Four colourways x four envelope steps x 12 bytes: the
\ palette entries for logicals 0,1,2 (D021,D022,D023 ramps,
\ pre-mapped to BBC physicals). Step 0 = rest, 3 = peak.
.cwSteps
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&87,&97,&C7,&D7 \ cw1 step 0
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&83,&93,&C3,&D3 \ cw1 step 1
  EQUB &07,&17,&47,&57,&23,&33,&63,&73,&81,&91,&C1,&D1 \ cw1 step 2
  EQUB &03,&13,&43,&53,&21,&31,&61,&71,&80,&90,&C0,&D0 \ cw1 step 3
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&87,&97,&C7,&D7 \ cw2 step 0
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&86,&96,&C6,&D6 \ cw2 step 1
  EQUB &07,&17,&47,&57,&26,&36,&66,&76,&86,&96,&C6,&D6 \ cw2 step 2
  EQUB &06,&16,&46,&56,&26,&36,&66,&76,&84,&94,&C4,&D4 \ cw2 step 3
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&87,&97,&C7,&D7 \ cw3 step 0
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&86,&96,&C6,&D6 \ cw3 step 1
  EQUB &07,&17,&47,&57,&26,&36,&66,&76,&82,&92,&C2,&D2 \ cw3 step 2
  EQUB &06,&16,&46,&56,&22,&32,&62,&72,&84,&94,&C4,&D4 \ cw3 step 3
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&87,&97,&C7,&D7 \ cw4 step 0
  EQUB &07,&17,&47,&57,&27,&37,&67,&77,&85,&95,&C5,&D5 \ cw4 step 1
  EQUB &07,&17,&47,&57,&25,&35,&65,&75,&81,&91,&C1,&D1 \ cw4 step 2
  EQUB &05,&15,&45,&55,&21,&31,&61,&71,&85,&95,&C5,&D5 \ cw4 step 3
