\ ============================================================
\ portraits.asm - GENERATED by tools/export_portraits.py, do not edit
\ ============================================================
\ The droid portrait pool: 63 unique C64 sprite images, verbatim,
\ and the per-type composition index. Read the tool header.

PO_IMAGES = 63
PO_MIRROR = &FF

\ 24 types x 8: even bytes the left image slot, odd bytes the right
\ (PO_MIRROR = mirror the left, the C64's record byte 0).
.poIdx
  EQUB &14, &FF, &15, &FF, &16, &FF, &17, &FF   \ type 0
  EQUB &0C, &FF, &0D, &FF, &0E, &FF, &00, &00   \ type 1
  EQUB &1C, &FF, &1B, &FF, &00, &00, &00, &00   \ type 2
  EQUB &04, &FF, &05, &FF, &06, &FF, &00, &00   \ type 3
  EQUB &04, &FF, &05, &FF, &18, &FF, &00, &00   \ type 4
  EQUB &22, &FF, &03, &FF, &00, &00, &00, &00   \ type 5
  EQUB &23, &FF, &28, &FF, &00, &00, &00, &00   \ type 6
  EQUB &2A, &FF, &29, &FF, &00, &00, &00, &00   \ type 7
  EQUB &04, &FF, &24, &FF, &03, &FF, &00, &00   \ type 8
  EQUB &23, &FF, &24, &FF, &06, &FF, &00, &00   \ type 9
  EQUB &23, &FF, &34, &FF, &33, &FF, &00, &00   \ type 10
  EQUB &1C, &FF, &01, &FF, &02, &FF, &00, &00   \ type 11
  EQUB &0F, &FF, &25, &FF, &26, &FF, &27, &FF   \ type 12
  EQUB &37, &FF, &38, &FF, &39, &FF, &3A, &FF   \ type 13
  EQUB &0F, &FF, &10, &11, &12, &FF, &13, &FF   \ type 14
  EQUB &2E, &FF, &2F, &FF, &00, &00, &00, &00   \ type 15
  EQUB &14, &FF, &30, &FF, &00, &00, &00, &00   \ type 16
  EQUB &07, &FF, &08, &0B, &09, &FF, &0A, &FF   \ type 17
  EQUB &35, &FF, &36, &FF, &12, &FF, &13, &FF   \ type 18
  EQUB &3B, &FF, &3C, &FF, &3D, &FF, &3E, &FF   \ type 19
  EQUB &19, &1A, &00, &00, &00, &00, &00, &00   \ type 20
  EQUB &31, &FF, &32, &FF, &00, &00, &00, &00   \ type 21
  EQUB &1D, &FF, &1E, &1F, &20, &FF, &21, &FF   \ type 22
  EQUB &2B, &FF, &2C, &FF, &2D, &FF, &19, &1A   \ type 23

\ The images, 64 bytes each: 21 rows x 3 bytes, then byte 63 =
\ MC flag (bit 7) OR rptLen (bits 0-4). ZX0, 8 chunks of 8;
\ PoImgPtr depacks the one it needs to PO_BASE. NOTHING may
\ index these bytes: there is no .poPool any more.
PO_CHUNK   = 8
PO_CHUNK_N = 8
PO_CHUNK_SZ = 512
.poPackLo
  EQUB LO(0), LO(256), LO(597), LO(891), LO(1200), LO(1468), LO(1784), LO(2137)
.poPackHi
  EQUB HI(0), HI(256), HI(597), HI(891), HI(1200), HI(1468), HI(1784), HI(2137)
.poPack
\ slots 0-7: 256 bytes packed from 512
  EQUB &80, &00, &02, &3B, &2B, &0F, &FB, &05, &CA, &F4, &04, &2B, &0B, &A2, &FB, &0A
  EQUB &8A, &2A, &8A, &28, &9A, &A2, &AA, &8A, &FF, &AC, &5A, &04, &2E, &3F, &E9, &86
  EQUB &CE, &8A, &0F, &0C, &BB, &95, &7F, &AC, &A2, &FB, &BC, &8A, &FC, &10, &28, &2C
  EQUB &A4, &AC, &5F, &A6, &1E, &81, &26, &02, &BC, &BF, &EA, &59, &F4, &1B, &AA, &E2
  EQUB &CF, &FB, &0A, &BF, &8A, &2A, &EA, &4A, &AB, &AA, &02, &AE, &A2, &0A, &A5, &A6
  EQUB &A0, &AB, &AA, &29, &5A, &EA, &2B, &FA, &A6, &29, &5A, &FF, &39, &AA, &03, &F2
  EQUB &9A, &01, &53, &FF, &38, &50, &00, &81, &8B, &03, &F0, &80, &EE, &FA, &02, &92
  EQUB &6E, &95, &FB, &A8, &BA, &25, &A2, &2F, &8B, &AF, &A0, &AE, &D1, &AA, &59, &A3
  EQUB &FF, &0F, &FF, &68, &05, &55, &A5, &15, &6F, &90, &A5, &A2, &25, &2A, &42, &AF
  EQUB &FA, &02, &AE, &BA, &02, &AC, &3A, &03, &AD, &7A, &0B, &A8, &BA, &69, &EF, &FA
  EQUB &2A, &FA, &AB, &EA, &0E, &AE, &9C, &D5, &90, &28, &BA, &A0, &1E, &BA, &E8, &00
  EQUB &FF, &3A, &08, &15, &0E, &AA, &23, &E8, &9A, &81, &DA, &A5, &2A, &BA, &8F, &FB
  EQUB &BA, &0A, &02, &1E, &0D, &DB, &82, &93, &8B, &96, &63, &9C, &3E, &AA, &98, &2B
  EQUB &AA, &3A, &97, &FF, &0D, &B0, &55, &01, &C0, &15, &29, &05, &05, &02, &DD, &8D
  EQUB &92, &EB, &FA, &55, &3B, &24, &1B, &B2, &41, &2B, &13, &BE, &1B, &3C, &ED, &1A
  EQUB &F4, &A1, &5D, &1A, &B6, &0E, &6F, &B6, &03, &7B, &95, &FF, &B5, &91, &55, &58
\ slots 8-15: 341 bytes packed from 512
  EQUB &AE, &00, &05, &FB, &F8, &3F, &F4, &A2, &02, &AA, &2B, &FF, &AF, &2E, &FA, &BA
  EQUB &AB, &E9, &BA, &2A, &AE, &39, &02, &AF, &FB, &3A, &B0, &FF, &0A, &C0, &05, &2B
  EQUB &B9, &14, &2E, &16, &F5, &28, &0E, &80, &E9, &03, &A3, &97, &EC, &AA, &C0, &0F
  EQUB &BF, &91, &F1, &AB, &EE, &FA, &FF, &7B, &82, &15, &E8, &0A, &E3, &2A, &A2, &FF
  EQUB &E2, &EA, &E9, &E9, &56, &8A, &EB, &AE, &2A, &78, &02, &9E, &22, &A7, &95, &8F
  EQUB &A9, &40, &51, &BA, &99, &8B, &FB, &9B, &22, &AF, &00, &48, &25, &95, &00, &AC
  EQUB &00, &A0, &50, &E1, &E2, &A2, &8C, &9E, &9C, &DC, &47, &EA, &AC, &EC, &3E, &03
  EQUB &BB, &81, &EE, &BF, &FC, &E2, &68, &F9, &A0, &BB, &E8, &F5, &B8, &8E, &FA, &EF
  EQUB &22, &FF, &AC, &28, &BA, &80, &A1, &EA, &A8, &E8, &3E, &A5, &50, &03, &E5, &B9
  EQUB &3B, &BA, &0B, &F5, &0B, &7A, &7F, &0B, &28, &F4, &A2, &3C, &DD, &F0, &81, &DB
  EQUB &A3, &98, &D8, &A9, &31, &A1, &A8, &2A, &EA, &A0, &0A, &2A, &AE, &BA, &FA, &EA
  EQUB &20, &ED, &FA, &A9, &6A, &7E, &D7, &1F, &B6, &75, &07, &69, &68, &01, &7F, &FF
  EQUB &DA, &15, &55, &17, &EA, &7C, &F4, &3A, &E1, &94, &28, &2A, &AA, &BF, &02, &EA
  EQUB &FB, &E0, &22, &0B, &AF, &AB, &9F, &0E, &2A, &7B, &95, &8A, &2B, &6A, &8A, &02
  EQUB &6A, &E2, &0A, &F5, &3A, &6B, &83, &3E, &6E, &95, &2E, &A9, &D7, &A8, &D9, &A5
  EQUB &F0, &0A, &DB, &E8, &02, &BF, &2C, &81, &3A, &A7, &0B, &A2, &54, &0E, &80, &8A
  EQUB &02, &D0, &28, &03, &54, &A3, &01, &50, &01, &40, &DC, &F5, &E7, &8E, &6E, &57
  EQUB &8B, &2A, &AB, &62, &D1, &AE, &A2, &80, &28, &AE, &A6, &0A, &AB, &AA, &29, &5A
  EQUB &EA, &2B, &FA, &EA, &29, &5A, &FF, &39, &5A, &A2, &03, &F2, &01, &53, &37, &67
  EQUB &B6, &31, &40, &81, &8A, &10, &06, &CC, &06, &8A, &08, &A2, &2A, &19, &A6, &0E
  EQUB &2E, &0F, &FB, &F7, &03, &81, &85, &FD, &C5, &FB, &57, &62, &32, &B8, &0F, &FE
  EQUB &0B, &8F, &55, &55, &80
\ slots 16-23: 294 bytes packed from 512
  EQUB &AE, &00, &0F, &FB, &A2, &AA, &0A, &BF, &8A, &AA, &EA, &62, &AB, &AA, &01, &00
  EQUB &A1, &09, &EB, &AF, &0A, &7A, &FA, &2A, &CE, &AA, &2B, &03, &A2, &AC, &00, &A6
  EQUB &D0, &68, &AA, &68, &04, &FF, &1A, &1F, &00, &06, &97, &FF, &01, &28, &77, &00
  EQUB &DF, &FF, &28, &FC, &00, &03, &F0, &82, &0F, &C0, &FE, &8D, &EF, &C1, &FB, &2F
  EQUB &FE, &A0, &8F, &F9, &7C, &FB, &A1, &40, &FA, &EB, &A2, &AF, &AD, &A0, &AA, &B3
  EQUB &8A, &C3, &8A, &9A, &03, &A2, &AA, &80, &FF, &3E, &9D, &F5, &18, &FD, &70, &77
  EQUB &75, &7F, &96, &50, &03, &C1, &50, &01, &40, &60, &88, &C0, &A0, &FE, &81, &82
  EQUB &E8, &02, &FB, &0A, &68, &06, &8A, &05, &6A, &28, &09, &5F, &A2, &0A, &A0, &08
  EQUB &20, &88, &0A, &E0, &13, &A7, &C5, &60, &FE, &FA, &EF, &FA, &B8, &95, &AA, &43
  EQUB &F8, &2F, &F4, &AD, &0E, &B0, &2B, &8A, &8B, &2A, &BC, &23, &3A, &BC, &6F, &90
  EQUB &FC, &AF, &93, &DF, &A2, &01, &8A, &E8, &DE, &CF, &DE, &A2, &9A, &A2, &EA, &03
  EQUB &FF, &2E, &3F, &FB, &B8, &05, &FE, &12, &EA, &89, &80, &80, &8A, &A2, &80, &29
  EQUB &A6, &80, &4E, &FF, &C0, &9B, &D5, &C2, &8F, &55, &CA, &9D, &55, &CE, &8D, &55
  EQUB &FE, &F4, &B8, &AD, &EE, &6A, &4E, &28, &50, &0E, &B6, &40, &07, &EB, &E8, &F4
  EQUB &81, &50, &4B, &90, &FE, &2A, &11, &FA, &18, &8B, &03, &FA, &AA, &A1, &E3, &EA
  EQUB &BA, &0E, &21, &03, &16, &8A, &0F, &33, &2E, &F7, &D9, &E8, &3C, &FB, &4D, &B8
  EQUB &D3, &81, &86, &37, &8D, &FB, &C0, &B2, &06, &8A, &FA, &0C, &06, &8A, &78, &CC
  EQUB &1A, &79, &3A, &C3, &0C, &FD, &C5, &F5, &7B, &F5, &CF, &CF, &A2, &09, &C7, &8A
  EQUB &40, &60, &6D, &15, &55, &56
\ slots 24-31: 309 bytes packed from 512
  EQUB &AE, &00, &0A, &FB, &8A, &2A, &AA, &A1, &02, &8A, &03, &FF, &28, &01, &51, &8A
  EQUB &02, &B3, &B1, &28, &B2, &0A, &F2, &28, &C2, &BA, &C3, &B9, &C1, &28, &C5, &A2
  EQUB &F5, &A3, &50, &06, &54, &AE, &FA, &95, &8D, &FF, &10, &FA, &7B, &A7, &75, &0F
  EQUB &B8, &F1, &8A, &71, &BE, &9A, &0A, &EF, &DA, &85, &38, &2B, &FF, &2A, &2F, &FF
  EQUB &A2, &2C, &FB, &66, &3D, &F7, &2A, &3F, &FF, &05, &55, &55, &05, &7F, &FF, &01
  EQUB &55, &3F, &FA, &15, &55, &C7, &FA, &89, &05, &A9, &00, &94, &04, &00, &A2, &A8
  EQUB &8A, &F0, &BF, &22, &A3, &FC, &82, &A7, &FF, &C0, &AB, &F9, &E5, &E9, &0A, &FF
  EQUB &FE, &54, &FF, &F6, &54, &EF, &B6, &66, &DF, &56, &55, &B8, &56, &83, &EA, &50
  EQUB &FD, &FB, &F5, &7E, &40, &55, &54, &84, &9E, &50, &13, &A8, &8D, &2B, &8A, &2B
  EQUB &05, &28, &AB, &AA, &A7, &BF, &FF, &C0, &0F, &2B, &A8, &55, &AC, &E1, &0F, &B0
  EQUB &3D, &E2, &B0, &D5, &FF, &B3, &D7, &FA, &AA, &DF, &B7, &AA, &AA, &DE, &26, &F7
  EQUB &FA, &66, &95, &03, &EA, &AE, &AA, &C0, &42, &D9, &EF, &B6, &C3, &0C, &95, &23
  EQUB &8C, &00, &DA, &F4, &A2, &2A, &A6, &8F, &03, &BB, &A2, &D1, &FA, &86, &05, &8B
  EQUB &28, &A3, &A2, &BB, &A7, &8B, &A9, &AA, &7B, &86, &3F, &AE, &1B, &2F, &0E, &7B
  EQUB &81, &3C, &62, &0D, &3E, &A9, &88, &3A, &A4, &E2, &FA, &22, &AA, &A9, &96, &AA
  EQUB &24, &19, &65, &F1, &E8, &38, &81, &AE, &2E, &EE, &AE, &FA, &22, &AD, &6E, &86
  EQUB &A5, &5F, &02, &E5, &DF, &A6, &E7, &5A, &1F, &00, &FD, &7F, &02, &AF, &FF, &8E
  EQUB &AB, &69, &9E, &02, &FE, &52, &1B, &8D, &EE, &EC, &00, &EE, &8A, &FA, &2E, &8A
  EQUB &FF, &3E, &27, &FC, &4E, &BA, &EE, &FB, &3C, &28, &FA, &B7, &EA, &EA, &39, &FE
  EQUB &5B, &8E, &55, &55, &80
\ slots 32-39: 268 bytes packed from 512
  EQUB &29, &00, &AA, &3B, &00, &23, &8E, &03, &EF, &BE, &FA, &BD, &E8, &E2, &28, &02
  EQUB &A2, &02, &8A, &0E, &0E, &28, &02, &42, &0E, &95, &05, &55, &55, &FA, &09, &90
  EQUB &00, &00, &00, &0A, &84, &8A, &28, &00, &AA, &A5, &02, &0A, &40, &03, &A9, &55
  EQUB &8B, &AA, &EA, &68, &FB, &FE, &8F, &3F, &FF, &DB, &A2, &F5, &0A, &36, &2A, &EA
  EQUB &F5, &8B, &E2, &E6, &8A, &CB, &EA, &01, &69, &FF, &02, &7E, &07, &0A, &C3, &AA
  EQUB &2B, &00, &EA, &AC, &01, &15, &5A, &A9, &40, &3F, &FD, &40, &93, &00, &10, &2A
  EQUB &00, &04, &A9, &00, &01, &A4, &FF, &9F, &FB, &79, &67, &FA, &9F, &85, &F5, &05
  EQUB &28, &2A, &4F, &FE, &06, &38, &8C, &10, &BD, &1A, &06, &A9, &AF, &07, &F6, &BA
  EQUB &10, &0A, &EA, &3A, &0E, &BF, &7B, &AA, &1B, &15, &E8, &07, &01, &2B, &BA, &3A
  EQUB &D7, &2E, &2A, &AB, &1A, &02, &BC, &FF, &0A, &C0, &E8, &2B, &7B, &14, &A9, &3A
  EQUB &88, &50, &0F, &A1, &A6, &F9, &50, &0D, &50, &8F, &36, &B0, &AB, &0A, &28, &B2
  EQUB &F5, &EA, &E1, &A1, &FA, &6D, &0E, &FF, &AA, &0B, &BF, &FF, &3A, &C5, &FF, &2E
  EQUB &00, &91, &B1, &BB, &2A, &3A, &02, &8A, &2F, &0E, &AA, &2A, &0F, &EA, &3F, &01
  EQUB &7F, &57, &2F, &AA, &DC, &00, &DA, &2B, &31, &2D, &25, &87, &35, &40, &7F, &05
  EQUB &50, &15, &95, &B6, &FB, &3A, &13, &20, &3E, &AF, &8D, &07, &F5, &A2, &69, &50
  EQUB &F1, &B0, &FA, &63, &03, &F0, &A4, &F5, &A0, &FE, &81, &E1, &A4, &01, &8F, &00
  EQUB &40, &56, &FA, &FB, &45, &74, &F1, &FE, &B5, &90, &55, &58
\ slots 40-47: 316 bytes packed from 512
  EQUB &AE, &00, &2A, &FB, &E4, &05, &F4, &A8, &AA, &EA, &02, &80, &FB, &95, &28, &03
  EQUB &AA, &8A, &00, &EA, &3F, &28, &01, &68, &09, &A2, &05, &8A, &04, &08, &28, &00
  EQUB &18, &0A, &92, &01, &42, &AA, &04, &52, &0A, &05, &8A, &AA, &5A, &2A, &A8, &22
  EQUB &5E, &A9, &A2, &AA, &53, &FF, &88, &50, &55, &A6, &00, &2F, &01, &40, &FE, &12
  EQUB &F2, &8C, &68, &1B, &50, &40, &01, &04, &10, &A2, &F9, &03, &7A, &0E, &C0, &41
  EQUB &FA, &2E, &03, &00, &CF, &8B, &4A, &A2, &68, &E9, &A6, &22, &03, &FA, &28, &FF
  EQUB &AF, &0F, &E1, &DF, &FA, &FE, &B6, &93, &99, &86, &11, &DB, &09, &D1, &24, &A8
  EQUB &FB, &A4, &A2, &2A, &A9, &EA, &80, &8A, &7A, &15, &2A, &3A, &51, &FE, &22, &7F
  EQUB &55, &A2, &3F, &9B, &0F, &45, &A2, &7B, &05, &9D, &0D, &A1, &81, &0F, &36, &18
  EQUB &3B, &62, &8A, &3D, &07, &66, &9F, &03, &FF, &FB, &31, &E2, &0A, &A2, &F5, &2B
  EQUB &03, &AE, &AA, &02, &BA, &FA, &06, &EA, &EE, &92, &FB, &EB, &26, &BA, &EA, &27
  EQUB &AE, &92, &29, &EB, &E5, &2B, &3A, &AE, &A6, &0E, &88, &A0, &EF, &AA, &95, &F8
  EQUB &FA, &88, &03, &AF, &A0, &AE, &A4, &00, &8A, &AF, &05, &68, &AA, &0E, &80, &A6
  EQUB &03, &A0, &00, &E8, &9A, &8A, &3A, &6A, &2A, &0E, &56, &0B, &FB, &EF, &E9, &3F
  EQUB &68, &69, &1F, &AC, &07, &A6, &CF, &7F, &BE, &90, &2F, &FB, &8A, &22, &82, &2A
  EQUB &89, &2A, &02, &A4, &13, &FA, &C9, &F4, &F7, &E9, &E3, &1E, &C8, &00, &A7, &0F
  EQUB &A0, &F5, &06, &6E, &0A, &9B, &28, &20, &80, &A0, &8A, &20, &E5, &AA, &AF, &8A
  EQUB &95, &3F, &38, &AA, &A5, &BA, &EA, &EA, &BF, &FA, &FA, &F0, &FF, &3F, &C0, &3F
  EQUB &0F, &A4, &0F, &3E, &8A, &10, &28, &3D, &04, &A9, &EB, &6A, &5C, &88, &2F, &D9
  EQUB &EF, &8A, &4B, &04, &FC, &26, &10, &3D, &D5, &95, &55, &60
\ slots 48-55: 353 bytes packed from 512
  EQUB &A7, &00, &AA, &00, &02, &8A, &FB, &0F, &FF, &62, &AA, &AA, &0A, &A3, &20, &FA
  EQUB &82, &9A, &F1, &8A, &2A, &0A, &5A, &6A, &FA, &EF, &FE, &AA, &F5, &57, &78, &F7
  EQUB &77, &EA, &F5, &0A, &FF, &37, &74, &FF, &05, &54, &00, &07, &6E, &00, &04, &44
  EQUB &FE, &5B, &91, &A1, &FB, &03, &68, &0F, &5A, &0A, &2A, &AA, &8A, &0A, &20, &22
  EQUB &82, &BE, &86, &8A, &EE, &02, &0B, &AE, &A1, &2E, &AA, &BA, &0A, &63, &BF, &FE
  EQUB &A6, &20, &95, &0A, &28, &9E, &1A, &69, &96, &EC, &FF, &E0, &D5, &EA, &C9, &FB
  EQUB &AE, &9A, &03, &AB, &9A, &00, &EA, &EE, &ED, &FA, &8D, &3E, &AE, &C4, &EA, &47
  EQUB &EE, &FF, &63, &3F, &FB, &86, &01, &E9, &04, &01, &10, &2F, &93, &B7, &68, &87
  EQUB &3F, &8F, &02, &C0, &FA, &08, &68, &01, &40, &02, &AA, &AA, &A2, &FD, &7F, &C1
  EQUB &40, &38, &D8, &AE, &C4, &38, &83, &0B, &FF, &FF, &0B, &F3, &F5, &FA, &FE, &E9
  EQUB &00, &7B, &E9, &0E, &FB, &3A, &A8, &40, &69, &AA, &44, &02, &22, &50, &0A, &66
  EQUB &60, &0B, &AA, &68, &2B, &EA, &3A, &AC, &3A, &0D, &B0, &72, &01, &C0, &3F, &BE
  EQUB &2A, &DF, &E8, &0B, &FB, &2F, &AA, &BF, &02, &3A, &92, &E8, &0E, &7B, &03, &A3
  EQUB &00, &F8, &81, &51, &BC, &E3, &F5, &08, &2A, &A8, &FB, &AA, &A2, &2A, &A0, &28
  EQUB &85, &8A, &29, &91, &88, &38, &A2, &3D, &95, &3F, &D5, &AE, &3C, &EF, &EA, &D4
  EQUB &F5, &C5, &36, &0D, &05, &86, &2E, &3E, &A7, &EA, &AF, &97, &AB, &DA, &2B, &51
  EQUB &AE, &E2, &BD, &BA, &BA, &8A, &AE, &EB, &3E, &EB, &AE, &EE, &28, &BE, &EA, &E8
  EQUB &B2, &BA, &FB, &AE, &A2, &2B, &8D, &6A, &A2, &4B, &B3, &2B, &B0, &55, &30, &6F
  EQUB &03, &70, &FA, &22, &00, &C0, &E5, &FE, &BE, &8C, &1F, &73, &0B, &A8, &0A, &02
  EQUB &AB, &A7, &FA, &03, &A9, &5A, &3B, &E2, &3A, &63, &FB, &0E, &AE, &AF, &A9, &A5
  EQUB &E7, &96, &B9, &3A, &02, &20, &0F, &02, &60, &01, &AE, &40, &FB, &33, &01, &02
  EQUB &32, &8E, &FF, &2A, &B9, &7C, &3A, &BA, &AA, &BB, &B7, &FB, &AB, &01, &55, &55
  EQUB &80
\ slots 56-62: 218 bytes packed from 448
  EQUB &29, &0B, &EA, &0E, &0B, &3A, &BF, &0B, &0E, &AA, &0B, &03, &FF, &0B, &00, &05
  EQUB &FB, &E5, &2A, &F4, &28, &00, &F8, &F3, &FB, &A2, &0A, &85, &0E, &94, &99, &03
  EQUB &D5, &40, &A8, &00, &7A, &00, &8D, &00, &02, &AA, &D9, &FF, &B8, &2B, &F5, &EE
  EQUB &3A, &EA, &CD, &BA, &B5, &FF, &AF, &E3, &EF, &DD, &A0, &FB, &C0, &42, &FF, &95
  EQUB &F2, &53, &E1, &93, &FA, &5F, &A6, &2E, &2B, &81, &88, &2B, &B8, &11, &40, &00
  EQUB &EA, &FA, &0A, &8A, &0E, &8A, &22, &0F, &AA, &8A, &EA, &FF, &28, &D5, &A8, &55
  EQUB &A2, &0D, &57, &05, &5E, &8A, &01, &7A, &9A, &00, &3A, &59, &86, &AA, &BA, &02
  EQUB &AA, &03, &AE, &02, &EA, &AB, &95, &03, &FA, &AA, &01, &7E, &98, &0E, &9F, &FF
  EQUB &A2, &33, &8A, &77, &FF, &2A, &3F, &22, &BF, &7F, &8A, &FF, &55, &A2, &BD, &28
  EQUB &B5, &57, &8A, &95, &5F, &7E, &08, &84, &80, &3A, &8A, &8A, &BA, &4E, &A2, &AE
  EQUB &95, &0E, &B6, &2B, &81, &E8, &62, &9F, &A6, &5A, &F5, &8A, &97, &FD, &3A, &83
  EQUB &FC, &FB, &BC, &28, &AC, &02, &A9, &43, &0D, &A8, &53, &A2, &01, &55, &00, &15
  EQUB &82, &95, &00, &03, &AC, &08, &A2, &00, &50, &03, &A0, &05, &72, &27, &8A, &B8
  EQUB &EC, &8A, &3E, &BC, &75, &05, &50, &95, &55, &58
.poPack_end

\ Multicolour nibble -> the MODE 1 byte for its two pixels.
\ ONE 16-BYTE TABLE, NOT TWO OF 256. pack() below reads the
\ top two 2-bit pixels for the left byte and the bottom two
\ for the right, so each half depends on ONE NIBBLE of the
\ source and both halves take the same sixteen values:
\   left  = poLut[b >> 4]      right = poLut[b AND 15]
\ The two 256-byte tables this replaces were that identity
\ written out longhand, 512 bytes of bank 7 for 16 bytes of
\ information. portrait.asm extracts the nibble; a portrait
\ is drawn once per screen, so the shifts cost nothing.
.poLut
  EQUB &00, &03, &30, &33, &0C, &0F, &3C, &3F, &C0, &C3, &F0, &F3, &CC, &CF, &FC, &FF

