\ ============================================================
\ sndchat.asm - the briefing chatter's three blips
\ GENERATED by tools/export_sound.py - do not edit by hand.
\ ============================================================
\ Effects 29-31, in sndFxTab's record format but assembled into
\ PARMAN - bank 5, beside the briefing text - rather than bank 4,
\ which had 15 bytes free. BmChatter copies the blip it picks
\ into brChRec and BrChatter lands it in the sndFxChat scratch
\ slot, then posts effect 29. Every instrument named here is
\ already in sndInstTab.
\
\ ONLY THE FIRST 5 BYTES OF A RECORD ARE HERE - instrument,
\ initial frequency and slide. The three blips share every byte
\ from the segment timer on (7D 00 01 00 00 00), the exporter
\ asserts they do, and sndFxChat ships holding them.
\ ============================================================

BR_CHAT_PRE = 5

.brChatTab
  EQUB &0E,&00,&20,&00,&E8  \ 29: briefing chatter blip A (triangle)
     \ F 0..63488, 12 wraps, sub-floor 6%
  EQUB &0E,&00,&10,&00,&C7  \ 30: briefing chatter blip B (sawtooth)
     \ F 768..62208, 28 wraps, sub-floor 4%
  EQUB &0E,&00,&0C,&00,&CD  \ 31: briefing chatter blip C (pulse)
     \ F 3328..61696, 25 wraps, sub-floor 0%
