\ ============================================================
\ svdecks6.asm - the deck rectangles, BANK 6 COPY
\ GENERATED by tools/export_sideview.py - do not edit by hand.
\ ============================================================
\ Byte-for-byte svDeckY/X/H/W from src/data/sideview.asm, which is
\ bank 7. LvClearedMark walks these from bank 6 and only one bank
\ is visible at a time, so the geometry has to exist in both. Both
\ copies come from the same C64 listing in the same exporter run,
\ so they cannot drift; regenerate, never hand-edit.

.lvcDeckY
  EQUB 0, 1, 1, 2, 2, 3, 4, 5, 6, 7, 3, 6, 9, 9, 8, 9
.lvcDeckX
  EQUB 5, 15, 5, 3, 16, 18, 20, 22, 22, 22, 9, 9, 9, 18, 0, 0
.lvcDeckH
  EQUB 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 2, 1, 1
.lvcDeckW
  EQUB 17, 15, 8, 13, 18, 18, 18, 14, 12, 8, 13, 13, 13, 4, 26, 24

