\ ============================================================
\ textfont.asm - GENERATED by tools/export_font.py, do not edit
\ ============================================================
\ The C64 text font at $7000, VERBATIM - 1 bit per pixel.
\
\ NOT converted to MODE 1. It used to be, at 32 bytes a glyph, and
\ half of every one of those bytes was redundant: the artwork is two
\ colour, logical 0 and logical 3, so each MODE 1 byte came out as
\ n<<4 | n and carried four pixels in eight bits. Pairing a cell's
\ byte i with its byte i+8 - the same scanline's left and right
\ halves - gives back (left<<4) | right, which IS the C64 byte. So
\ the packed form is not an encoding this port invented; it is the
\ original data, and FontCell in main RAM expands it as it draws.
\ export_font.py asserts the round-trip for every cell it emits.
\
\ IT IS 8 x 16, NOT 8 x 8: the glyph top half is at C64 code c and
\ its bottom half at c + $80. A cell is 8 x 8, which is 8 PACKED
\ bytes, so a glyph is TWO STACKED CELLS, 16 bytes - top then bottom.
\ That is why the four-row panel holds ONE line of text with a border
\ row above it and another below.
\
\ CAPITALS ARE 16 PX WIDE, right half at C64 code + $20, which is
\ DrawChar's own arrangement at $0C82 — "see if it was wide". Each is
\ exported as two glyphs and PnStr draws the second when the first
\ falls in the capital range. Lowercase and digits are 8 px, one cell.
\
\ Glyph index, contiguous so PnAscii can map ASCII with four compares:
\   0 space, 1-10 digits, 11-36 capitals LEFT, 37-62 capitals RIGHT,
\   63-88 lowercase, 89 full stop, 90-96 the LOGO, 97 the box bar.
\ NOTHING IS SYNTHESISED: every byte below is the C64's own artwork.

\ Declared here and checked against main.asm's FONT_GLYPHS and
\ FONT_BYTES, which have to come first: beebasm resolves constants in
\ file order and droid.asm asserts on the font size before this file.
GEN_FONT_GLYPHS = 104
GEN_FONT_BYTES  = 1664
GEN_FRAME_CELLS = 12
GEN_FRAME_BYTES = 96

.textfont
  \  0  space
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  \  1  '0'
  EQUB &00, &00, &00, &00, &38, &7C, &EE, &C6
  EQUB &C6, &EE, &7C, &38, &00, &00, &00, &00
  \  2  '1'
  EQUB &00, &00, &00, &00, &3C, &3C, &0C, &0C
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \  3  '2'
  EQUB &00, &00, &00, &00, &F8, &FC, &0E, &06
  EQUB &0E, &1C, &38, &70, &FE, &FE, &00, &00
  \  4  '3'
  EQUB &00, &00, &F8, &FC, &0E, &06, &0E, &FC
  EQUB &FC, &0E, &06, &0E, &FC, &F8, &00, &00
  \  5  '4'
  EQUB &00, &00, &00, &00, &06, &0E, &1C, &38
  EQUB &70, &E0, &FE, &FE, &06, &06, &00, &00
  \  6  '5'
  EQUB &00, &00, &00, &00, &FE, &FE, &C0, &F8
  EQUB &FC, &0E, &06, &0E, &FC, &F8, &00, &00
  \  7  '6'
  EQUB &00, &00, &0E, &1C, &38, &7C, &EE, &C6
  EQUB &C6, &EE, &7C, &38, &00, &00, &00, &00
  \  8  '7'
  EQUB &00, &00, &00, &00, &FE, &FE, &1C, &1C
  EQUB &38, &38, &70, &70, &E0, &E0, &00, &00
  \  9  '8'
  EQUB &00, &00, &38, &7C, &EE, &C6, &EE, &7C
  EQUB &7C, &EE, &C6, &EE, &7C, &38, &00, &00
  \ 10  '9'
  EQUB &00, &00, &00, &00, &38, &7C, &EE, &C6
  EQUB &C6, &EE, &7C, &38, &70, &E0, &00, &00
  \ 11  'A' left
  EQUB &00, &00, &03, &07, &0E, &0C, &0C, &0C
  EQUB &0F, &0F, &00, &00, &00, &00, &00, &00
  \ 12  'B' left
  EQUB &00, &00, &0F, &0F, &0C, &0C, &0D, &0D
  EQUB &0C, &0C, &0C, &0C, &03, &03, &00, &00
  \ 13  'C' left
  EQUB &00, &00, &01, &03, &07, &0E, &0C, &0C
  EQUB &0E, &07, &03, &01, &00, &00, &00, &00
  \ 14  'D' left
  EQUB &00, &00, &0F, &0F, &0C, &0C, &0C, &0C
  EQUB &0C, &0C, &0D, &0D, &00, &00, &00, &00
  \ 15  'E' left
  EQUB &00, &00, &03, &07, &0E, &0E, &07, &07
  EQUB &0E, &0C, &0C, &0E, &07, &03, &00, &00
  \ 16  'F' left
  EQUB &00, &00, &01, &03, &07, &0E, &0C, &0F
  EQUB &0F, &0C, &0C, &0C, &0C, &0C, &00, &00
  \ 17  'G' left
  EQUB &00, &00, &01, &03, &07, &0E, &0C, &0C
  EQUB &0E, &07, &03, &01, &00, &00, &00, &00
  \ 18  'H' left
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0D, &0D
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \ 19  'I' left
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0C, &0C
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \ 20  'J' left
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &01, &01, &00, &00, &00, &00
  \ 21  'K' left
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0F, &0F
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \ 22  'L' left
  EQUB &00, &00, &01, &01, &01, &01, &01, &01
  EQUB &01, &01, &01, &01, &00, &00, &00, &00
  \ 23  'M' left
  EQUB &00, &00, &3E, &3F, &33, &31, &31, &31
  EQUB &31, &31, &31, &31, &00, &00, &00, &00
  \ 24  'N' left
  EQUB &00, &00, &0F, &0F, &0C, &0C, &0C, &0C
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \ 25  'O' left
  EQUB &00, &00, &01, &03, &07, &0E, &0C, &0C
  EQUB &0E, &07, &03, &01, &00, &00, &00, &00
  \ 26  'P' left
  EQUB &00, &00, &0F, &0F, &0C, &0C, &0C, &0C
  EQUB &0C, &0C, &0D, &0D, &0C, &0C, &00, &00
  \ 27  'Q' left
  EQUB &00, &00, &01, &03, &07, &0E, &0C, &0C
  EQUB &0E, &07, &03, &01, &00, &00, &00, &00
  \ 28  'R' left
  EQUB &00, &00, &0F, &0F, &0C, &0C, &0C, &0C
  EQUB &0D, &0D, &0C, &0C, &00, &00, &00, &00
  \ 29  'S' left
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &01, &01, &00, &00, &00, &00
  \ 30  'T' left
  EQUB &00, &00, &0F, &0F, &00, &00, &00, &00
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  \ 31  'U' left
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0C, &0C
  EQUB &0C, &0E, &07, &03, &00, &00, &00, &00
  \ 32  'V' left
  EQUB &00, &00, &0C, &0C, &0E, &06, &07, &03
  EQUB &03, &01, &01, &00, &00, &00, &00, &00
  \ 33  'W' left
  EQUB &00, &00, &1D, &3D, &71, &61, &61, &61
  EQUB &61, &73, &7F, &1E, &00, &00, &00, &00
  \ 34  'X' left
  EQUB &00, &00, &0E, &0F, &03, &01, &00, &00
  EQUB &01, &03, &0F, &0E, &00, &00, &00, &00
  \ 35  'Y' left
  EQUB &00, &00, &0C, &0C, &0E, &06, &07, &03
  EQUB &03, &01, &01, &00, &00, &00, &00, &00
  \ 36  'Z' left
  EQUB &00, &00, &0F, &0F, &00, &00, &00, &01
  EQUB &03, &07, &0F, &0F, &00, &00, &00, &00
  \ 37  'A' right
  EQUB &00, &00, &F0, &F8, &1C, &0C, &0C, &0C
  EQUB &EC, &EC, &0C, &0C, &0C, &0C, &00, &00
  \ 38  'B' right
  EQUB &00, &00, &F0, &F8, &1C, &1C, &F8, &F8
  EQUB &1C, &0C, &0C, &1C, &F8, &F0, &00, &00
  \ 39  'C' right
  EQUB &00, &00, &FC, &FC, &00, &00, &00, &00
  EQUB &00, &00, &FC, &FC, &00, &00, &00, &00
  \ 40  'D' right
  EQUB &00, &00, &E0, &F0, &38, &1C, &0C, &0C
  EQUB &1C, &38, &F0, &E0, &00, &00, &00, &00
  \ 41  'E' right
  EQUB &00, &00, &FC, &FC, &00, &00, &FC, &FC
  EQUB &00, &00, &00, &00, &FC, &FC, &00, &00
  \ 42  'F' right
  EQUB &00, &00, &FC, &FC, &00, &00, &00, &FC
  EQUB &FC, &00, &00, &00, &00, &00, &00, &00
  \ 43  'G' right
  EQUB &00, &00, &FC, &FC, &00, &0C, &0C, &0C
  EQUB &0C, &0C, &FC, &FC, &00, &00, &00, &00
  \ 44  'H' right
  EQUB &00, &00, &0C, &0C, &0C, &0C, &FC, &FC
  EQUB &0C, &0C, &0C, &0C, &0C, &0C, &00, &00
  \ 45  'I' right
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  \ 46  'J' right
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0C, &0C
  EQUB &0C, &1C, &F8, &F0, &00, &00, &00, &00
  \ 47  'K' right
  EQUB &00, &00, &0C, &0C, &1C, &38, &F0, &F0
  EQUB &38, &1C, &0C, &0C, &0C, &0C, &00, &00
  \ 48  'L' right
  EQUB &00, &00, &80, &80, &80, &80, &80, &80
  EQUB &80, &80, &FC, &FC, &00, &00, &00, &00
  \ 49  'M' right
  EQUB &00, &00, &70, &78, &9C, &8C, &8C, &8C
  EQUB &8C, &8C, &8C, &8C, &00, &00, &00, &00
  \ 50  'N' right
  EQUB &00, &00, &F0, &F8, &1C, &0C, &0C, &0C
  EQUB &0C, &0C, &0C, &0C, &00, &00, &00, &00
  \ 51  'O' right
  EQUB &00, &00, &E0, &F0, &38, &1C, &0C, &0C
  EQUB &1C, &38, &F0, &E0, &00, &00, &00, &00
  \ 52  'P' right
  EQUB &00, &00, &E0, &F0, &38, &1C, &0C, &0C
  EQUB &1C, &38, &F0, &E0, &00, &00, &00, &00
  \ 53  'Q' right
  EQUB &00, &00, &E0, &F0, &38, &1C, &0C, &0C
  EQUB &1C, &38, &F0, &F0, &18, &00, &00, &00
  \ 54  'R' right
  EQUB &00, &00, &F0, &F8, &1C, &0C, &0C, &1C
  EQUB &F8, &F8, &1C, &0C, &0C, &0C, &00, &00
  \ 55  'S' right
  EQUB &00, &00, &C0, &C0, &E0, &70, &38, &1C
  EQUB &0C, &1C, &F8, &F0, &00, &00, &00, &00
  \ 56  'T' right
  EQUB &00, &00, &FC, &FC, &C0, &C0, &C0, &C0
  EQUB &C0, &C0, &C0, &C0, &00, &00, &00, &00
  \ 57  'U' right
  EQUB &00, &00, &0C, &0C, &0C, &0C, &0C, &0C
  EQUB &0C, &0C, &FC, &FC, &00, &00, &00, &00
  \ 58  'V' right
  EQUB &00, &00, &F0, &F8, &1C, &0C, &1C, &18
  EQUB &B8, &B0, &F0, &E0, &00, &00, &00, &00
  \ 59  'W' right
  EQUB &00, &00, &B8, &BC, &8E, &86, &86, &86
  EQUB &86, &CE, &FC, &78, &00, &00, &00, &00
  \ 60  'X' right
  EQUB &00, &00, &1C, &3C, &F0, &E0, &C0, &C0
  EQUB &E0, &F0, &3C, &1C, &00, &00, &00, &00
  \ 61  'Y' right
  EQUB &00, &00, &F0, &F8, &1C, &0C, &1C, &18
  EQUB &B8, &B0, &F0, &E0, &60, &C0, &00, &00
  \ 62  'Z' right
  EQUB &00, &00, &FC, &FC, &38, &70, &E0, &C0
  EQUB &80, &00, &FC, &FC, &00, &00, &00, &00
  \ 63  'a'
  EQUB &00, &00, &00, &00, &3E, &7E, &E6, &C6
  EQUB &C6, &E6, &76, &36, &00, &00, &00, &00
  \ 64  'b'
  EQUB &00, &00, &C0, &C0, &D8, &DC, &CE, &C6
  EQUB &C6, &CE, &FC, &F8, &00, &00, &00, &00
  \ 65  'c'
  EQUB &00, &00, &00, &00, &3E, &7E, &E0, &C0
  EQUB &C0, &E0, &7E, &3E, &00, &00, &00, &00
  \ 66  'd'
  EQUB &00, &00, &06, &06, &36, &76, &E6, &C6
  EQUB &C6, &E6, &7E, &3E, &00, &00, &00, &00
  \ 67  'e'
  EQUB &00, &00, &00, &00, &3E, &7E, &E6, &CC
  EQUB &D8, &E0, &7E, &3E, &00, &00, &00, &00
  \ 68  'f'
  EQUB &00, &00, &1E, &3E, &70, &60, &60, &7E
  EQUB &7E, &60, &60, &60, &00, &00, &00, &00
  \ 69  'g'
  EQUB &00, &00, &00, &00, &3E, &7E, &E6, &C6
  EQUB &E6, &76, &36, &06, &3E, &3C, &00, &00
  \ 70  'h'
  EQUB &00, &00, &C0, &C0, &F8, &FC, &CE, &C6
  EQUB &C6, &C6, &C6, &C6, &00, &00, &00, &00
  \ 71  'i'
  EQUB &00, &00, &18, &18, &00, &18, &18, &18
  EQUB &18, &18, &18, &18, &00, &00, &00, &00
  \ 72  'j'
  EQUB &00, &00, &06, &06, &00, &06, &06, &06
  EQUB &06, &06, &06, &0E, &7C, &78, &00, &00
  \ 73  'k'
  EQUB &00, &00, &C0, &C0, &C6, &CE, &FC, &F8
  EQUB &DC, &CE, &C6, &C6, &00, &00, &00, &00
  \ 74  'l'
  EQUB &00, &00, &18, &18, &18, &18, &18, &18
  EQUB &18, &18, &18, &18, &00, &00, &00, &00
  \ 75  'm'
  EQUB &00, &00, &00, &00, &3E, &3F, &33, &31
  EQUB &31, &31, &31, &31, &00, &00, &00, &00
  \ 76  'n'
  EQUB &00, &00, &00, &00, &F8, &FC, &CE, &C6
  EQUB &C6, &C6, &C6, &C6, &00, &00, &00, &00
  \ 77  'o'
  EQUB &00, &00, &00, &00, &38, &7C, &EE, &C6
  EQUB &C6, &EE, &7C, &38, &00, &00, &00, &00
  \ 78  'p'
  EQUB &00, &00, &00, &00, &F8, &FC, &CE, &C6
  EQUB &C6, &CE, &DC, &D8, &C0, &C0, &00, &00
  \ 79  'q'
  EQUB &00, &00, &00, &00, &3E, &7E, &E6, &C6
  EQUB &C6, &E6, &76, &36, &06, &06, &00, &00
  \ 80  'r'
  EQUB &00, &00, &00, &00, &1E, &3E, &70, &60
  EQUB &60, &60, &60, &60, &00, &00, &00, &00
  \ 81  's'
  EQUB &00, &00, &00, &00, &60, &60, &70, &38
  EQUB &1C, &0E, &06, &0E, &7C, &78, &00, &00
  \ 82  't'
  EQUB &00, &00, &60, &60, &7E, &7E, &60, &60
  EQUB &60, &70, &3E, &1E, &00, &00, &00, &00
  \ 83  'u'
  EQUB &00, &00, &00, &00, &C6, &C6, &C6, &C6
  EQUB &C6, &E6, &7E, &3E, &00, &00, &00, &00
  \ 84  'v'
  EQUB &00, &00, &00, &00, &D8, &DC, &CE, &66
  EQUB &66, &6E, &3C, &38, &00, &00, &00, &00
  \ 85  'w'
  EQUB &00, &00, &00, &00, &1D, &3D, &71, &61
  EQUB &61, &73, &3F, &1E, &00, &00, &00, &00
  \ 86  'x'
  EQUB &00, &00, &00, &00, &C7, &EF, &3C, &18
  EQUB &18, &3C, &EF, &C7, &00, &00, &00, &00
  \ 87  'y'
  EQUB &00, &00, &00, &00, &D8, &DC, &CE, &66
  EQUB &66, &6E, &3C, &38, &70, &E0, &00, &00
  \ 88  'z'
  EQUB &00, &00, &00, &00, &FE, &FE, &0E, &38
  EQUB &38, &E0, &FE, &FE, &00, &00, &00, &00
  \ 89  '.'
  EQUB &00, &00, &00, &00, &00, &00, &00, &00
  EQUB &00, &00, &70, &70, &00, &00, &00, &00
  \ 90  logo cell 0
  EQUB &7F, &78, &78, &78, &78, &78, &7F, &78
  EQUB &78, &78, &78, &7C, &7C, &7C, &7C, &00
  \ 91  logo cell 1
  EQUB &FF, &00, &00, &00, &00, &00, &FF, &00
  EQUB &FC, &CC, &0C, &FE, &CE, &CE, &FE, &00
  \ 92  logo cell 2
  EQUB &FF, &00, &00, &00, &00, &00, &FF, &00
  EQUB &DE, &F6, &60, &70, &70, &70, &70, &00
  \ 93  logo cell 3
  EQUB &FF, &00, &00, &00, &06, &06, &FF, &06
  EQUB &FE, &C6, &C6, &E7, &E7, &E7, &FF, &00
  \ 94  logo cell 4
  EQUB &FF, &00, &00, &00, &00, &00, &FF, &00
  EQUB &FE, &C6, &C6, &E7, &E7, &E7, &FF, &00
  \ 95  logo cell 5
  EQUB &FF, &00, &00, &00, &00, &00, &FF, &00
  EQUB &67, &06, &66, &77, &77, &77, &77, &00
  \ 96  logo cell 6
  EQUB &F0, &30, &30, &30, &30, &30, &F0, &30
  EQUB &F0, &30, &30, &38, &38, &38, &FB, &00
  \ 97  box bar
  EQUB &3C, &3C, &3C, &3C, &3C, &3C, &3C, &3C
  EQUB &3C, &3C, &3C, &3C, &3C, &3C, &3C, &3C
  \ 98  '-'
  EQUB &00, &00, &00, &00, &00, &00, &00, &F6
  EQUB &FE, &DE, &00, &00, &00, &00, &00, &00
  \ 99  ':'
  EQUB &00, &00, &00, &00, &70, &70, &00, &00
  EQUB &00, &00, &70, &70, &00, &00, &00, &00
  \ 100  'm' right
  EQUB &00, &00, &00, &00, &70, &78, &9C, &8C
  EQUB &8C, &8C, &8C, &8C, &00, &00, &00, &00
  \ 101  'w' right
  EQUB &00, &00, &00, &00, &B8, &BC, &8E, &86
  EQUB &86, &CE, &FC, &78, &00, &00, &00, &00
  \ 102  '!'
  EQUB &00, &00, &70, &70, &70, &70, &70, &70
  EQUB &70, &00, &70, &70, &00, &00, &00, &00
  \ 103  '?'
  EQUB &00, &00, &70, &78, &1C, &0C, &1C, &78
  EQUB &70, &00, &70, &70, &00, &00, &00, &00
.textfont_end
ASSERT textfont_end - textfont == GEN_FONT_BYTES
ASSERT GEN_FONT_GLYPHS == FONT_GLYPHS
ASSERT GEN_FONT_BYTES  == FONT_BYTES

\ ------------------------------------------------------------
\ panelframe - the status box border, twelve MODE 1 cells
\ ------------------------------------------------------------
\ HALF glyphs, 8 packed bytes each, not 16: the box is 32 scanlines
\ and
\ the border rows contribute only their inner 8. Row 0 of the panel
\ is cells 0,1 then 18 x (2,3) then 4,5; row 3 is 6,7 then
\ 18 x (8,9) then 10, 11 - which is $6900 and $693C exactly.
.panelframe
  \  0  top-left  L  ($55 lower half)
  EQUB &FE, &F0, &C0, &83, &0F, &1F, &1E, &3C
  \  1  top-left  R  ($75 lower half)
  EQUB &00, &00, &7F, &F8, &C0, &00, &00, &00
  \  2  top-mid   L  ($56 lower half)
  EQUB &00, &00, &FF, &00, &00, &00, &00, &00
  \  3  top-mid   R  ($76 lower half)
  EQUB &00, &00, &FF, &00, &00, &00, &00, &00
  \  4  top-right L  ($57 lower half)
  EQUB &00, &00, &FE, &1F, &03, &00, &00, &00
  \  5  top-right R  ($77 lower half)
  EQUB &7F, &0F, &03, &C1, &F0, &F8, &78, &3C
  \  6  bot-left  L  ($58 upper half)
  EQUB &3C, &1E, &1F, &0F, &83, &C0, &F0, &FE
  \  7  bot-left  R  ($78 upper half)
  EQUB &00, &00, &00, &C0, &F8, &7F, &00, &00
  \  8  bot-mid   L  ($59 upper half)
  EQUB &00, &00, &00, &00, &00, &FF, &00, &00
  \  9  bot-mid   R  ($79 upper half)
  EQUB &00, &00, &00, &00, &00, &FF, &00, &00
  \ 10  bot-end 1    ($7A upper half)
  EQUB &00, &00, &00, &03, &0F, &FE, &00, &00
  \ 11  bot-end 2    ($7B upper half)
  EQUB &3C, &78, &F8, &F0, &C1, &03, &0F, &7F
.panelframe_end
ASSERT panelframe_end - panelframe == GEN_FRAME_BYTES
ASSERT GEN_FRAME_CELLS == PN_FRAME_CELLS
ASSERT GEN_FRAME_BYTES == PN_FRAME_BYTES

