\ ============================================================
\ xferboard.asm - GENERATED by tools/export_xfer.py, do not edit
\ ============================================================
\ The transfer minigame board: SubGameTopLines_dat ($E613), three
\ rows; SubGameLine_dat ($E68B), ONE row the original repeats twelve
\ times; SubGameBottomLine_dat ($E6B3), one row. 200 bytes, and the
\ repeat is why.
\
\ Rows are RAW C64 CODES - the game logic dispatches on the byte in
\ the cell, so the shadow screen keeps the original's values and the
\ renderer owns the code->glyph mapping. Three glyph sets: neutral
\ (logical 3), player (3 rewritten to 1), CPU (3 rewritten to 2) -
\ ownership as a character-set choice, route A of
\ docs/layer-10-transfer.md section 5.

XB_CHARS = 17
XB_COLS  = 40

XB_GLYPHS = 38

\ Offsets into the depacked image at XB_BASE. THE ORDER IS
\ THE LAYOUT: change one and you change the other.
XB_O_CODE =    0
XB_O_POOL =   17
XB_O_SLOT =  625
XB_O_TOP  =  676
XB_O_MID  =  796
XB_O_BOT  =  836
XB_UNPACKED = 876

\ ...and the names the renderer already uses, now pointing at
\ the depacked image instead of at bytes in this bank. Every
\ read site in xfer.asm is unchanged. XB_BASE is main.asm's,
\ declared beside the INCLUDE so the choice of arena is not
\ buried in generated code.
xbCode   = XB_BASE + XB_O_CODE
xbPool   = XB_BASE + XB_O_POOL
xbSlot   = XB_BASE + XB_O_SLOT
xbTop    = XB_BASE + XB_O_TOP
xbMid    = XB_BASE + XB_O_MID
xbBottom = XB_BASE + XB_O_BOT

\ The board, ZX0 (v2, forwards): 288 bytes packed from 876.
\ XfStart depacks it into the tile map -- see xfer.asm.
.xbPack
  EQUB &04, &85, &00, &D0, &D1, &F1, &F2, &F3, &F4, &F5, &F6, &F7, &F8, &F9, &FA, &FB
  EQUB &FC, &FD, &FE, &00, &6A, &33, &9A, &FF, &33, &AF, &CC, &F0, &F9, &F5, &CA, &3E
  EQUB &E3, &F0, &5E, &B0, &7F, &E4, &F8, &FE, &F0, &0F, &DE, &5F, &FE, &5F, &A2, &5F
  EQUB &60, &78, &BC, &0D, &9D, &F0, &CE, &C6, &0A, &79, &D8, &A1, &33, &F7, &C8, &DE
  EQUB &6E, &A0, &4B, &CF, &76, &A0, &DC, &3F, &80, &A4, &CF, &A5, &3F, &88, &CF, &CF
  EQUB &FF, &C4, &FF, &FB, &DC, &E2, &B8, &DE, &E0, &3C, &DE, &A4, &CF, &E9, &FF, &CF
  EQUB &7F, &E8, &DF, &E0, &A2, &BD, &3F, &82, &B9, &0F, &FE, &F7, &F0, &DA, &40, &FF
  EQUB &4F, &FF, &9D, &40, &FA, &60, &42, &97, &CC, &F7, &E3, &E0, &D3, &82, &DA, &CF
  EQUB &81, &FC, &02, &96, &F3, &92, &FC, &96, &F3, &23, &FC, &FC, &FF, &C4, &FF, &DC
  EQUB &EE, &E2, &DE, &E0, &E0, &F2, &DE, &93, &FC, &A5, &FF, &FC, &FF, &E8, &E0, &7E
  EQUB &A2, &F6, &F3, &82, &E7, &F0, &FE, &DF, &F0, &40, &69, &FF, &3E, &FF, &40, &77
  EQUB &80, &EA, &42, &CC, &5F, &E3, &DF, &E0, &82, &4E, &CF, &00, &E8, &01, &02, &03
  EQUB &03, &04, &05, &06, &07, &08, &07, &09, &0A, &0B, &0C, &0D, &07, &DE, &48, &0E
  EQUB &0F, &10, &11, &12, &13, &14, &15, &16, &17, &89, &18, &19, &84, &88, &1A, &1B
  EQUB &1C, &1D, &1E, &1F, &20, &21, &22, &23, &B8, &24, &25, &FE, &1A, &FB, &A1, &00
  EQUB &18, &91, &F5, &00, &8A, &D0, &F8, &E4, &D1, &BE, &27, &F6, &F1, &FD, &C2, &B0
  EQUB &24, &FE, &FE, &66, &F3, &F2, &F6, &0A, &FD, &7C, &FE, &22, &F9, &F8, &89, &FA
  EQUB &F2, &1E, &B1, &DE, &F3, &F0, &95, &F7, &CF, &FD, &DE, &4F, &BE, &D5, &55, &60
.xbPack_end

